### ISSUE TITLE
Consistency of `configure --enable-threading=openmp`

### ISSUE THREAD

**Issue by heroxbd** [flame/blis#114]
From fd04869ae4d4a3, both --enable-threading=openmp and --enable-threading=omp are accepted.

But from 11eed3f683d09, although `configure --enable-threading=omp` is valid, common.mk will not append -fopenmp to CTHREADFLAGS and LDFLAGS, resulting in under-linking.

In addition, wiki page

  https://github.com/flame/blis/wiki/Multithreading

Should use 'openmp' instead of 'omp' in `configure --enable-threading=openmp`.

**Comment by fgvanzee** [comment]
I've pushed a commit, 018180c9, to fix the `configure` bug. Thanks for reporting this issue! I've also fixed the wiki page. Please let me know if you encounter any further problems.

**Comment by heroxbd** [comment]
Thanks, Field!
