### ISSUE TITLE
Completeness of BLAS compatibility layer (like dcabs1_)

### ISSUE THREAD

**Issue by heroxbd** [flame/blis#115]
I have compiled blis on Intel MIC Knight Landing, with the following options:

`./configure --enable-threading=openmp --enable-blas --enable-cblas knl`

But when I link [R](https://www.r-project.org/) to it, the BLAS compatibility layer cannot pass the completeness test of R configuration,
> checking for dgemm_ in -lblis... yes
> checking whether double complex BLAS can be used... yes
> checking whether the BLAS is complete... no

The related part of config.log is:
> conftest.o: In function 'blas_set':
> /dev/shm/portage/dev-lang/R-3.3.2/work/R-3.3.2/conftest.c:49: undefined reference to 'dcabs1_' 
> collect2: error: ld returned 1 exit status              
> configure:32282: result: no

The similar issue is found when I build numpy and scipy against the BLAS compatibility layer,

> python -c 'from scipy import linalg'
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/work/0/gh60/share/knl/usr/lib64/python2.7/site-packages/scipy/linalg/__init__.py", line 190, in <module>
>     from ._decomp_update import *
>   File "scipy/linalg/_decomp_update.pyx", line 1, in init scipy.linalg._decomp_update (scipy/linalg/_decomp_update.c:38525)
> ImportError: /work/0/gh60/share/knl/usr/lib64/python2.7/site-packages/scipy/linalg/cython_blas.so: undefined symbol: dcabs1_

I have looked up dcabs1_ . It is a [BLAS layer 1 function](http://www.netlib.org/lapack/explore-html/de/da4/group__double__blas__level1_ga53914429b84cb315da483e71e27ed5c1.html#ga53914429b84cb315da483e71e27ed5c1) trivial to implement with 3 lines of fortran.

I am not certain if this is a design decision of blis or a bug, or rather my compilation is incorrect.

If blis can provide these trivial functions for a complete BLAS API, I am sure it will be deployed more widely.

**Comment by fgvanzee** [comment]
@heroxbd Thanks for pointing this out. (I wasn't aware that the BLAS compatibility layer was missing any functionality.) I'll work on a fix.

**Comment by fgvanzee** [comment]
@heroxbd I've committed a fix in c362afc5. Please give it a try. (There may be other BLAS functionality that is still missing from the compatibility layer.)

**Comment by heroxbd** [comment]
It works! Thanks Field.
