### ISSUE TITLE
Kernel symlinks cause build failure in msys2

### ISSUE THREAD

**Issue by tkelman** [flame/blis#13]
Another one for you, following up on https://github.com/flame/blis/pull/9

When I try to build the Sandy Bridge configuration on Windows in MSYS2 with MinGW compiler (on an i7-2630QM), I get a failure to link the test executable:

```
Archiving lib/sandybridge/libblis.a
Linking test_libblis.x against './lib/sandybridge/libblis.a -lm'
./lib/sandybridge/libblis.a(bli_gemm_cntl.o):bli_gemm_cntl.c:(.text+0x1bc): undefined reference to `bli_dgemm_opt_8x4_ref_u4_nodupl_avx1'
./lib/sandybridge/libblis.a(bli_gemm_ukernel.o):bli_gemm_ukernel.c:(.text+0x11): undefined reference to `bli_dgemm_opt_8x4_ref_u4_nodupl_avx1'
./lib/sandybridge/libblis.a(bli_gemmtrsm_l_ukr_ref.o):bli_gemmtrsm_l_ukr_ref.c:(.text+0x10d): undefined reference to `bli_dgemm_opt_8x4_ref_u4_nodupl_avx1'
./lib/sandybridge/libblis.a(bli_gemmtrsm_u_ukr_ref.o):bli_gemmtrsm_u_ukr_ref.c:(.text+0x10d): undefined reference to `bli_dgemm_opt_8x4_ref_u4_nodupl_avx1'
./lib/sandybridge/libblis.a(bli_gemm4m_ukr_ref.o):bli_gemm4m_ukr_ref.c:(.text+0xe94): undefined reference to `bli_dgemm_opt_8x4_ref_u4_nodupl_avx1'
./lib/sandybridge/libblis.a(bli_gemm4m_ukr_ref.o):bli_gemm4m_ukr_ref.c:(.text+0xedb): more undefined references to `bli_dgemm_opt_8x4_ref_u4_nodupl_avx1' follow
d:/code/mingw-builds/x64-4.8.1-win32-seh-rev5/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.1/../../../../x86_64-w64-mingw32/bin/ld.exe: ./lib/sandybridge/libblis.a(bli_gemm4m_ukr_ref.o): bad reloc address 0x0 in section `.pdata'
collect2.exe: error: ld returned 1 exit status
Makefile:531: recipe for target 'test_libblis.x' failed
make: *** [test_libblis.x] Error 1
```

If I try in Cygwin, setting `CC := x86_64-w64-mingw32-gcc` and `AR := x86_64-w64-mingw32-ar` in `config/sandybridge/make_defs.mk` to use the MinGW cross-compiler, then the executable links correctly but segfaults when running the tests. The backtrace is more interesting if I set `BLIS_SIMD_ALIGN_SIZE` to 1 in `config/sandybridge/config.h`, since my patch in #9 didn't completely fix the alignment problems. Backtrace with alignment=1 (also uncommented `CDBGFLAGS := -g` to get debug info) posted here https://gist.github.com/tkelman/25d290b131c0a1205b27. Everything passes until `blis_dgemm_nn_ccc`. The same `bli_dgemm_opt_8x4_ref_u4_nodupl_avx1` that was an undefined reference in MSYS2 is causing the segfault in Cygwin-to-MinGW cross-compile.

**Comment by tkelman** [comment]
The segfault appears to have been fixed some over the past 18 months. The MSYS2 symlink build issue can either be documented, or the symlinks could be created at configure time rather than being checked in to git. The handling of symlinks in git is not very portable.

**Comment by njsmith** [comment]
@tkelman: the simplest change would probably be to change it so that instead of knowing that the kernel directory is always `config/<name>/kernels`, instead have the kernel directory specified as a variable in `config/<name>/make_defs.mk`. Then we could remove the symlinks in general.

**Comment by tkelman** [comment]
I like that idea, and it sounds like it would work. I'm not the one who would be hitting merge though.

**Comment by devinamatthews** [comment]
Given our Appveyor CI these days, I assume this is fixed.
