### ISSUE TITLE
When bli_malloc_align fails, may print an error message before aborting ?

### ISSUE THREAD

**Issue by hominhquan** [flame/blis#136]
Hi all, 

I know this mostly never arrives. But when it arrives, I find it a little
unpleasant to see the execution aborted without any information 
about the cause. (in fact I get something similar to "libblis : aborted")

Quan

**Comment by fgvanzee** [comment]
@hominhquan I'm not sure how this issue slipped by without anyone noticing, or commenting. Sorry about that.

BLIS is actually not supposed to `abort()` like this. We plan for certain situations to end in `abort()`, but they all come with an error message. If you ever experience an `abort()` without an error message, it means something went very wrong (such as BLIS was never initialized, or an "assertion" that was never thought to be able to fail, failed).

Do you still experience this issue? If so, a backtrace through `gdb` (with BLIS configured with `-d noopt`) would be a good starting point to investigate.

**Comment by hominhquan** [comment]
@fgvanzee yes, as you said, `bli_abort()` occured only when execution goes really wrong. The abort I'm talking about is in the malloc function of BLIS:
https://github.com/flame/blis/blob/0645f239fbdf37ee9d2096ee3bb0e76b3302cfff/frame/base/bli_malloc.c#L119:L120

I know that out-of-memory is something very rare, or never happens, since Linux is using [opportunistic allocation](https://books.google.fr/books?id=LOeK6EZfiH0C&pg=PT456&lpg=PT456&dq=linux+opportunistic+allocation&source=bl&ots=HcjkIARpB_&sig=cTwlw_QEjGj_UqcPGgjmySRfovY&hl=en&sa=X&ved=2ahUKEwib6q_A8s7fAhUyUBUIHd1cDqMQ6AEwAXoECAkQAQ#v=onepage&q=linux%20opportunistic%20allocation&f=false). I am thinking for other non-linux systems on which such situation may come. And if it is the case, a printf message would help saving some time to the developer.

**Comment by fgvanzee** [comment]
Oh, of course; I misunderstood. Sorry about that confusion, @hominhquan. You are absolutely right that the code does not currently check for out-of-memory situations. I will take care of this.

**Comment by fgvanzee** [comment]
@hominhquan Try the head of `master` now (currently 7052fca). This commit integrates some unrelated memory allocation changes I made over the holiday break and also includes an error message when `malloc()` returns `NULL` in the recently renamed `bli_fmalloc_align()` function. I've also applied the same behavior to `bli_fmalloc_noalign()`.

**Comment by hominhquan** [comment]
@fgvanzee Your commit suits me perfectly. Thank you and I close the ticket.

**Comment by fgvanzee** [comment]
Great, thanks Minh. Sorry it took so long! And as luck would have it, I was already almost there when I stumbled upon the issue again. :)
