### ISSUE TITLE
build error (0.2.1 & 0.2.0) on buildroot but 0.1.8 version is ok  

### ISSUE THREAD

**Issue by lujnan** [flame/blis#137]
```
/usr/bin/make -j41 CC=/home/lujnan/works/linux_amlogic_a1xx/output/nana_l_a112/host/usr/bin/aarch64-linux-gnu-gcc LD=/home/lujnan/works/linux_amlogic_a1xx/output/nana_l_a112/host/usr/bin/aarch64-linux-gnu-ld -C /home/lujnan/works/linux_amlogic_a1xx/output/nana_l_a112/build/blis-0.2.1 all
Compiling config/armv8a/kernels/3/bli_gemm_opt_4x4.c (NOTE: using flags for kernels)
Compiling frame/0/bli_l0_check.c
Compiling frame/0/bli_l0_oapi.c
Compiling frame/0/bli_l0_tapi.c
Compiling frame/0/copysc/bli_copysc.c
Compiling frame/1/bli_l1v_check.c
Compiling frame/1/bli_l1v_cntx.c
Compiling frame/1/bli_l1v_oapi.c
Compiling frame/1/bli_l1v_oapi_wc.c
Compiling frame/1/bli_l1v_oapi_woc.c
Compiling frame/1/bli_l1v_tapi.c
Compiling frame/1/kernels/bli_addv_ref.c (NOTE: using flags for kernels)
Compiling frame/1/kernels/bli_amaxv_ref.c (NOTE: using flags for kernels)
Compiling frame/1/kernels/bli_axpbyv_ref.c (NOTE: using flags for kernels)
Compiling frame/1/kernels/bli_axpyv_ref.c (NOTE: using flags for kernels)
Compiling frame/1/kernels/bli_copyv_ref.c (NOTE: using flags for kernels)
Compiling frame/1/kernels/bli_dotv_ref.c (NOTE: using flags for kernels)
Compiling frame/1/kernels/bli_dotxv_ref.c (NOTE: using flags for kernels)
Compiling frame/1/kernels/bli_invertv_ref.c (NOTE: using flags for kernels)
Compiling frame/1/kernels/bli_scal2v_ref.c (NOTE: using flags for kernels)
Compiling frame/1/kernels/bli_scalv_ref.c (NOTE: using flags for kernels)
Compiling frame/1/kernels/bli_setv_ref.c (NOTE: using flags for kernels)
Compiling frame/1/kernels/bli_subv_ref.c (NOTE: using flags for kernels)
Compiling frame/1/kernels/bli_swapv_ref.c (NOTE: using flags for kernels)
Compiling frame/1/kernels/bli_xpbyv_ref.c (NOTE: using flags for kernels)
Compiling frame/1d/bli_l1d_cntx.c
Compiling frame/1d/bli_l1d_oapi.c
Compiling frame/1d/bli_l1d_oapi_wc.c
Compiling frame/1d/bli_l1d_check.c
Compiling frame/1d/bli_l1d_oapi_woc.c
Compiling frame/1d/bli_l1d_tapi.c
Compiling frame/1f/bli_l1f_check.c
Compiling frame/1f/bli_l1f_cntx.c
Compiling frame/1f/bli_l1f_oapi.c
Compiling frame/1f/bli_l1f_oapi_wc.c
Compiling frame/1f/bli_l1f_oapi_woc.c
Compiling frame/1f/bli_l1f_tapi.c
Compiling frame/1f/kernels/bli_axpy2v_ref.c (NOTE: using flags for kernels)
Compiling frame/1f/kernels/bli_axpyf_ref.c (NOTE: using flags for kernels)
config/armv8a/kernels/3/bli_gemm_opt_4x4.c:53:6: error: conflicting types for ‘bli_sgemm_opt_8x12’
 void bli_sgemm_opt_8x12(
      ^
In file included from ./frame/include/blis.h:84:0,
                 from config/armv8a/kernels/3/bli_gemm_opt_4x4.c:36:
./config/armv8a/bli_kernel.h:153:36: note: previous declaration of ‘bli_sgemm_opt_8x12’ was here
 #define BLIS_SGEMM_UKERNEL         bli_sgemm_opt_8x12
                                    ^
./frame/include/bli_kernel_prototypes.h:44:34: note: in expansion of macro ‘BLIS_SGEMM_UKERNEL’
 #define bli_sgemm_ukr_name       BLIS_SGEMM_UKERNEL
                                  ^
./frame/include/bli_macro_defs.h:89:36: note: in expansion of macro ‘bli_sgemm_ukr_name’
 #define PASTEMAC_(ch,op)           bli_ ## ch  ## op
                                    ^
./frame/include/bli_macro_defs.h:90:36: note: in expansion of macro ‘PASTEMAC_’
 #define PASTEMAC(ch,op)            PASTEMAC_(ch,op)
                                    ^
./frame/3/bli_l3_ukr.h:42:6: note: in expansion of macro ‘PASTEMAC’
 void PASTEMAC(ch,opname) \
      ^
./frame/include/bli_gentprot_macro_defs.h:134:1: note: in expansion of macro ‘GENTPROT’
 GENTPROT( float,    s, funcname ) \
 ^
./frame/3/bli_l3_ukr.h:54:1: note: in expansion of macro ‘INSERT_GENTPROT_BASIC’
 INSERT_GENTPROT_BASIC( gemm_ukr_name )
 ^
config/armv8a/kernels/3/bli_gemm_opt_4x4.c:1102:6: error: conflicting types for ‘bli_dgemm_opt_6x8’
 void bli_dgemm_opt_6x8(
      ^
In file included from ./frame/include/blis.h:84:0,
                 from config/armv8a/kernels/3/bli_gemm_opt_4x4.c:36:
./config/armv8a/bli_kernel.h:154:36: note: previous declaration of ‘bli_dgemm_opt_6x8’ was here
 #define BLIS_DGEMM_UKERNEL         bli_dgemm_opt_6x8
                                    ^
./frame/include/bli_kernel_prototypes.h:45:34: note: in expansion of macro ‘BLIS_DGEMM_UKERNEL’
 #define bli_dgemm_ukr_name       BLIS_DGEMM_UKERNEL
                                  ^
./frame/include/bli_macro_defs.h:89:36: note: in expansion of macro ‘bli_dgemm_ukr_name’
 #define PASTEMAC_(ch,op)           bli_ ## ch  ## op
                                    ^
./frame/include/bli_macro_defs.h:90:36: note: in expansion of macro ‘PASTEMAC_’
 #define PASTEMAC(ch,op)            PASTEMAC_(ch,op)
                                    ^
./frame/3/bli_l3_ukr.h:42:6: note: in expansion of macro ‘PASTEMAC’
 void PASTEMAC(ch,opname) \
      ^
./frame/include/bli_gentprot_macro_defs.h:135:1: note: in expansion of macro ‘GENTPROT’
 GENTPROT( double,   d, funcname ) \
 ^
./frame/3/bli_l3_ukr.h:54:1: note: in expansion of macro ‘INSERT_GENTPROT_BASIC’
 INSERT_GENTPROT_BASIC( gemm_ukr_name )
 ^
In file included from ./frame/include/blis.h:86:0,
                 from config/armv8a/kernels/3/bli_gemm_opt_4x4.c:36:
config/armv8a/kernels/3/bli_gemm_opt_4x4.c: In function ‘bli_cgemm_opt_4x4’:
./frame/include/bli_kernel_pre_macro_defs.h:48:42: error: too few arguments to function ‘bli_cgemm_ukr_ref’
 #define BLIS_CGEMM_UKERNEL_REF           bli_cgemm_ukr_ref
                                          ^
config/armv8a/kernels/3/bli_gemm_opt_4x4.c:2082:2: note: in expansion of macro ‘BLIS_CGEMM_UKERNEL_REF’
  BLIS_CGEMM_UKERNEL_REF( k,
  ^
In file included from ./frame/include/blis.h:69:0,
                 from config/armv8a/kernels/3/bli_gemm_opt_4x4.c:36:
./frame/include/bli_macro_defs.h:89:36: note: declared here
 #define PASTEMAC_(ch,op)           bli_ ## ch  ## op
                                    ^
./frame/include/bli_macro_defs.h:90:36: note: in expansion of macro ‘PASTEMAC_’
 #define PASTEMAC(ch,op)            PASTEMAC_(ch,op)
                                    ^
./frame/3/bli_l3_ukr.h:42:6: note: in expansion of macro ‘PASTEMAC’
 void PASTEMAC(ch,opname) \
      ^
./frame/include/bli_gentprot_macro_defs.h:136:1: note: in expansion of macro ‘GENTPROT’
 GENTPROT( scomplex, c, funcname ) \
 ^
./frame/3/bli_l3_ukr.h:54:1: note: in expansion of macro ‘INSERT_GENTPROT_BASIC’
 INSERT_GENTPROT_BASIC( gemm_ukr_name )
 ^
In file included from ./frame/include/blis.h:86:0,
                 from config/armv8a/kernels/3/bli_gemm_opt_4x4.c:36:
config/armv8a/kernels/3/bli_gemm_opt_4x4.c: In function ‘bli_zgemm_opt_4x4’:
./frame/include/bli_kernel_pre_macro_defs.h:49:42: error: too few arguments to function ‘bli_zgemm_ukr_ref’
 #define BLIS_ZGEMM_UKERNEL_REF           bli_zgemm_ukr_ref
                                          ^
config/armv8a/kernels/3/bli_gemm_opt_4x4.c:2102:2: note: in expansion of macro ‘BLIS_ZGEMM_UKERNEL_REF’
  BLIS_ZGEMM_UKERNEL_REF( k,
  ^
In file included from ./frame/include/blis.h:69:0,
                 from config/armv8a/kernels/3/bli_gemm_opt_4x4.c:36:
./frame/include/bli_macro_defs.h:89:36: note: declared here
 #define PASTEMAC_(ch,op)           bli_ ## ch  ## op
                                    ^
./frame/include/bli_macro_defs.h:90:36: note: in expansion of macro ‘PASTEMAC_’
 #define PASTEMAC(ch,op)            PASTEMAC_(ch,op)
                                    ^
./frame/3/bli_l3_ukr.h:42:6: note: in expansion of macro ‘PASTEMAC’
 void PASTEMAC(ch,opname) \
      ^
./frame/include/bli_gentprot_macro_defs.h:137:1: note: in expansion of macro ‘GENTPROT’
 GENTPROT( dcomplex, z, funcname )
 ^
./frame/3/bli_l3_ukr.h:54:1: note: in expansion of macro ‘INSERT_GENTPROT_BASIC’
 INSERT_GENTPROT_BASIC( gemm_ukr_name )
 ^
Compiling frame/1f/kernels/bli_dotaxpyv_ref.c (NOTE: using flags for kernels)
make[2]: *** [obj/armv8a/config/kernels/3/bli_gemm_opt_4x4.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [/home/lujnan/works/linux_amlogic_a1xx/output/nana_l_a112/build/blis-0.2.1/.stamp_built] Error 2
make: *** [_all] Error 2
```

**Comment by figual** [comment]
Hi,

I cannot reproduce this issue on a Juno board with GCC 4.9.1 and BLIS 0.2.1-128.

Is this happening with an unmodified BLIS code?

Fran

**Comment by lujnan** [comment]
No, I don't modify can codes.
my configure cmd is:

(cd /home/lujnan/works/linux_amlogic_a1xx/output/nana_l_a112/build/blis-0.2.1 && mkdir -p output && ./configure -p output --enable-static armv8a)

**Comment by lujnan** [comment]
umask 0022 && make -C /home/lujnan/works/linux_amlogic_a1xx/buildroot O=/home/lujnan/works/linux_amlogic_a1xx/output/nana_l_a112 blis
WARNING: no hash file for blis-0.2.1.tar.gz
>>> blis 0.2.1 Extracting
gzip -d -c /home/lujnan/works/linux_amlogic_a1xx/buildroot/dl/blis-0.2.1.tar.gz | tar --strip-components=1 -C /home/lujnan/works/linux_amlogic_a1xx/output/nana_l_a112/build/blis-0.2.1   -xf -
>>> blis 0.2.1 Patching
>>> blis 0.2.1 Configuring
(cd /home/lujnan/works/linux_amlogic_a1xx/output/nana_l_a112/build/blis-0.2.1 && mkdir -p output && ./configure -p output --enable-static armv8a)
configure: checking whether we need to update the version file.
configure: checking version file './version'.
configure: starting configuration of BLIS 0.2.1.
configure: manual configuration requested.
configure: configuring with 'armv8a' configuration sub-directory.
configure: using install prefix 'output'.
configure: debug symbols disabled.
configure: disabling verbose make output, enable with 'make V=1'.
configure: building BLIS as a static library.
configure: threading is disabled.
configure: the CBLAS compatibility layer is disabled.
configure: the BLAS compatibility layer is enabled.
configure: the internal integer size is automatically determined.
configure: the BLAS/CBLAS interface integer size is 32-bit.
configure: creating ./config.mk from ./build/config.mk.in
configure: creating ./bli_config.h from ./build/bli_config.h.in
configure: creating ./obj/armv8a
configure: creating ./obj/armv8a/config
configure: creating ./obj/armv8a/frame
configure: creating ./obj/armv8a/testsuite
configure: creating ./lib/armv8a
configure: mirroring ./config/armv8a to ./obj/armv8a/config
configure: mirroring ./frame to ./obj/armv8a/frame
configure: creating makefile fragment in ./config/armv8a
configure: creating makefile fragment in ./config/armv8a/kernels
configure: creating makefile fragment in ./config/armv8a/kernels/3
configure: creating makefile fragment in ./frame
configure: creating makefile fragment in ./frame/0
configure: creating makefile fragment in ./frame/0/copysc
configure: creating makefile fragment in ./frame/1
configure: creating makefile fragment in ./frame/1/kernels
configure: creating makefile fragment in ./frame/1d
configure: creating makefile fragment in ./frame/1f
configure: creating makefile fragment in ./frame/1f/kernels
configure: creating makefile fragment in ./frame/1m
configure: creating makefile fragment in ./frame/1m/packm
configure: creating makefile fragment in ./frame/1m/packm/ukernels
configure: creating makefile fragment in ./frame/1m/scalm
configure: creating makefile fragment in ./frame/1m/unpackm
configure: creating makefile fragment in ./frame/1m/unpackm/ukernels
configure: creating makefile fragment in ./frame/2
configure: creating makefile fragment in ./frame/2/gemv
configure: creating makefile fragment in ./frame/2/ger
configure: creating makefile fragment in ./frame/2/hemv
configure: creating makefile fragment in ./frame/2/her
configure: creating makefile fragment in ./frame/2/her2
configure: creating makefile fragment in ./frame/2/symv
configure: creating makefile fragment in ./frame/2/syr
configure: creating makefile fragment in ./frame/2/syr2
configure: creating makefile fragment in ./frame/2/trmv
configure: creating makefile fragment in ./frame/2/trsv
configure: creating makefile fragment in ./frame/3
configure: creating makefile fragment in ./frame/3/gemm
configure: creating makefile fragment in ./frame/3/gemm/ind
configure: creating makefile fragment in ./frame/3/hemm
configure: creating makefile fragment in ./frame/3/her2k
configure: creating makefile fragment in ./frame/3/herk
configure: creating makefile fragment in ./frame/3/symm
configure: creating makefile fragment in ./frame/3/syr2k
configure: creating makefile fragment in ./frame/3/syrk
configure: creating makefile fragment in ./frame/3/trmm
configure: creating makefile fragment in ./frame/3/trmm3
configure: creating makefile fragment in ./frame/3/trsm
configure: creating makefile fragment in ./frame/3/ukernels
configure: creating makefile fragment in ./frame/base
configure: creating makefile fragment in ./frame/base/check
configure: creating makefile fragment in ./frame/base/noopt
configure: creating makefile fragment in ./frame/compat
configure: creating makefile fragment in ./frame/compat/cblas
configure: creating makefile fragment in ./frame/compat/cblas/f77_sub
configure: creating makefile fragment in ./frame/compat/cblas/src
configure: creating makefile fragment in ./frame/compat/check
configure: creating makefile fragment in ./frame/compat/f2c
configure: creating makefile fragment in ./frame/compat/f2c/util
configure: creating makefile fragment in ./frame/include
configure: creating makefile fragment in ./frame/include/level0
configure: creating makefile fragment in ./frame/include/level0/io
configure: creating makefile fragment in ./frame/include/level0/ri
configure: creating makefile fragment in ./frame/include/level0/ri3
configure: creating makefile fragment in ./frame/include/level0/rih
configure: creating makefile fragment in ./frame/include/level0/ro
configure: creating makefile fragment in ./frame/include/level0/rpi
configure: creating makefile fragment in ./frame/ind
configure: creating makefile fragment in ./frame/ind/cntx
configure: creating makefile fragment in ./frame/ind/include
configure: creating makefile fragment in ./frame/ind/oapi
configure: creating makefile fragment in ./frame/ind/tapi
configure: creating makefile fragment in ./frame/ind/ukernels
configure: creating makefile fragment in ./frame/ind/ukernels/gemm
configure: creating makefile fragment in ./frame/ind/ukernels/trsm
configure: creating makefile fragment in ./frame/thread
configure: creating makefile fragment in ./frame/util
configure: configured to build within top-level directory of source distribution.

**Comment by lujnan** [comment]
@figual 

My toolchain is 4.9.2
```
lujnan@build-6:~/works/linux_amlogic_a1xx$ /home/lujnan/works/linux_amlogic_a1xx/output/nana_l_a112/host/usr/bin/aarch64-linux-gnu-gcc --version
aarch64-linux-gnu-gcc (crosstool-NG linaro-1.13.1-4.9-2014.09 - Linaro GCC 4.9-2014.09) 4.9.2 20140904 (prerelease)
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by fgvanzee** [comment]
@lujnan Sorry we were not able to address your issue last year. We've fixed some bugs recently that may or may not help you get further along. If you have time and interest, please give our latest `master` branch a try.

**Comment by lujnan** [comment]
@fgvanzee release version 0.3.2 now could build on buildroot.

**Comment by fgvanzee** [comment]
@lujnan Glad to hear the new code works for you. Thanks for the update.
