### ISSUE TITLE
Tag "0.2.2" disappeared at some point after initial tagging?

### ISSUE THREAD

**Issue by fgvanzee** [flame/blis#142]
It seems that the 0.2.2 tag was missing from the master branch. I checked out the commit referenced in the `CHANGELOG`, re-tagged it, and pushed that tag to github and everything seems to be fine now. Any ideas how this might have happened?

**Comment by devinamatthews** [comment]
If you still had the tag locally you could just re-push it. Did you do a forced update at some point?

**Comment by fgvanzee** [comment]
I didn't have the tag locally anymore, either. It's as if someone deleted it and that deletion silently trickled down to my clones. Really weird.

Could you elaborate on what you mean by a forced update?

**Comment by devinamatthews** [comment]
git push --force, e.g. for amending a commit you've already pushed. This can change the hash so the old tag would point to oblivion.

**Comment by fgvanzee** [comment]
Not sure if I ever got to the bottom of this, but it's hopefully moot now. Closing.
