### ISSUE TITLE
Support of BlueGene/Q

### ISSUE THREAD

**Issue by chiensh** [flame/blis#143]
I would like to confirm that if BlueGene is no longer supported:  the latest version of BLIS cannot be compiled
Compiling ../frame/thread/bli_thrcomm.c
```
../frame/thread/bli_thrcomm.c", line 69.68: 1506-045 (S) Undeclared identifier __ATOMIC_RELAXED.
../frame/thread/bli_thrcomm.c", line 75.64: 1506-045 (S) Undeclared identifier __ATOMIC_ACQ_REL.
../frame/thread/bli_thrcomm.c", line 87.62: 1506-045 (S) Undeclared identifier __ATOMIC_RELEASE.
../frame/thread/bli_thrcomm.c", line 94.64: 1506-045 (S) Undeclared identifier __ATOMIC_ACQUIRE.
```
and the failure in the test cases reported previously have not been addressed for nearly a year.

**Comment by devinamatthews** [comment]
PR #144 should fix this issue. As for the previous problems (#34), I think the failures should not affect the results unless you go out of your way to make use of the 4mh induced method. @fgvanzee can you comment on whether 4mh failures will affect results using default settings?

**Comment by fgvanzee** [comment]
@chiensh: @devinamatthews is correct. You can ignore the failures in 4mh. This has been a long-standing issue that seems to crop up occasionally, go away for a while, and then come back. It may actually be a compiler bug, though if it were it would be consistent with a similar bug in `icc` :)
