### ISSUE TITLE
Any make template for Epyc available? 

### ISSUE THREAD

**Issue by hanyunfan** [flame/blis#151]
Or can you help to provide the steps to create it?

**Comment by devinamatthews** [comment]
AMD EPYC/Ryzen support is available in the `amd` branch as well as at AMD's fork of BLIS for their ACL libraries: https://github.com/amd/blis (the former may or may not be up to date with the latter).

**Comment by fgvanzee** [comment]
@hanyunfan Thanks for your interest in BLIS.

We expect to have explicit support for Zen architectures soon.

**Comment by hanyunfan** [comment]
thanks a lot. found it at: https://github.com/flame/blis/commit/0b19029342ffc530fa22ef20398a26221cb8f6ec

**Comment by devinamatthews** [comment]
@hanyunfan That commit is a ways back on the `amd` branch...
