### ISSUE TITLE
OSX:  any issues with building openmp+pthread libs?

### ISSUE THREAD

**Issue by gaming-hacker** [flame/blis#152]
All,

Has anyone API problems  for haswell and using openmp and pthread libs?  or is it either one lib or the other?

**Comment by jeffhammond** [comment]
No. Please report an issue or discuss on mailing list. This is not a proper
issue report, since it contains no useful information.
-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by gaming-hacker** [comment]
Why don't you configure the build bot to run the configuration and do regression test.

**Comment by devinamatthews** [comment]
If you are encountering a specific problem please provide the details (platform, compiler, configuration, error output, etc.).

**Comment by fgvanzee** [comment]
@gaming-hacker If you are still having issues and would like our help, please provide more information so we can better assist. (I'm going to close this issue for now, but we can reopen it if needed.)

Note that some of the threading API was recently updated and reimplemented, so it may be that whatever issue you originally encountered has been fixed.
