### ISSUE TITLE
support for older Intel64 arhictectures?

### ISSUE THREAD

**Issue by gshamov** [flame/blis#155]
The documentation mentions Penryn; but it is not in the config anymore? 
We still run Nehalem/Wesmeres and would be glad to have BLIS on pre-AVX machines.

**Comment by jeffhammond** [comment]
Dunnington is the target for SSE4 chips.
-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by fgvanzee** [comment]
@gshamov Sorry for the confusion. The wiki documentation is temporarily inconsistent with the `master` branch. I'm preparing to merge the `rt` branch, which will be the new basis for `master` going forward.

Don't worry: Your pre-AVX systems will remain supported in BLIS. In `rt`, I've renamed the `dunnington` configuration to `penryn`. But that is simply a microarchitectural approximation; the `penryn` configuration applies to several processor revisions, including Penryn, Nehalem, and Westmere. (Honestly, I'm considering renaming it again to something more general, like `core2`.) 

In any case, I recommend that you begin using `rt`, as it is basically stable and ready to use.

**Comment by jeffhammond** [comment]
> Don't worry: Your pre-AVX systems will remain supported in BLIS. In rt,
> I've renamed the dunnington configuration to penryn. But that is simply a
> microarchitectural approximation; the penryn configuration applies to
> several processor revisions, including Penryn, Nehalem, and Westmere.
> (Honestly, I'm considering renaming it again to something more general,
> like core2.
>

I’d just use SSE-whatever since that’s the first-order hardware requirement.

> --
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by gshamov** [comment]
Thanks!
