### ISSUE TITLE
families are not enabled in rt branch?

### ISSUE THREAD

**Issue by iotamudelta** [flame/blis#156]
in bli_arch.c, bli_cpuid_query_id(); is only enabled if BLIS_FAMILY_INTEL64 or BLIS_FAMILY_AMD64 are defined. However, these macros are not defined elsewhere?

More importantly, the x86_64 family also needs this logic (and the correct macro).

**Comment by devinamatthews** [comment]
This should probably use standard predefined macros (something like `
#if defined(__x86_64__) || defined(_M_X64) || defined(__i386) || defined(_M_IX86)` for x86/x64 or `#if defined(__aarch64__) || defined(__arm__) || defined(_M_ARM)` for ARM).

**Comment by fgvanzee** [comment]
@iotamudelta The `BLIS_FAMILY_` macro is defined by the build system in `bli_config.h` for whichever family was targeted by `configure`.

You are right that I forgot to add support for the `x86_64` family. I'll commit a fix.
