### ISSUE TITLE
Add CI builds for out-of-tree and installation

### ISSUE THREAD

**Issue by devinamatthews** [flame/blis#162]
Two CI builds should be added to test:
- Out-of-tree builds, and
- Installation

The first is easy to do. The second needs a bit of care that the entire installation is actually tested. I think that using the installed headers and libs to build the testsuite would be sufficient. Neither of these probably need to run the testsuite.

Some good additional tests include:
- [x] Out-of-tree
    - [ ] Concurrent builds
    - [x] Read-only source dir
- [ ] Installation
    - [ ] Delete build/src dir

Now that we have the `rt` branch, the CI builds probably need some consolidation as well.

**Comment by devinamatthews** [comment]
I made it into a checklist and update to reflect.

**Comment by fgvanzee** [comment]
Oh, very nice. I didn't realize you could insert checkboxes with github markdown!

**Comment by devinamatthews** [comment]
The monolithic `blis.h` actually solves the typical installation problems, so the current solution is good enough.
