### ISSUE TITLE
building x86_64 shared library fails

### ISSUE THREAD

**Issue by loveshack** [flame/blis#168]
After configuring version 0.3.0 with "--enable-shared x86_64" on GNU/Linux with gcc, linking the shared library fails with many errors due to objects not being built with -fPIC. I think they're all built with -march=core2 under frame, starting with

gcc -O3 -mssse3 -mfpmath=sse -march=core2 -I./include/x86_64 -I./frame/3/ -I./frame/ind/ukernels/ -I./frame/1m/ -I./frame/1f/ -I./frame/1/ -I./frame/include -DBLIS_VERSION_STRING=\"0.3.0\" -c frame/0/bli_l0_check.c -o obj/x86_64/frame/0/bli_l0_check.o

but I can't immediately see what's wrong.

**Comment by fgvanzee** [comment]
@loveshack Thanks for this bug report. I think I see what's going on, but the fix is not immediately obvious. I'll take a harder look at it when I get back into the office on Monday.

**Comment by fgvanzee** [comment]
@loveshack I think I've fixed this issue in 8912e688. Please give it a try. And thanks again for taking the time to provide us with this valuable feedback.

**Comment by loveshack** [comment]
Confirmed fixed, thanks.
