### ISSUE TITLE
simple sanity test

### ISSUE THREAD

**Issue by loveshack** [flame/blis#171]
I think it would be useful to have a make target that does a quick sanity check of the build, presumably a small subset of the "test" target.  Looking at packaging, I think the full test suite is too time-consuming to be reasonable for building distribution packages, but it's generally a good to have a %check stanza in rpm, for instance.

**Comment by fgvanzee** [comment]
@loveshack Could you elaborate? For example:

1. What things would you like to see affirmatively tested in such a sanity test?
2. What kinds of situations you would the sanity test to rule out?

(Notice that the testsuite is designed to test a cross section of numerical correctness of most operations in BLIS; it doesn't test the build system, per se.)

**Comment by loveshack** [comment]
You wrote: 

> @loveshack Could you elaborate? For example:
>
> 1. What things would you like to see affirmatively tested in such a sanity test?
> 2. What kinds of situations you would the sanity test to rule out?

It's basically checking that the built library works to run a short test
correctly, e.g. a few cases in dblat.f if one was using Fortran.
(Obviously I can do that in packaging, so it's not a big deal, but I
thought it might be more generally useful.)  A random short case from
the testsuite should be good enough, but I haven't looked at what's
there.  Now I mention it, a Fortran test for the BLAS compatibility is
probably worthwhile; would an optional make target for the Fortran BLAS
interface make sense in case you've built it and have Fortran?

The motivation is that in my experience checking you can trivially use
what you've just built is worthwhile more often than one might hope!

> (Notice that the testsuite is designed to test a cross section of
> numerical correctness of most operations in BLIS; it doesn't test the
> build system, per se.)

Right.  As a packager I might have a flag to run the full test after
significant changes, but I think it's too heavy to use for routine
builds.

Does that make sense?  Sorry I'm probably too close to this sort of
thing and maybe mindful of patronizing explanations, but happy to
explain as appropriate.

**Comment by fgvanzee** [comment]
@loveshack It sounds like we may be able to give you what you want by drastically pruning the parameter/operation space specified by the testsuite's input files. This would amount to using a special set of files that is tailored for a very short run as part of a hypothetical `make quicktest`. Does that sound sensible?

> Now I mention it, a Fortran test for the BLAS compatibility is probably
> worthwhile; would an optional make target for the Fortran BLAS interface
> make sense in case you've built it and have Fortran?

@loveshack Are you suggesting a testsuite feature that exercises the BLAS compatibility layer? We've had a few requests for this in the past, but unfortunately it can't be tested easily using the current testsuite framework. The better option would be to simply recycle whatever netlib has for the BLAS. I think the LAPACK testsuite exercises the BLAS API as well, and that testsuite is included in libflame. But I know that doesn't really help you here.

Another thing is that we (I?) have a sort of reflexive aversion to Fortran. As you point out, running such a Fortran testsuite would be optional. But we would still need to re-integrate Fortran (at least the use of Fortran compilers) into our build system--something I am hesitant to do. The testsuite could be rewritten in C, but that's a heavy lift.

**Comment by loveshack** [comment]
> @loveshack It sounds like we may be able to give you what you want by
> drastically pruning the parameter/operation space specified by the
> testsuite's input files. This would amount to using a special set of
> files that is tailored for a very short run as part of a hypothetical
> `make quicktest`. Does that sound sensible?

Yes, that's the idea if it's easy to do.

> @loveshack Are you suggesting a testsuite feature that exercises the
> BLAS compatibility layer?

Yes.

> We've had a few requests for this in the
> past, but unfortunately it can't be tested easily using the current
> testsuite framework. The better option would be to simply recycle
> whatever netlib has for the BLAS.

I added the netlib dblat3.f as a test to rpm packaging, and now need to
investigate why it's aborting...

> Another thing is that we (I?) have a sort of reflexive aversion to
> Fortran.

I wonder why for numerical work.  (I feel the same about C++.)  Fortran
codes of the sort Jeff knows form a large part of our workloads.

  ALGOL 60 is alive and well and living in FORTRAN 90.  -- Tony Hoare

> As you point out, running such a Fortran testsuite would be
> optional. But we would still need to re-integrate Fortran (at least
> the use of Fortran compilers) into our build system--something I am
> hesitant to do. The testsuite could be rewritten in C, but that's a
> heavy lift.

Oh, OK.  I thought it would just need a simple make rule which wouldn't
normally be run.  (Writing in C doesn't check that the Fortran interface
is right.)

**Comment by fgvanzee** [comment]
> I added the netlib dblat3.f as a test to rpm packaging, and now need to 
> investigate why it's aborting...

Be careful with your stack size limit (`ulimit -s`). I was unable to run the LAPACK testsuite using the default of 8MB. Switching to an unlimited stack size fixed the problem (which was a segfault on a *very* odd line of code).

> I wonder why for numerical work. (I feel the same about C++.) Fortran
> codes of the sort Jeff knows form a large part of our workloads.

Let me clarify that it's mainly Fortran-77 that bothers me. It's a perfectly fine language for some people, just not me. :) 

> Oh, OK. I thought it would just need a simple make rule which wouldn't normally
> be run. (Writing in C doesn't check that the Fortran interface is right.)

We intentionally removed all Fortran dependencies from libflame, and the BLIS project was originally developed Fortran-free. (We've worked with industry partners in the past for whom Fortran was a deal-breaker; they needed C-only code.) So no, definitely not as simple as adding a `make` rule. 

I suppose part of the problem with *truly* testing Fortran interfaces is that they partially depend on the compiler. I vaguely recall working with compilers many years ago that inserted not one, but two underscores after symbol names. BLIS would not work for users of those kinds of compilers. I've also worked with compilers that made all symbols uppercase. Again, BLIS would not play well with applications that were built by such a compiler. So there are definitely shortcomings in the BLIS implementation of the BLAS API layer, and those shortcomings are not exercised or tested.

What I meant by my comment was that we could assume that none of that weirdness is in play, and, under that assumption, test BLIS's BLAS API (routines like `dgemv_()`) by calling such routines from a C driver program. Or do you still disagree?

**Comment by fgvanzee** [comment]
@loveshack In light of [issue 177](https://github.com/flame/blis/issues/177), I may have had a change of heart. I think I can provide some basic infrastructure to run this netlib BLAS testsuite, **provided** the user has `gfortran` (or a different working Fortran compiler). I may also experiment with running those test drivers through `f2c` and seeing if the output works just as well. If I can get the drivers into C, then not only is Fortran not needed to compile the driver, but the drivers can be integrated into the existing BLIS build system and I give you a `make` target. :)

As always, thanks for your continued feedback.

**Comment by loveshack** [comment]
I agree about f77, and it's a pity there isn't a standard modern fortran
interface to blas/lapack.  (The one in MKL is proprietary.)

I don't understand the problem with having a make target using fortran
that isn't normally used, like mkl openblas ones, but no matter.

I used to be all too familiar with different f77 ABIs.  The double
underscore is used by the traditional unix ABI iff the fortran name
contains an underscore.  I don't recall which compilers upper-cased
names (XLF?) and I don't know much about current compatibility, but I'd
expect GNU/Linux compilers at least to have options for compatibility
with gfortran.

For what it's worth, if you want to use f2c for the BLAS tests, you'll
still need libf77 to handle i/o, at least, and the ABI isn't compatible
with the gfortran default in some ways I forget (other than double
underscores) which may or may not be relevant to BLAS.

**Comment by fgvanzee** [comment]
> I don't understand the problem with having a make target using fortran
> that isn't normally used, like mkl openblas ones, but no matter.

As I alluded to before, we've had partners in industry who have environments completely void of a Fortran compiler. I understand if that's difficult to imagine, especially for a user of Fortran and GNU software in general, but it's a situation we want to be able to handle.

> For what it's worth, if you want to use f2c for the BLAS tests, you'll
> still need libf77 to handle i/o, at least, and the ABI isn't compatible
> with the gfortran default in some ways I forget (other than double
> underscores) which may or may not be relevant to BLAS.

I plan to import the necessary source code from `f2c` into the test driver, providing I can get everything working, so the ABI won't be an issue. That probably sounds hackish, but as a general policy we like to keep BLIS's number of link-time dependencies to an absolute minimum. (Granted, it's not quite as important to us when dealing with optional test drivers.)

**Comment by fgvanzee** [comment]
@loveshack I'm making progress with converting the BLAS testsuite to C via `f2c`. I was able to convert, compile, and run a `dblat3.c` and the behavior and output seems identical to the Fortran version. I'll proceed with importing the rest of the testsuite files and integrating it into the BLIS build system.

**Comment by loveshack** [comment]
For what it's worth, see -ff2c at
https://gcc.gnu.org/onlinedocs/gcc-7.3.0/gfortran/Code-Gen-Options.html#Code-Gen-Options
for ABI differences between f2c and gfortran, which the BLIS interface
follows.  (BLAS has real and complex functions.)

**Comment by fgvanzee** [comment]
Thanks. Yes, I've been bitten by the differences in f2c vs. conventional calling conventions before. I'm taking care to un-f2c f2c'ed functions that return complex values so they are compatible with BLIS's BLAS API.

I'm almost done with the new BLAS testsuite. (I think everything is running now. But I'm going to use the results to continue to track down and fix the remaining test failures.)

**Comment by fgvanzee** [comment]
@loveshack I'm happy to announce that commit 664ec48 provides the integrated BLAS test suite, as promised. Simply `configure` and `make`, as before, and then run `make check`. This will run (1) a fast version of the BLIS test suite and a script that checks for BLIS testsuite errors, followed by (2) the new BLAS test suite (which is fast by default) and a script that checks for BLAS test errors. Granted, what constitutes "fast" for the BLIS test suite is subjective. For now, it uses a slightly modified version of `input.general` that only tests with problem sizes of 200 (instead of the previous default of 500). If this is still not fast enough for you, I can bump it down to something less than 200.

I've also edited the `.travis.yml` file so that Travis CI will run the BLAS tests with each commit.

Please try it out and let me know what you think. Thanks again for nudging me in this direction. (We've had requests for BLAS tests in the past.)

**Comment by devinamatthews** [comment]
@fgvanzee is it necessary (for a "quick sanity test") to test all of the transpose/storage variants as well? That would cut down the time a lot.

**Comment by fgvanzee** [comment]
@devinamatthews No, it's not strictly necessary, but I figure if I can get the runtime of `make check` for mainstream architectures down to 10s or so, then it's worth the added test coverage (and we're at around 10s on Haswell).

We could probably go down a rabbit hole debating what is high priority in such a quick test (e.g. larger problem sizes but fewer parameters/operations vs. smaller problem sizes and all parameters/operations). I'm open to being convinced that the sweet spot is elsewhere, though.

**Comment by loveshack** [comment]
You wrote: 

> @devinamatthews No, it's not strictly necessary, but I figure if I can
> get the runtime of `make check` for mainstream architectures down to
> 10s or so, then it's worth the added test coverage (and we're at
> around 10s on Haswell).

I've just timed make check at 4m42.929s on KNL with up-to-date dev
branch, so there seems to be something wrong unless it was highly
parallel on Haswell.

(That's not terrible if it was right, but it would likely be too time
consuming for, say, arm32 packages or anything that needs to be built on
an emulator.)

**Comment by fgvanzee** [comment]
@loveshack I should have been more precise. It's not the mainstream-ness of the architecture that matters, it's the kernel support in BLIS. All of the important kernels are written for Haswell. That's not the case yet for KNL, so it's definitely not surprising that running `make check` takes so long in that environment. (Reference kernels are slow.)

Would you mind editing the problem size in `testsuite/input.general.fast` and re-running (and re-timing) `make check`? Just change the following lines
```
200     # Problem size: first to test
200     # Problem size: maximum to test
```
to something like 100 or less. I'm thinking of adding a companion `testsuite/input.operations.fast` file too (rather than the "fast" test using the  `testsuite/input.operations` file, which defaults to full operation coverage). That way, if we come to some consensus that certain operations can be pruned from the "fast" test space, that can be done.

**Comment by devinamatthews** [comment]
@fgvanzee KNL is slow because it is a 1.1-1.3 GHz processor with terrible integer performance (the testsuite is slow even for `dgemm` which has an optimized kernel). As @loveshack points out, this is the case for a number of other architectures and even moreso when one has to use an emulator. I still think turning off the transpose and storage variants will help a lot, but N=100 is fine too (in addition?). That or just running the BLAS testuite/simple example program.

**Comment by fgvanzee** [comment]
@devinamatthews After further consideration, I agree with you that we can turn off transposition and conjugation in level-3 operations, as that functionality only exercises `packm`, which has been tested to death. And if anything in `packm` ever breaks, we'll know about it soon enough.

I'm about to commit an `input.operations.fast` companion file to `input.general.fast`, so we'll be able to prune down the set of things that gets tested.

**Comment by fgvanzee** [comment]
Okay, in the "fast" version of the testsuite, I've:
- disabled testing of the `trmm3` operation
- disabled all transposition and conjugation testing for all level-3 operations
- disabled testing of the 1m method
- reduced the problem size to 100
`make testblis-fast` (the most time-consuming part of `make check`) now finishes about 5-6 times faster than before on my Haswell system.

**Comment by loveshack** [comment]
You wrote: 

> @loveshack I should have been more precise. It's not the
> mainstream-ness of the architecture that matters, it's the kernel
> support in BLIS. All of the important kernels are written for
> Haswell. That's not the case yet for KNL, so it's definitely not
> surprising that running `make check` takes so long in that
> environment. (Reference kernels are slow.)

I guess I could do the experiments, but what's missing on KNL?  I
haven't checked what they do, but there seem to be more kernels for KNL
than Haswell.

There still seems to something wrong for me anyway.  When I tried make
check for an x86_64 build on 2.6GHz Haswell (serial), it took 76s,
c.f. 10.  (That was off Lustre, not a local filesystem, but it was only
10s sys.)

**Comment by loveshack** [comment]
> I still think turning off the transpose and
> storage variants will help a lot, but N=100 is fine too (in
> addition?). That or just running the BLAS testuite/simple example
> program.

Yes, I'll probably just keep the run of dblat3 for rpm packaging.  By
the way, I can post the current version of the spec file using snapshot
source if anyone's interested.

Not my call, of course, but I'd rather see knl and skx in the x86_64
collection (if that's worthwhile without whatever they're missing) than
variants of tests.

**Comment by fgvanzee** [comment]
> I guess I could do the experiments, but what's missing on KNL? I haven't checked what they do, but there seem to be more kernels for KNL than Haswell. There still seems to something wrong for me anyway. When I tried make check for an x86_64 build on 2.6GHz Haswell (serial), it took 76s, c.f. 10. (That was off Lustre, not a local filesystem, but it was only 10s sys.)

The best way to get a sense of how many kernels a configuration "has" is look at which kernels are actually registered. So for `knl`, you would look at `config/knl/bli_cntx_init_knl.c`. As you can see, only one computational kernel is registered: the `dgemm` microkernel. (The other two `knl` kernels are `packm` kernels, which have a **much** lower impact on runtime compared to reference kernels.)

If you look at `haswell`, by contrast, it has most of the important kernels registered. (This configuration borrows kernels from the `zen` kernel set, as they are virtually interchangeable for our purposes.)

> Not my call, of course, but I'd rather see knl and skx in the x86_64 collection (if that's worthwhile without whatever they're missing) than variants of tests.

Don't worry, it will happen, but I'm going to first get the `--with[out]-memkind` option in place.

**Comment by fgvanzee** [comment]
> Yes, I'll probably just keep the run of dblat3 for rpm packaging.

@loveshack Alternatively, you could run `make checkblas`. This will run only the BLAS test drivers.
