### ISSUE TITLE
format fix

### ISSUE THREAD

**Issue by loveshack** [flame/blis#184]
This avoids a format warning in 64-bit mode with current master.  I don't know if long is good enough on everything.

```
diff --git a/frame/compat/cblas/src/cblas_xerbla.c b/frame/compat/cblas/src/cbla
index 5d79080..b5332ad 100644
--- a/frame/compat/cblas/src/cblas_xerbla.c
+++ b/frame/compat/cblas/src/cblas_xerbla.c
@@ -61,7 +61,7 @@ void cblas_xerbla(f77_int info, const char *rout, const char *
       }
    }
    if (info)
-      fprintf(stderr, "Parameter %d to routine %s was incorrect\n", info, rout)
+      fprintf(stderr, "Parameter %jd to routine %s was incorrect\n", (intmax_t)
    vfprintf(stderr, form, argptr);
    va_end(argptr);
    if (info && !info) 
```

**Comment by fgvanzee** [comment]
@loveshack I don't receive this warning when I compile with `--enable-cblas`. Is there any other configuration option you are enabling when you observe the format warning you cite? I'd like to try to reproduce it.

**Comment by loveshack** [comment]
You wrote: 

> @loveshack I don't receive this warning when I compile with
> `--enable-cblas`. Is there any other configuration option you are
> enabling when you observe the format warning you cite? I'd like to try
> to reproduce it.

Using any vaguely recent gcc with -Wall should give the warning.  %d
can't be correct for -b 32 and -b 64 (where "info" is either int or
long).

Looking at the issue now, I realize the patch got truncated, but it just
uses %jd instead of %d and casts info to intmax_t.
