### ISSUE TITLE
Assembler checks needed

### ISSUE THREAD

**Issue by devinamatthews** [flame/blis#186]
Compiler version checking is necessary, but not sufficient, to blacklist configurations such as skx, knl, etc. You also have to make sure that the assembler is up to snuff. icc makes this impossible to do properly with inline assembly because it sometimes does and sometimes doesn't use its built-in assembler. So, the only way to do it is to generate short assembly files (e.g. here) and see if they assemble. For example, I doubt configure intel64 would work on macOS right now.

**Comment by jeffhammond** [comment]
`./configure intel` works on MacOS Sierra right now.  `make check` fails here:
```
Linking test_libblis.x against './lib/intel64/libblis.a -lm -lmemkind -lpthread'
ld: library not found for -lmemkind
```

The system linker on my laptop does not understand AVX-512:
```
$ gfortran-7 -march=skylake-avx512 -cpp -fopenmp nstream.f90
/var/folders/tz/3sxkhvt90632mzr6fxm1cd0h0000gp/T//cc9xzTET.s:869:2: error: instruction requires: AVX-512 ISA
        vpxord  %zmm0, %zmm0, %zmm0
        ^
/var/folders/tz/3sxkhvt90632mzr6fxm1cd0h0000gp/T//cc9xzTET.s:900:2: error: instruction requires: AVX-512 ISA
        vpxord  %zmm0, %zmm0, %zmm0
        ^
/var/folders/tz/3sxkhvt90632mzr6fxm1cd0h0000gp/T//cc9xzTET.s:906:2: error: instruction requires: AVX-512 ISA
        vpxord  %zmm0, %zmm0, %zmm0
        ^
/var/folders/tz/3sxkhvt90632mzr6fxm1cd0h0000gp/T//cc9xzTET.s:931:2: error: instruction requires: AVX-512 ISA
        vpxord  %zmm0, %zmm0, %zmm0
        ^
/var/folders/tz/3sxkhvt90632mzr6fxm1cd0h0000gp/T//cc9xzTET.s:1248:2: error: instruction requires: AVX-512 ISA
        vpxord  %zmm0, %zmm0, %zmm0
        ^
/var/folders/tz/3sxkhvt90632mzr6fxm1cd0h0000gp/T//cc9xzTET.s:1406:2: error: instruction requires: AVX-512 ISA
        vpxord  %zmm0, %zmm0, %zmm0
        ^
```

However, the Intel compiler is smart enough to work around this.
```
$ ifort -xCORE-AVX512 -qopt-zmm-usage=high -fpp -qopenmp nstream.f90
$ ./a.out 

Please verify that both the operating system and the processor support Intel(R) AVX512DQ, AVX512F, ADX, AVX512CD, AVX512BW and AVX512VL instructions.
```

Given that Apple is shipping work stations with AVX-512 support (Xeon W or Skylake X), I expect their toolchain to support AVX-512 soon, if not already (in High Sierra).

**Comment by fgvanzee** [comment]
@devinamatthews Do you have an example I can build off of vis-a-vis assembler checking? You referenced "(e.g. here)" which feels like maybe it wanted to be a link to something. :)

**Comment by fgvanzee** [comment]
Thanks Devin. Can you confirm my interpretation of how the assembler checks fit in with the overall blacklisting?

My best guess is that for any given configuration `fooconfig` that wants to use kernels that need instruction set `barset`, we check if the assembler can assemble instructions from `barset`; if the test fails, then we must blacklist `fooconfig`.

Did I get that right?

**Comment by devinamatthews** [comment]
Yes. I do it in TBLIS by just checking all instruction set extensions and disabling all configurations that use a given instruction set extensions when it is not supported.

**Comment by fgvanzee** [comment]
BTW, I didn't notice that the original comment you made directly on commit 786d15c had the link for "[here](https://github.com/devinamatthews/tblis/blob/1258e346b64f628a4c61851bb84956585c6b82e0/configure.ac#L305)", which didn't transfer during the opening of the issue. Mystery solved.

**Comment by fgvanzee** [comment]
Commit 088c474e now implements this feature. (Though further tweaks may be necessary.)

**Comment by fgvanzee** [comment]
And f56481e fixes the version-challengedness on OS X, as well as redundant blacklisting.

**Comment by noloader** [comment]
Sorry for digging up an old bug report. I came across this issue report when searching for our instance of the problem.

Also see LLVM Issue 39875, [Error: instruction requires: AVX-512 ISA when using -mavx512f](https://bugs.llvm.org/show_bug.cgi?id=39875). The short of it is, Clang 7.0 is needed to sidestep a problem with the Clang integrated assembler. The root cause is LLVM Issue 36202, [llvm-mc doesn't accept AVX512 instructions using %zmm16+](https://bugs.llvm.org/show_bug.cgi?id=36202).

**Comment by fgvanzee** [comment]
Thanks for reaching out, @noloader.

@devinamatthews, can you help me interpret what this means for BLIS's assembler handling?

**Comment by jeffhammond** [comment]
This is fixed in LLVM already. Is the point to blacklist 6.0?
-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by noloader** [comment]
@fgvanzee,

This code and compile error:

```
gfortran-7 -march=skylake-avx512 -cpp -fopenmp nstream.f90
/var/folders/tz/3sxkhvt90632mzr6fxm1cd0h0000gp/T//cc9xzTET.s:869:2: error: instruction requires: AVX-512 ISA
        vpxord  %zmm0, %zmm0, %zmm0
```

Looks a lot like the Clang bug. The [comment](https://github.com/flame/blis/issues/186#issuecomment-444303674) only serves to give you the heads up on the cause and the work around.

**Comment by devinamatthews** [comment]
@noloader I have had success on macOS using `-march=skylake-avx512 -Wa,-march=skylake-avx512`, but of course detecting failure and disabling AVX512 on macOS is also fine since there is no such machine (yet?). So far I have only needed to explicitly enable it for testing with Intel SDE.

**Comment by jeffhammond** [comment]
@devinamatthews 
[MacOS question on AVX-512 support](https://discussions.apple.com/thread/8256853+&cd=1&hl=en&ct=clnk&gl=us) ([cached](https://webcache.googleusercontent.com/search?q=cache:Symss6T883kJ:https://discussions.apple.com/thread/8256853+&cd=1&hl=en&ct=clnk&gl=us)) and the linked [answer](https://github.com/apple/darwin-xnu/blob/0a798f6738bc1db01281fc08ae024145e84df927/osfmk/i386/fpu.c#L176).
