### ISSUE TITLE
Track CFLAGS for reference kernels separately from those of optimized kernels

### ISSUE THREAD

**Issue by fgvanzee** [flame/blis#187]
Referencing this discussion on issue #183:

@jeffhammond So you're saying that we can compile reference kernel code with AVX2 on skx, no questions asked, and the outcome will always be better than with AVX512?

@fgvanzee Yeah, reference/unoptimized code should be compiled to AVX2, because that code is not going to achieve high enough SIMD utilization to overcome the AVX512 frequency drop. Note that this doesn't mean AVX-512 isn't useful - it is certainly useful in BLAS3*, but I assume you are not using reference code there.

**Comment by fgvanzee** [comment]
This has been addressed in commit bd02767.

@jeffhammond I set the reference kernel vectorization flags to AVX2 for `knl` as well as `skx` sub-configurations. I probably should have checked with you first before making that call, but I can always fix it if you think the step-down to AVX2 for `knl` is not appropriate.

**Comment by devinamatthews** [comment]
AVX2 is probably fine for KNL, unless the level 1/2 kernels are bounded by instruction bandwidth (unlikely).

**Comment by devinamatthews** [comment]
Note that `-march=knl` implies `-mavx512f`... maybe `-march=knl -mno-avx512f` (order might matter, icc might be different, etc.)?

**Comment by jeffhammond** [comment]
Using KNL flags also ensures the right uarch optimizations. AVX2 implies
Core/Xeon, which isn’t optimal for KNL. The KNL-AVX512 flags might work.
But ICC should use MIC-AVX512 flags.
-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by jeffhammond** [comment]
> Note that -march=knl implies -mavx512f... maybe -march=knl -mno-avx512f
> (order might matter, icc might be different, etc.)?
>

Some versions of ICC support these flags. The lack of universal support is
why I recommend MIC-AVX512 flags. KNL is tuned for ZMM usage...
-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by fgvanzee** [comment]
I just realized that I forgot to break out the setting of reference kernel vectorization flags (`CRVECFLAGS`) by compiler in bd02767. Will fix.

**Comment by fgvanzee** [comment]
As a separate question, does anyone know the behavior of including the following `gcc` flags in the following order:
```
-march-skylake-avx512 -mavx2
```
Is the net result the same as `-march-skylake-avx512`, or does the compiler start with all of the options implied by `-march=skylake-avx512` but then dial back the instruction set to AVX2? I hope it is the latter, but I wouldn't be surprised if they got interpreted differently.

**Comment by devinamatthews** [comment]
The latter.

**Comment by fgvanzee** [comment]
Great. Thanks Devin.

**Comment by devinamatthews** [comment]
But of course `-mavx2` is redundant in this case`.

**Comment by fgvanzee** [comment]
> But of course -mavx2 is redundant in this case`.

Wait, why? The whole point of my hypothetical was to ask how including `-mavx2` affects `-march-skylake-avx512` You seemed to indicate that the latter possibility was what would happen.

**Comment by devinamatthews** [comment]
s/latter/former/, your phrasing confused me.

**Comment by devinamatthews** [comment]
Basically `-march=<whatever> == -mtune=<whatever> -m<lots of stuff> -mno-<lots of other stuff>`, and you can tweak this with more `-m<this>` and `-mno-<that>` flags. AFAICT `-mno-x` overrides `-mx`.

**Comment by fgvanzee** [comment]
@devinamatthews Okay, that's what I was afraid of. Thanks.

**Comment by devinamatthews** [comment]
If you want to disable AVX512 on SKX, just use `-march=skylake`. They are basically the same chip apart from the cache and AVX512.

**Comment by fgvanzee** [comment]
That probably works fine in the case of disabling avx512 on skx, but as a general rule I should probably get in the habit of manually disabling instruction subsets. (For example, this trick would not work with KNL, correct? Since there is no non-512 analogue of KNL?)

**Comment by devinamatthews** [comment]
Correct.

**Comment by devinamatthews** [comment]
Yes. In the vast majority of cases (basically all x86_64) all you need is `-march`.

**Comment by devinamatthews** [comment]
`-xMIC-AVX512` won't work. What I think @jeffhammond was suggesting was that for KNL with icc you can leave it as-is (i.e. `-xCORE-AVX512`).

**Comment by fgvanzee** [comment]
@devinamatthews Thanks.

Here's what I have for knl (the setting of vectorization flags for reference kernels):
```
ifeq ($(CC_VENDOR),gcc)
CRVECFLAGS     := -march=knl -mno-avx512f -mno-avx512pf -mno-mavx512er -mno-mavx512cd
else
ifeq ($(CC_VENDOR),icc)
CRVECFLAGS     := -xMIC-AVX512
else
ifeq ($(CC_VENDOR),clang)
CRVECFLAGS     := -march=knl -mno-avx512f -mno-avx512pf -mno-mavx512er -mno-mavx512cd
else
```
And skx:
```
ifeq ($(CC_VENDOR),gcc)
CRVECFLAGS     := -march=skylake-avx512 -mno-avx512f -mno-mavx512vl -mno-mavx512bw -mno-mavx512dq -mno-mavx512cd
else
ifeq ($(CC_VENDOR),icc)
CRVECFLAGS     := -xCORE-AVX2
else
ifeq ($(CC_VENDOR),clang)
CRVECFLAGS     := -march=skylake-avx512 -mno-avx512f -mno-mavx512vl -mno-mavx512bw -mno-mavx512dq -mno-mavx512cd
else
```

**Comment by devinamatthews** [comment]
Nevermind, I was thinking that `-xMIC-AVX512` was KNC.

**Comment by devinamatthews** [comment]
I can't seem to find an equivalent of `-mno-avx...` for icc. You could use `-xCORE-AVX2` for Skylake.

**Comment by fgvanzee** [comment]
> You could use `-xCORE-AVX2` for Skylake.

Was that a suggestion or an affirmation? (I already am.)

**Comment by devinamatthews** [comment]
Sorry, reading comprehension fail. All looks good.

**Comment by fgvanzee** [comment]
@devinamatthews Thanks for your help.

**Comment by fgvanzee** [comment]
@devinamatthews lol, I had an extra `m` in the `-mno-` options. Oops.

**Comment by jeffhammond** [comment]
> I can't seem to find an equivalent of -mno-avx... for icc. You could use
> -xCORE-AVX2 for Skylake.
>
>
Intel 18 supports “-xCORE-AVX512 -qopt-zmm-usage=low” that should be better
but this hasn’t always been true in practice.
-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by fgvanzee** [comment]
@jeffhammond Good to know. Thanks Jeff.
