### ISSUE TITLE
Configure not taking compiler override through the options

### ISSUE THREAD

**Issue by dnparikh** [flame/blis#190]
$ ./configure CC=icc skx
configure: using 'gcc' compiler.
configure: found gcc version 5.4.0 (maj: 5, min: 4, rev: 0).
configure: checking for blacklisted configurations for gcc 5.4.0.
configure: warning: gcc 5.4.0 does not support 'skx'; adding to blacklist.
configure: configuration blacklist:
configure:   skx
configure: reading configuration registry...done.
configure: checking whether we need to update the version file.
configure: checking version file './version'.
configure: found '.git' directory; assuming git clone.
configure: executing: git describe --tags.
configure: got back 0.3.1-7-gca98214.
configure: truncating to 0.3.1-7.
configure: updating version file './version'.
configure: starting configuration of BLIS 0.3.1-7.
configure: configuring with official version string.
configure: manual configuration requested; configuring with 'skx'.
configure: checking configuration against contents of 'config_registry'.
configure: 'user-specified configuration '' is NOT registered!
configure: 
configure: *** Cannot continue with unregistered configuration ''. ***
configure:

**Comment by fgvanzee** [comment]
Thanks for the bug report. This should be fixed in 388f64d.
