### ISSUE TITLE
tests on x86_64 link against memkind when it's not present

### ISSUE THREAD

**Issue by loveshack** [flame/blis#191]
Running make check after configuring for x86_64 fails on a system without libmemkind because it's added to LDFLAGS in config/knl/make_defs.mk without an appropriate guard.

**Comment by fgvanzee** [comment]
@loveshack Thanks Dave. I saw that code recently but misread it as an `$ifeq ($(DEBUG_TYPE),sde)`, hence why I previously thought it was okay. I'll fix.

**Comment by fgvanzee** [comment]
@loveshack This should be fixed in 45fbe66.
