### ISSUE TITLE
Broken x86_64 build on Arch Linux

### ISSUE THREAD

**Issue by fgvanzee** [flame/blis#192]
@stefanhusmann is using a very recent version of gcc (on Arch Linux) and getting an error when compiling the knl `packm` kernels via the `x86_64` configuration family:
```
kernels/knl/1m/bli_packm_knl_asm_24x8.c: Assembler messages:
kernels/knl/1m/bli_packm_knl_asm_24x8.c:244: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:245: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:246: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:247: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:248: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:249: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:250: Error: missing `}' in `{% k1 } {z}'
...
```
His configure log is [here](https://github.com/flame/blis/files/1887253/buildlog.txt).

**Comment by devinamatthews** [comment]
c.f. the version of blis_avx512_macros.h [here](https://github.com/devinamatthews/tblis/blob/develop/src/configs/knl/bli_avx512_macros.h). Various spaces need to be removed.

**Comment by fgvanzee** [comment]
@stefanhusmann Please try 78a24e7d and let us know how it goes.

**Comment by stefanhusmann** [comment]
https://github.com/flame/blis/commit/78a24e7dada52a3582f8488795bd1a44993989d9
does not make a big difference. 

Compiling obj/x86_64/kernels/knl/1m/bli_packm_knl_asm_24x8.o ('knl' CFLAGS for kernels)
kernels/knl/1m/bli_packm_knl_asm_24x8.c: Assembler messages:
kernels/knl/1m/bli_packm_knl_asm_24x8.c:244: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:245: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:246: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:247: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:248: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:249: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:250: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:251: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:302: Error: missing `}' in `{% k1 }'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:558: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:559: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:560: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:561: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:562: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:563: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:564: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:565: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:566: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:567: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:568: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:569: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:570: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:571: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:572: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:573: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:574: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:575: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:576: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:577: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:578: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:579: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:580: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:581: Error: missing `}' in `{% k1 } {z}'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:698: Error: missing `}' in `{% k1 }'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:699: Error: missing `}' in `{% k2 }'
kernels/knl/1m/bli_packm_knl_asm_24x8.c:700: Error: missing `}' in `{% k3 }'

**Comment by fgvanzee** [comment]
@stefanhusmann I've spoken to @devinamatthews, and we can't account for where the spaces are coming from in the expressions such as `{% k1 }`. The most recent commits appear to fix this problem on our end.

Out of curiosity, what are your versions of `gcc` and `binutils` (`as`, `objdump`, etc.)?

**Comment by stefanhusmann** [comment]
I am sorry, it indeed works also for me now, after building from a fresh build directory tree. I missed to delete it before my first retry.

I you are still interested: I use the official Arch Linux packages of gcc (7.3.1+20180312) and binutils (2.29.1).

**Comment by fgvanzee** [comment]
@stefanhusmann Very glad your builds are working now. Thanks for the update.
