### ISSUE TITLE
rpm packaging available

### ISSUE THREAD

**Issue by loveshack** [flame/blis#193]
I noticed 0.3.2 is released, and I've built rpms of it for RHEL(-alike)/Fedora under https://copr.fedorainfracloud.org/coprs/loveshack/blis/

I don't know if it's appropriate to include the spec file (http://copr-dist-git.fedorainfracloud.org/cgit/loveshack/blis/blis.git/plain/blis.spec) in the distribution, but you're welcome. You might like to mention the repo, at least. I could try to get BLIS into Fedora/EPEL, but that's increasingly painful.

**Comment by fgvanzee** [comment]
@loveshack This is great, Dave. Thank you for all of the effort you put into this.

1. I would most definitely love to mention your repository. In fact, I would like to link your packages homepage [1] from the `README.md` so that they are visible via the front/landing page of https://github.com/flame/blis/ . I assume you don't object to this, but let me know if you have any issues.

2. I also think we should send out a message announcing the availability of these packages on the blis-devel mailing list [2]. I'm happy to make the announcement on your behalf, or you can make the announcement--either way is fine.

[1] https://copr.fedorainfracloud.org/coprs/loveshack/blis/
[2] https://groups.google.com/d/forum/blis-devel

**Comment by loveshack** [comment]
You wrote: 

> @loveshack This is great, Dave. Thank you for all of the effort you
> put into this.
>
> 1. I would most definitely love to mention your repository. In fact, I
> would like to link your packages homepage [1] from the `README.md` so
> that they are visible via the front/landing page of
> https://github.com/flame/blis/ . I assume you don't object to this,
> but let me know if you have any issues.

Sure; it's all public stuff "in the hope that it will be useful".
That's the appropriate URL.  (No guarantees of how it will be
maintained, of course, and it's unofficial, but the packaging should be
roughly OK to be reviewed for inclusion in Fedora.)  I should have said
comments welcome, and to see README.Fedora from the installed package or
embedded in the spec
<http://copr-dist-git.fedorainfracloud.org/cgit/loveshack/blis/blis.git/plain/blis.spec>,
if that's not obvious.  I guess it's only really worthwhile for avx512
systems, given the openblas packaging which covers more architectures.

> 2. I also think we should send out a message announcing the
> availability of these packages on the blis-devel mailing list [2].

I'm not subscribed to it -- feel free.

[I could probably contribute Debian packaging too, but I'm not a Debian
developer, I don't think there's a Debian equivalent of copr apart from
Ubuntu PPA, and I was confused by the linear algebra policy when I
looked.]

**Comment by fgvanzee** [comment]
@loveshack Could you point us to the confusing linear algebra policy? As someone with zero expertise in contributing binary packages, I find it strange that they would have a policy specific to LA. (Getting into Ubuntu would be a huge coup for us, but we understand if it doesn't make sense for you at the moment.)

I've added a link to your Copr to the BLIS homepage. Thanks again.

**Comment by loveshack** [comment]
You wrote: 

> @loveshack Could you point us to the confusing linear algebra policy?
> As someone with zero expertise in contributing binary packages, I find
> it strange that they would have a policy specific to LA.

My confusion is that I thought there actually was a clear policy on what
BLAS packaging should do, but the reference I made in
https://loveshack.fedorapeople.org/blas-subversion.html to
https://wiki.debian.org/DebianScience/LinearAlgebraLibraries doesn't
actually specify that.

The basic idea, as I understand it, is that anything providing a BLAS
interface should provide a shared library, libblas.so.3, which can be
interchanged with others at run rime via LD_LIBRARY_PATH or made default
on the system with update-alternatives (which is presumably what you
normally want on specific hardware, possibly node-dependent on a
heterogeneous cluster).  Then it doesn't matter how you build a dynamic
object against some BLAS, and you should be able to assume an optimal
one is used at run rime.  I've provided shim libraries in the blis rpm
to allow you to do the same thing, but using the alternatives mechanism
would need a "system-wide change" in Fedora/RHEL.

Does that make sense?

> (Getting into
> Ubuntu would be a huge coup for us, but we understand if it doesn't
> make sense for you at the moment.)

I don't have any route into Ubuntu, though I'd have thought it should
got via Debian.  I could attempt to get it into Fedora (specifically
EPEL for RHEL7, which I'd expect to make most use of it) as I am a
Fedora maintainer -- it's just relatively painful now.

[I should apologize that I worded the package README badly, saying BLIS
probably only is an advantage over openblas for avx512.  I was thinking
just in the context of BLAS, without the different interface BLIS has.
I'll clarify that.]

**Comment by fgvanzee** [comment]
Thanks for the policy discussion. Yes, that makes sense. No worries about Ubuntu. You raise a good point that RHEL probably targets our core audience better anyway.

And yes, if the user is interested in more than just BLAS APIs, BLIS does indeed provide added value over OpenBLAS. :)

**Comment by fgvanzee** [comment]
@loveshack I'm going to close this issue now that your packages are linked from the homepage (`README.md`). Many thanks.
