### ISSUE TITLE
Enable shared library build by default?

### ISSUE THREAD

**Issue by fgvanzee** [flame/blis#199]
Can you think of any reasons we *shouldn't* enable building shared libraries by default?

On a related topic, to support shared libraries on OS X, do I need to do anything aside from using the appropriate flag (`-dynamiclib`) and file suffix (`.dylib`)?

**Comment by devinamatthews** [comment]
No.

Re macOS, technically there are more things to tweak like the install name, but if it links and runs a test program then go with it.

**Comment by fgvanzee** [comment]
Thank Devin.

Commit 4b72a46 should take care of this now.
