### ISSUE TITLE
Better handling of shared libraries on OS X

### ISSUE THREAD

**Issue by fgvanzee** [flame/blis#200]
Changes:
- Use the `.dylib` suffix on OS X (instead of `.so`).
- Link with the `-dynamiclib` and `-install_name` options on OS X (instead of `-shared` and `-soname`).

I'll try to finish working on this tomorrow. (Thanks for the tips, @devinamatthews .)

**Comment by ararslan** [comment]
Note that this was previously reported in #153. :slightly_smiling_face:

**Comment by fgvanzee** [comment]
Apologies, @ararslan (and @gaming-hacker) and thank you kindly for pointing this out. (Sometimes I am bad about sifting through open issues.) I will cross-post to #153 until this is resolved.

**Comment by fgvanzee** [comment]
@ararslan This issue has been fixed (hopefully) by af1d847. Please let us know if you encounter any problems or find that it needs further attention.

**Comment by ararslan** [comment]
Looks good to me! Probably safe to close this and #153 now, I'd think.

**Comment by fgvanzee** [comment]
Great, thanks. Will do.

**Comment by gaming-hacker** [comment]
No worries, nice clean up.
