### ISSUE TITLE
Default compiler is misidentified on OpenBSD

### ISSUE THREAD

**Issue by ararslan** [flame/blis#201]
In the `configure` script, having GCC on the user's `PATH` takes precedence over Clang or `cc`. This ends up picking up OpenBSD's default GCC 4.2.1 installation, which is too old to build BLIS. GCC is actually no longer the default compiler on OpenBSD; `cc` now points to `clang` as of OpenBSD 6.2.

This poses a subtly different problem on FreeBSD, where Clang is the default compiler as of FreeBSD 11.0 and GCC is no longer installed by default. If someone installs GCC from the Ports Collection then reconfigures BLIS without specifying `CC=`, they will suddenly be using GCC instead of Clang.

It seems like the best course of action across all platforms would be to check `cc` _first_ rather than last, and fall back to looking for GCC or Clang if that fails.

**Comment by devinamatthews** [comment]
One possible problem is that using `cc` will pick up the system compiler on macOS (which is a problem for homebrew users who would prefer `gcc` or non-Apple `clang`) and on Linux (where a user-built or -loaded compiler will be skipped). I see three options:

1. Pick the "least bad" ordering and stick with it.
2. Use different ordering for different operating systems.
3. Detect all compilers and pick the "best" one.

**Comment by jeffhammond** [comment]
On Mac, BLIS is doing the right thing, because the system compiler is crippled (e.g. has no OpenMP).  For OpenBSD, we should prioritize `cc` over compilers `PATH`.

**Comment by fgvanzee** [comment]
Thanks for breaking it down for us, Devin. Also, thanks for your suggestion, Jeff.

I've never used OpenBSD, nor do I have access to a system with it installed. Can someone tell me if we can rely on `uname` to detect OpenBSD, and if so, what is the expected output of `uname -s`? Is it simply `OpenBSD`?

**Comment by ararslan** [comment]
Yes, `uname -s` is OpenBSD on OpenBSD.

**Comment by fgvanzee** [comment]
@ararslan Okay, give 55ebf24d a shot. The normal search list/order is now `gcc clang cc`, except on OpenBSD, where it is `cc gcc clang`. (And if `CC` is set, it is added to the beginning of the search list automatically.)

**Comment by ararslan** [comment]
Any chance it could be `cc clang gcc` (Clang before GCC) on both OpenBSD and FreeBSD?

**Comment by ararslan** [comment]
Looks like 55ebf24 fixes this on OpenBSD. Thanks!

**Comment by fgvanzee** [comment]
@ararslan Yes, I will change it to `cc clang gcc` for OpenBSD and FreeBSD.

**Comment by fgvanzee** [comment]
Okay, try 9dbce16.

**Comment by devinamatthews** [comment]
Is `cc` updated when a newer version of `clang` is installed (via ports?)? If *not*, then perhaps `clang gcc cc` would make the most sense on *BSD (or `gcc` last).
