### ISSUE TITLE
configs for which arch?

### ISSUE THREAD

**Issue by nschloe** [flame/blis#205]
In https://github.com/flame/blis/tree/master/config, one finds configs for different CPU architectures. It's not always entire clear when to use which config. For examples, there's `x86_64` _and_ `amd64` and `intel64`. What's the difference between them? A small clarifying `README.md` in each directory would help out.

**Comment by fgvanzee** [comment]
@nschloe The key to understanding the sub-configurations in the `config` directory begins with the configuration registry in `config_registry`, which is explained in detail by the rather long [ConfigurationHowTo](https://github.com/flame/blis/wiki/ConfigurationHowTo) wiki.

Even if you just peek inside `config_registry`, you'll probably get a better feeling for how configuration families work in BLIS. (Note that the `/<name>` notation means "make the kernel set associated with `<name>` available to this sub-configuration. So, for example, `haswell` actually uses some of the `zen` kernels.)

However, you make a good point that I could add a README file to that directory. I've added such a file in 20af119.

**Comment by nschloe** [comment]
Perfect, thank you.
