### ISSUE TITLE
include rpm spec file?

### ISSUE THREAD

**Issue by loveshack** [flame/blis#213]
Since there's now Debian packaging included in the repo, it might be appropriate to include the rpm packaging (spec file) too, from http://copr-dist-git.fedorainfracloud.org/cgit/loveshack/blis/blis.git/plain/blis.spec
That should now work on OpenSuSE, but I'm somewhat confused about versions of that, and realize I haven't submitted builds for the blis copr.

**Comment by loveshack** [comment]
I should have said that if I steel myself to trying to get the package into Fedora/EPEL, I'll have to remove support for SuSE (or any other rpm-based distro) from the spec file, so it would make sense to distribute a more general one. [I think that Fedora policy is unfortunate, but there it is.]

**Comment by devinamatthews** [comment]
Does that just mean we would just have two (or more) spec files or is it more restrictive than that?

**Comment by loveshack** [comment]
You wrote: 

> Does that just mean we would just have two (or more) spec files or is
> it more restrictive than that?

I'm not sure what you mean by more restrictive, but support for other
rpm-based distributions would have to be maintained separately from the
spec file for a package putatively in Fedora (sigh).  I don't know if
any rpm-based distribution other than SuSE is relevant, or if SuSE has a
similar policy, but if there were packages maintained in Fedora/EPEL and
SuSE, this would probably be moot.  I hope that's clear!

**Comment by fgvanzee** [comment]
@loveshack Yes, now that we have Debian/Ubuntu packaging in the BLIS distribution, you are welcome to add a directory for rpm-related files if you like. What are the conventions for naming/locating such directories? (For example, @nschloe explained to me that with Debian, it's expected that it be in a directory named `debian` at the top-level directory.)

**Comment by loveshack** [comment]
If you put blis.spec at the top level, you can build a binary or source
rpm directly from the distribution tarball (with rpmbuild -tb or
rpmbuild -ts respectively).  Some people put the spec in something like
an "rpm" subdir, but I don't think there's any reason to do that.

**Comment by fgvanzee** [comment]
@loveshack What would the `rpmbuild -tb` command look like if the `blis.spec` file were in an `rpm` directory? I'll be honest that I'd actually prefer to tuck it away to be consistent with the `debian` package files, and to give the reader/user a more descriptive cue as to what `blis.spec` relates to.

**Comment by loveshack** [comment]
You wrote: 

> @loveshack What would the `rpmbuild -tb` command look like if the
> `blis.spec` file were in an `rpm` directory?

As far as I know, there isn't one that will work.  You have to unpack
the tarball, copy the spec to ~/rpmbuild/SPECS, copy the tarball to
~/rpmbuild/SOURCES and run rpmbuild on the spec.

> I'll be honest that I'd
> actually prefer to tuck it away to be consistent with the `debian`
> package files, and to give the reader/user a more descriptive cue as
> to what `blis.spec` relates to.

Up to you, but I reckon it's consistent to put the build recipes (debian
directory and rpm spec file) at the same level.  If people don't
recognize a spec file, I doubt they'll know what to do with it.

**Comment by fgvanzee** [comment]
@loveshack Thanks for those details, Dave. One last idea: is there any flexibility on what we can name the spec file? Could we name it `blis-rpm.spec`? Or would that not make sense given naming conventions and/or requirements of `rpmbuild`?

**Comment by loveshack** [comment]
You wrote: 

> @loveshack Thanks for those details, Dave. One last idea: is there any
> flexibility on what we can name the spec file? Could we name it
> `blis-rpm.spec`? Or would that not make sense given naming conventions
> and/or requirements of `rpmbuild`?

You could in principle build blis-0...rpm from blis-rpm.spec (unlike a
dpkg from a "blis-dpkg" directory), but it would be frowned upon and
confusing.

I'm afraid I don't understand what problem you see with the
well-established mechanisms and conventions for packaging, but it isn't
a big problem, and I should probably just maintain the copr for now.

**Comment by fgvanzee** [comment]
My problem--to the extent that it is an actual problem--is limited to the fact that the purpose of the file is not intuitively obvious (unless you have experience building rpms). But I was never going to let that get in the way of accepting the file, provided all other possible alternatives were exhausted, which it seems that they are now. :)

Thanks for fielding my questions. You can submit a pull request when you're ready.

**Comment by devinamatthews** [comment]
@loveshack if you'd like to contribute an rpm spec file please open a PR. Any further discussion can happen there if it needs to.

**Comment by loveshack** [comment]
> @loveshack if you'd like to contribute an rpm spec file please open a
> PR. Any further discussion can happen there if it needs to.

If you want it, you can just take it from
https://copr-dist-git.fedorainfracloud.org/cgit/loveshack/blis/blis.git
though I've just realized it needs updating.  That's the production
Fedora one with additions for SuSE, which still doesn't seem to have a
package.
