### ISSUE TITLE
Piledriver dependent builds broken

### ISSUE THREAD

**Issue by qnerd0815** [flame/blis#217]
Hello everybody,

in 0.3.2 and master the build of piledriver dependent kernels
(excavator, steamroller) is broken.  

After the build process the library conains an undefined reference to
'bli_cntx_init_piledriver_ref'

This has been checked on Ubuntu 18.04 and Fedora 28.

Kind regards,

qnerd

**Comment by fgvanzee** [comment]
@qnerd0815 Could you be more specific about the "undefined reference" error you observe? Using the head of master (commit 96d2774) I did the following:
```
./configure piledriver
make
```
And observed no errors during the build or the dynamic link of the shared object.

**Comment by qnerd0815** [comment]
Not the piledriver target itselft, only the dependent targets.
Please try

```
./configure steamroller
make
make test
```

and you should see 
```
lib/steamroller/libblis.a(bli_cntx_init_steamroller.o): In function `bli_cntx_init_steamroller':
bli_cntx_init_steamroller.c:(.text+0x17): undefined reference to `bli_cntx_init_piledriver_ref'
```

Thank you for investigating this issue,


qnerd

**Comment by fgvanzee** [comment]
@qnerd0815 Yes, you're right. The `steamroller` and `excavator` subconfigurations were broken due to copy-paste bugs. Here is the appropriate fix:
```
--- a/config/excavator/bli_cntx_init_excavator.c
+++ b/config/excavator/bli_cntx_init_excavator.c
@@ -39,7 +39,7 @@ void bli_cntx_init_excavator( cntx_t* cntx )
        blksz_t blkszs[ BLIS_NUM_BLKSZS ];
 
        // Set default kernel blocksizes and functions.
-       bli_cntx_init_piledriver_ref( cntx );
+       bli_cntx_init_excavator_ref( cntx );
 
--- a/config/steamroller/bli_cntx_init_steamroller.c
+++ b/config/steamroller/bli_cntx_init_steamroller.c
@@ -39,7 +39,7 @@ void bli_cntx_init_steamroller( cntx_t* cntx )
        blksz_t blkszs[ BLIS_NUM_BLKSZS ];
 
        // Set default kernel blocksizes and functions.
-       bli_cntx_init_piledriver_ref( cntx );
+       bli_cntx_init_steamroller_ref( cntx );
```
I'm preparing to commit this change to `master`. Would you care to share your name so I can acknowledge you in our commit log? (If not, I will just reference you by your github handle, unless you would rather I not mention you.)

**Comment by fgvanzee** [comment]
@qnerd0815 You're very welcome. Thank you for taking the time to bring these bugs to our attention, and for your interest in BLIS.

I've committed 262a62e, which contains the modifications shown in the diff patch above.
