### ISSUE TITLE
Static linking and -dead_strip on OSX breaks inline asm kernels

### ISSUE THREAD

**Issue by kali** [flame/blis#220]
I found this issue while working on a Rust binding for BLIS, as a BLAS provider. Rust will eagerly link everything it can statically, and pass -dead_strip to OSX linker to remove unreachable code.

It turns out this breaks the haswell GEMM kernel, and possibly others.

testcase:
```
#include <stdio.h>
#include "include/blis/blis.h"

int main() {
    float a[] = { 1.0 };
    float b[] = { 1.0 };
    float c[] = { 0.0 };
    float one = 1.0;
    bli_sgemm(BLIS_NO_TRANSPOSE, BLIS_NO_TRANSPOSE, 1, 1, 1,
            &one, a, 1, 1, b, 1, 1,
            &one, c, 1, 1,
            NULL);
    printf("c: %f", *c);
}
```

```
% gcc tc.c -o tc -L lib -lblis && ./tc
c: 1.000000
% gcc -dead_strip tc.c -o tc -L lib -lblis && ./tc
c: 0.000000
K
```

blis is 0.3.2, compiled for haswell. As this is on OSX, gcc is actually clang, but as far as I can tell, we are dealing with a linker issue.

I was able to track the issue to the use of textual labels in the inline assembly used for zen kernels in bli_gemm_zen_asm_d6x8.c . I could not find definite spec about this, but it looks like the C compiler when dealing with inline assembly will resolve backward going jumps to a litteral directly, and insert symbols for forward jumps. I found out about that disassembling the kernels .o . As far as I can tell clang and gcc (a real gcc) behave the same.

When linking with dead_strip, OSX linker will find symbols that are not linked (as they are reached by natural flow of instructions or internal jumps only), think they are dead functions and kill them with they associated block of code, resulting in a kernel function gutted out of entire chunks of its code.

It looks like gnu ld is a bit smarter, and manages to find out (because the symbol name starts by L ? because it performs more analysis ?) that it should not remove these chunks of code.

Now. There are a few ways to fix that.
* not use dead_strip.
* fix apple linker (will take years)
* fix the inline assembly by using 1f and 2b like jumps.
* move the kernel to functions to be assembled by as

I was able to verify that option 3, rewriting the jumps in relative form, does fix the issue. As far as I can tell it is actually the only kind of jumps explicitelly supported by inline assembly, and again, both compilers families do the same thing. It also results in a bit cleaner object code as local jumps will be used instead of long jumps. It is really not difficult to do, and the readability of the kernel code can be maintained with comments. 

I am convinced that options 3 is the right way to go. I am prepared to start fixing some kernels, but it's not exactly fun to do, so I want your opinion first.

**Comment by devinamatthews** [comment]
Re the long jump issue, can you share the disassembly? Even on OSX I've only seen near jumps being generated (of course most of these have 32B displacements but that is unavoidable due to the code size).

As for 1f/2b jumps, we like to use descriptive label names because it makes writing and maintaining the kernels much easier. I *have* found out, though, that labels beginning with "L" seem to get treated as local, and so wouldn't trigger the dead code issue. I have no idea how standard this is but I've tested it on macOS and Linux.

**Comment by devinamatthews** [comment]
FYI I've also switched to a mini-macro-language for new kernels (e.g. the KNL and SKX kernels), so prefixing label names automatically with "L" is dead easy. The older kernels would only take a few minutes anyways, though.

**Comment by kali** [comment]
My mistake, they are near jump, not far jumps, but they are not resolved and registered as a relocatable address instead.

This is the beginning of _bli_sgemm_zen_asm_6x16 from libblis.a for instance.

```
_bli_sgemm_zen_asm_6x16:
0000000000000000        55      pushq   %rbp
0000000000000001        48 89 e5        movq    %rsp, %rbp
0000000000000004        41 57   pushq   %r15
0000000000000006        41 56   pushq   %r14
0000000000000008        41 55   pushq   %r13
000000000000000a        41 54   pushq   %r12
000000000000000c        53      pushq   %rbx
000000000000000d        48 89 75 a0     movq    %rsi, -0x60(%rbp)
0000000000000011        48 89 55 a8     movq    %rdx, -0x58(%rbp)
0000000000000015        48 89 4d b0     movq    %rcx, -0x50(%rbp)
0000000000000019        4c 89 45 b8     movq    %r8, -0x48(%rbp)
000000000000001d        4c 89 4d c0     movq    %r9, -0x40(%rbp)
0000000000000021        89 f8   movl    %edi, %eax
0000000000000023        c1 f8 1f        sarl    $0x1f, %eax
0000000000000026        c1 e8 1e        shrl    $0x1e, %eax
0000000000000029        01 f8   addl    %edi, %eax
000000000000002b        89 c1   movl    %eax, %ecx
000000000000002d        83 e1 fc        andl    $-0x4, %ecx
0000000000000030        c1 f8 02        sarl    $0x2, %eax
0000000000000033        48 98   cltq
0000000000000035        48 89 45 c8     movq    %rax, -0x38(%rbp)
0000000000000039        29 cf   subl    %ecx, %edi
000000000000003b        48 63 c7        movslq  %edi, %rax
000000000000003e        48 89 45 d0     movq    %rax, -0x30(%rbp)
0000000000000042        c5 fc 77        vzeroall
0000000000000045        48 8b 45 a8     movq    -0x58(%rbp), %rax
0000000000000049        48 8b 5d b0     movq    -0x50(%rbp), %rbx
000000000000004d        48 81 c3 80 00 00 00    addq    $0x80, %rbx
0000000000000054        c5 fc 28 43 80  vmovaps -0x80(%rbx), %ymm0
0000000000000059        c5 fc 28 4b a0  vmovaps -0x60(%rbx), %ymm1
000000000000005e        48 8b 4d c0     movq    -0x40(%rbp), %rcx
0000000000000062        48 8b 7d 10     movq    0x10(%rbp), %rdi
0000000000000066        48 8d 3c bd 00 00 00 00         leaq    (,%rdi,4), %rdi
000000000000006e        4c 8d 2c 7f     leaq    (%rdi,%rdi,2), %r13
0000000000000072        4a 8d 14 29     leaq    (%rcx,%r13), %rdx
0000000000000076        0f 18 49 38     prefetcht0      0x38(%rcx)
000000000000007a        0f 18 4c 39 38  prefetcht0      0x38(%rcx,%rdi)
000000000000007f        0f 18 4c 79 38  prefetcht0      0x38(%rcx,%rdi,2)
0000000000000084        0f 18 4a 38     prefetcht0      0x38(%rdx)
0000000000000088        0f 18 4c 3a 38  prefetcht0      0x38(%rdx,%rdi)
000000000000008d        0f 18 4c 7a 38  prefetcht0      0x38(%rdx,%rdi,2)
0000000000000092        48 8b 75 c8     movq    -0x38(%rbp), %rsi
0000000000000096        48 85 f6        testq   %rsi, %rsi
0000000000000099        0f 84 00 00 00 00       je      0x9f
.SLOOPKITER:
000000000000009f        0f 18 88 00 01 00 00    prefetcht0      0x100(%rax)
00000000000000a6        c4 e2 7d 18 10  vbroadcastss    (%rax), %ymm2
00000000000000ab        c4 e2 7d 18 58 04       vbroadcastss    0x4(%rax), %ymm3
00000000000000b1        c4 e2 6d b8 e0  vfmadd231ps     %ymm0, %ymm2, %ymm4
00000000000000b6        c4 e2 6d b8 e9  vfmadd231ps     %ymm1, %ymm2, %ymm5
00000000000000bb        c4 e2 65 b8 f0  vfmadd231ps     %ymm0, %ymm3, %ymm6
00000000000000c0        c4 e2 65 b8 f9  vfmadd231ps     %ymm1, %ymm3, %ymm7
00000000000000c5        c4 e2 7d 18 50 08       vbroadcastss    0x8(%rax), %ymm2
```

at 0x0099, the address is for SCONSIDKLEFT is left for the linker to compute.

otool -r shows it in the relocation table...

```
000000000000009b X86_64_RELOC_BRANCH .SCONSIDKLEFT
```

For comparison, this is the assembly in the final binary:

```
_bli_sgemm_zen_asm_6x16:
0000000100006180        55      pushq   %rbp
0000000100006181        48 89 e5        movq    %rsp, %rbp
0000000100006184        41 57   pushq   %r15
0000000100006186        41 56   pushq   %r14
0000000100006188        41 55   pushq   %r13
000000010000618a        41 54   pushq   %r12
000000010000618c        53      pushq   %rbx
000000010000618d        48 89 75 a0     movq    %rsi, -0x60(%rbp)
0000000100006191        48 89 55 a8     movq    %rdx, -0x58(%rbp)
0000000100006195        48 89 4d b0     movq    %rcx, -0x50(%rbp)
0000000100006199        4c 89 45 b8     movq    %r8, -0x48(%rbp)
000000010000619d        4c 89 4d c0     movq    %r9, -0x40(%rbp)
00000001000061a1        89 f8   movl    %edi, %eax
00000001000061a3        c1 f8 1f        sarl    $0x1f, %eax
00000001000061a6        c1 e8 1e        shrl    $0x1e, %eax
00000001000061a9        01 f8   addl    %edi, %eax
00000001000061ab        89 c1   movl    %eax, %ecx
00000001000061ad        83 e1 fc        andl    $-0x4, %ecx
00000001000061b0        c1 f8 02        sarl    $0x2, %eax
00000001000061b3        48 98   cltq
00000001000061b5        48 89 45 c8     movq    %rax, -0x38(%rbp)
00000001000061b9        29 cf   subl    %ecx, %edi
00000001000061bb        48 63 c7        movslq  %edi, %rax
00000001000061be        48 89 45 d0     movq    %rax, -0x30(%rbp)
00000001000061c2        c5 fc 77        vzeroall
00000001000061c5        48 8b 45 a8     movq    -0x58(%rbp), %rax
00000001000061c9        48 8b 5d b0     movq    -0x50(%rbp), %rbx
00000001000061cd        48 81 c3 80 00 00 00    addq    $0x80, %rbx
00000001000061d4        c5 fc 28 43 80  vmovaps -0x80(%rbx), %ymm0
00000001000061d9        c5 fc 28 4b a0  vmovaps -0x60(%rbx), %ymm1
00000001000061de        48 8b 4d c0     movq    -0x40(%rbp), %rcx
00000001000061e2        48 8b 7d 10     movq    0x10(%rbp), %rdi
00000001000061e6        48 8d 3c bd 00 00 00 00         leaq    (,%rdi,4), %rdi
00000001000061ee        4c 8d 2c 7f     leaq    (%rdi,%rdi,2), %r13
00000001000061f2        4a 8d 14 29     leaq    (%rcx,%r13), %rdx
00000001000061f6        0f 18 49 38     prefetcht0      0x38(%rcx)
00000001000061fa        0f 18 4c 39 38  prefetcht0      0x38(%rcx,%rdi)
00000001000061ff        0f 18 4c 79 38  prefetcht0      0x38(%rcx,%rdi,2)
0000000100006204        0f 18 4a 38     prefetcht0      0x38(%rdx)
0000000100006208        0f 18 4c 3a 38  prefetcht0      0x38(%rdx,%rdi)
000000010000620d        0f 18 4c 7a 38  prefetcht0      0x38(%rdx,%rdi,2)
0000000100006212        48 8b 75 c8     movq    -0x38(%rbp), %rsi
0000000100006216        48 85 f6        testq   %rsi, %rsi
0000000100006219        0f 84 08 00 00 00       je      0x100006227
000000010000621f        90      nop
0000000100006220        90      nop
0000000100006221        90      nop
0000000100006222        90      nop
0000000100006223        90      nop
0000000100006224        90      nop
0000000100006225        90      nop
0000000100006226        90      nop
.SCONSIDKLEFT:
0000000100006227        48 8b 75 d0     movq    -0x30(%rbp), %rsi
000000010000622b        48 85 f6        testq   %rsi, %rsi
000000010000622e        0f 84 0d 00 00 00       je      0x100006241
```

The main loop is just gone :)

I am not sure if prefixing by "L" will be enough. I have struggle with this issue for a while and I think I tried that already. I can try again though. 

I also wonder if duplication in these branch symbol between the various kernels may not be a source of confusion for the linker actually. I am not sure if the "scoping" rules of local symbols are the same across compilers, and we have 4 SCONSIDKLEFT symbols laying around, so it may play a role too.

**Comment by kali** [comment]
The end of the main loop in libblis.a, if it helps...

```
0000000000000249        48 83 c0 60     addq    $0x60, %rax
000000000000024d        48 81 c3 00 01 00 00    addq    $0x100, %rbx
0000000000000254        c5 fc 28 43 80  vmovaps -0x80(%rbx), %ymm0
0000000000000259        c5 fc 28 4b a0  vmovaps -0x60(%rbx), %ymm1
000000000000025e        48 ff ce        decq    %rsi
0000000000000261        0f 85 38 fe ff ff       jne     0x9f
.SCONSIDKLEFT:
0000000000000267        48 8b 75 d0     movq    -0x30(%rbp), %rsi
000000000000026b        48 85 f6        testq   %rsi, %rsi
000000000000026e        0f 84 00 00 00 00       je      0x274
```

**Comment by kali** [comment]
So, it appears that the convention for mach-o local symbols is "L" prefixed, without the leading dot. Replacing the dots by L makes the kernel work again. But I'm not sure how we can fix this while preserving compatibility with ELF. Unless we switch to macros as you did for the newest, that is.

**Comment by devinamatthews** [comment]
Yes indeed it seems the prefix is `.L` for ELF. I had made an effort at one point to port everything over to the macro language, maybe now is the time to finish that.

One way to address the multiple symbol problem as well is to use the `%=` identifier which gives a unique identified per asm block. Can also be automated.

**Comment by devinamatthews** [comment]
@fgvanzee about the macros of course you could make them lowercase (or have both). I would *not* pull them into blis.h though, because they are not prefixed with `bli_` and it would be super annoying to do so.

**Comment by devinamatthews** [comment]
The other benefit of the macro approach is that in theory you can support Intel/Microsoft-style asm blocks, which would open up Windows beyond WSL.

**Comment by fgvanzee** [comment]
> I would not pull them into blis.h though, because they are not prefixed with bli_ and it would be super annoying to do so.

Agreed.

> The other benefit of the macro approach is that in theory you can support Intel/Microsoft-style asm blocks, which would open up Windows beyond WSL.

Understood. This will likely make some people out there very happy (though I am not among them).

**Comment by devinamatthews** [comment]
@kali can you check that moving to the assembly macros with `L` or `.L` prefixes fixes your issue with Rust?

**Comment by kali** [comment]
@devinamatthews Yes, it does :) Thanks :)
