### ISSUE TITLE
Undefined references while linking

### ISSUE THREAD

**Issue by smavros** [flame/blis#232]
Hello,

Following the _Linking against BLIS_ section I am trying to compile a small example with BLIS but I am getting this linker error
```
main.o: In function `bli_thread_obroadcast':
main.c:(.text+0x48a7): undefined reference to `bli_thrcomm_bcast'
main.o: In function `bli_thread_obarrier':
main.c:(.text+0x48cf): undefined reference to `bli_thrcomm_barrier'
collect2: error: ld returned 1 exit status
make: *** [Makefile:16: main.x] Error 1
```

My configure options are ```--enable-cblas --enable-threading=openmp auto``` and my setup is
```
configure: detected Linux kernel version 4.17.3-100.fc27.x86_64.
configure: found gcc version 7 (maj: 7, min: 7, rev: 7).
configure: found assembler ('as') version 2.29 (maj: 2, min: 29, rev: ).
```
with kernels ```haswell``` and ```zen```.

I am using the latest version of _master_ bf10d8624e7b5902c9d9189c7c93f318b8e1b9a5

Any ideas on how I can resolve that issue would be helpful.

**Comment by smavros** [comment]
I resolved the issue. The problem was due to wrong order of blis linking in my Makefile.

**Comment by fgvanzee** [comment]
@smavros I was about to sit down and look into this, but I'm glad you were able to figure out your problem. Thanks for your interest in BLIS.

**Comment by fgvanzee** [comment]
@smavros Actually, you brought my attention to the fact that the example `Makefile` in `docs/BuildSystem.md` is slightly out-of-date. Specifically, I need to add `-lpthread` since libpthread is now always required (because we need `pthread_once()`), even for sequential or OpenMP users.

**Comment by smavros** [comment]
@fgvanzee You are right. I was including ```<omp.h>``` in my source and I was compiling with ```-fopenmp``` so the problem didn't show up. Without those I am getting ```undefined reference to `pthread_once'```.
