### ISSUE TITLE
configure -p fails

### ISSUE THREAD

**Issue by loveshack** [flame/blis#239]
While configure's --prefix option works, -p now doesn't (seen in the 0.4.0 release, but looks the same in git). It seems the "p" case should set install_prefix_user, not install_prefix, but I just changed the rpm build to use --prefix before reading the script.

**Comment by fgvanzee** [comment]
Thanks for this report, Dave. You were correct in your diagnosis. It should be fixed now in 65c9096.

**Comment by fgvanzee** [comment]
@loveshack Closing this issue on assumption that this has been fixed. Let us know if we need to reopen.
