### ISSUE TITLE
Shared library versions of BLIS?

### ISSUE THREAD

**Issue by poulson** [flame/blis#24]
Is there a simple means of modifying BLIS to build a shared library instead of a static library? It seems to be missing from the `configure` script.

**Comment by fgvanzee** [comment]
It's not accessible via the configure script itself, but it is supported. Take a look at the `make_defs.mk` file in the configuration of interest:
```
BLIS_ENABLE_STATIC_BUILD        := yes
BLIS_ENABLE_DYNAMIC_BUILD       := no
```

**Comment by poulson** [comment]
Thanks Field; I grep'd for "shared" but did not try "dynamic". But I wouldn't necessarily close this yet, as the current approach seems to require manual editing of files and would prevent the usage of BLIS from other projects (i.e., Elemental) via CMake's ``ExternalProject_Add`` unless I add a patch script when attempting to build a shared library:
https://github.com/elemental/Elemental/blob/96f9b5984f93881db97b3cea2e27a2c9244d140c/external/cmake/blis.cmake

**Comment by fgvanzee** [comment]
That's fine. We can leave it open until the functionality is satisfactory.

**Comment by devinamatthews** [comment]
PR #54 adds support for --enable-shared in configure, so this could be closed now.
