### ISSUE TITLE
Support Octave?

### ISSUE THREAD

**Issue by jeffhammond** [flame/blis#241]
Consistent with the engagements with Julia and Numpy, perhaps it is worth validating BLIS works as desired in Octave (https://octave.org/doc/v4.0.3/External-Packages.html).

**Comment by fgvanzee** [comment]
Just to be clear, I assume you are referring to using BLIS as a drop-in replacement for whatever BLAS back-end is used for Octave, and **not** referring to the ability of Octave to correctly parse the output of BLIS's various test drivers.

**Comment by rvdg** [comment]
What we have done in the past is to wait for someone from that universe to take the initiative…

**Comment by jeffhammond** [comment]
This issue was inspired by https://twitter.com/owainkenway/status/1032986589079588865...

**Comment by fgvanzee** [comment]
@jeffhammond Could you follow-up tweet to Kenway and tell him that BLIS just merged some thread safety changes that may make a big difference for his purposes?

**Comment by owainkenwayucl** [comment]
Cheers, I'll take a look.

**Comment by fgvanzee** [comment]
@owainkenwayucl Please let us know if you have any questions.

**Comment by fgvanzee** [comment]
@owainkenwayucl Just following up. Were you able to look at BLIS? Please let us know (open a new issue, or comment here) if you run into any trouble. We're happy to try to help.

**Comment by cdluminate** [comment]
FYI: https://wiki.debian.org/DebianScience/LinearAlgebraLibraries

Debian family features an "update-alternatives" mechanism which allows you to switch BLAS/LAPACK backend without recompiling packages... And I've already added such support for Debian's BLIS package.

```
libblas.so.3-x86_64-linux-gnu
[ ] auto                                               
[ ] 35 /usr/lib/x86_64-linux-gnu/atlas/libblas.so.3    
[ ] 10 /usr/lib/x86_64-linux-gnu/blas/libblas.so.3     
[ ] 37 /usr/lib/x86_64-linux-gnu/libblis.so.1          <----
[*] 1 /usr/lib/x86_64-linux-gnu/libmkl_rt.so           
[ ] 100 /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
```

So anyone could test BLIS as a drop-in BLAS implementation against octave, numpy, etc ... without recompiling anything. Although I  manually set my default as MKL.

**Comment by owainkenwayucl** [comment]
Sorry, I haven't had a chance to look at this yet (we're in the middle of a procurement so it's chaos here).  It might be better to close this and I'll take a look when I get a chance and re-open if I run into any issues?

**Comment by fgvanzee** [comment]
We appreciate your "issue etiquette," Owain, and understand the delay. But it's up to you. We don't mind leaving the issue open, especially given that you've touched base with us.

**Comment by fgvanzee** [comment]
@cdluminate A few quick questions about the way priorities work in Debian:
```
libblas.so.3-x86_64-linux-gnu
[ ] auto                                               
[ ] 35 /usr/lib/x86_64-linux-gnu/atlas/libblas.so.3    
[ ] 10 /usr/lib/x86_64-linux-gnu/blas/libblas.so.3     
[ ] 37 /usr/lib/x86_64-linux-gnu/libblis.so.1
[*] 1 /usr/lib/x86_64-linux-gnu/libmkl_rt.so           
[ ] 100 /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
```
1. Are the priorities set by the Debian maintainers (such as you or Nico)? Or do they default to something and then the user changes them? (I think it is a static property set by the DMs, but I wasn't sure.) 
2. I'm also trying to get a sense for how the priority is used. Does it kick in when, for example, you have some subset of the total BLAS alternatives universe installed? Whatever is highest is what applications link against?
3. Assuming lower numbers are higher priority, I'm a little surprised that ATLAS has a higher priority than OpenBLAS. Although they are a "competitor" to BLIS, I will stick up for them here: In our many years of experience, OpenBLAS consistently yielded higher performance than ATLAS, to the point where we stopped comparing against ATLAS altogether. (Perhaps I will set up some experiments in the future just to re-confirm this.)
4. By similar logic, I also feel that BLIS should receive higher priority than ATLAS, but I'm comfortable letting BLIS prove itself to you over time, if you like. :)

**Comment by cdluminate** [comment]
> @cdluminate A few quick questions about the way priorities work in Debian:
> 
> ```
> libblas.so.3-x86_64-linux-gnu
> [ ] auto                                               
> [ ] 35 /usr/lib/x86_64-linux-gnu/atlas/libblas.so.3    
> [ ] 10 /usr/lib/x86_64-linux-gnu/blas/libblas.so.3     
> [ ] 37 /usr/lib/x86_64-linux-gnu/libblis.so.1
> [*] 1 /usr/lib/x86_64-linux-gnu/libmkl_rt.so           
> [ ] 100 /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
> ```
> 1. Are the priorities set by the Debian maintainers (such as you or Nico)? Or do they default to something and then the user changes them? (I think it is a static property set by the DMs, but I wasn't sure.)

These integers are manually set by package maintainers. For important libraries the priority number is discussed in mailing list.

> 2. I'm also trying to get a sense for how the priority is used. Does it kick in when, for example, you have some subset of the total BLAS alternatives universe installed? Whatever is highest is what applications link against?

All these libraries provides the libblas.so.3 symlink. If you choose MKL, then the symlink /usr/lib/x86_64-linux-gnu/libblas.so.3 point at libmkl-rt. Such, ELFs linked against libblas.so.3 can take advantage from this mechanism. By default, packages are built in clean chroots against the standard BLAS i.e. netlib, and depend on netlib during installation. And if user installed packages and openblas, these packages will automatically turn to use openblas.

> 3. Assuming lower numbers are higher priority, I'm a little surprised that ATLAS has a higher priority than OpenBLAS. Although they are a "competitor" to BLIS, I will stick up for them here: In our many years of experience, OpenBLAS consistently yielded higher performance than ATLAS, to the point where we stopped comparing against ATLAS altogether. (Perhaps I will set up some experiments in the future just to re-confirm this.)

You are mislead by the singular point MKL, whose priority has been set to 1. Actually 1 is the lowest priority, and we set this due to legal reasons. For example GPL licenses of other software. Debian cannot make user to use non-free or link against non-free libs by default unless the user explicitly requires so. Priority 1 means "require manual operation to enable" instead of "this library is slow". 
Then MKL became an singular point.

> 4. By similar logic, I also feel that BLIS should receive higher priority than ATLAS, but I'm comfortable letting BLIS prove itself to you over time, if you like. :)

BLIS has the second highest priority, while the higghest is currently openblas.

BLAS is a widely used by even software outside of the scientific computing fields, directly or indirectly. So I dont expect every user know xxx_num_threads or even BLAS itself. In order to deliver the best performance, the highest priority is set as openblas, which leverages more than 1 threads by default without doing anything. This is why I asked #292

**Comment by cdluminate** [comment]
So if my BLAS alternatives are configured in auto mode, openblas will be used. However, I manually overriden the default to MKL whose priority is even lower than netlib.

**Comment by cdluminate** [comment]
> @cdluminate Thanks for your explanations. I understand your decision to currently prioritize OpenBLAS above BLIS.
> 
> Just to make sure I understand the priority system: Hypothetically, suppose a user installed all of the libraries listed in the previous example _except_ OpenBLAS, which he/she did not install. Then the highest priority installed alternative would be BLIS, and applications would link to BLIS. Am I correct?

Correct, the "auto" mode automatically picks the one with highest (maximum) priority. If a user install all tbe BLASes at the same time except for OpenBLAS, BLIS would become the default because it has the highest priority on user's system.

**Comment by fgvanzee** [comment]
Got it. Thanks!

**Comment by devinamatthews** [comment]
Closing until further input.
