### ISSUE TITLE
Testsuite broken due to redundant pthread_barrier

### ISSUE THREAD

**Issue by fgvanzee** [flame/blis#249]
The testsuite is broken in Linux (and probably elsewhere) due to the testsuite's local pthread barrier definition (added during #243 #244) being activated even though the environment (apparently) already supports pthread barriers.
```
$ ./configure auto; make
$ cd testsuite
$ make
Compiling obj/test_addm.o
In file included from src/test_libblis.h:58:0,
                 from src/test_addm.c:37:
src/pthread_barrier.h:9:13: error: conflicting types for ‘pthread_barrierattr_t’
 typedef int pthread_barrierattr_t;
             ^
compilation terminated due to -Wfatal-errors.
Makefile:145: recipe for target 'obj/test_addm.o' failed
make: *** [obj/test_addm.o] Error 1
```
This is almost surely due to the cpp guard:
```c
#if !defined(_POSIX_BARRIERS) || (_POSIX_BARRIERS < 0)
#include "pthread_barrier.h"
#endif
```
not working properly. I tried replacing it with:
```c
#if !defined(_POSIX_BARRIERS) || (_POSIX_BARRIERS != 200809L)
```
but to no avail. (This change was made in tandem with the redundant guard in `src/pthread_barrier.h`.)

@kali @devinamatthews Any ideas?

**Comment by devinamatthews** [comment]
For expediency's sake, I would go back to using `__APPLE__`.

**Comment by fgvanzee** [comment]
> For expediency's sake, I would go back to using `__APPLE__`.

No objection here.

**Comment by fgvanzee** [comment]
Also: how the hell did this not get caught by Travis?

**Comment by kali** [comment]
LOL

**Comment by kali** [comment]
@fgvanzee could it be a distro thing ? what are you using ?

**Comment by kali** [comment]
@fgvanzee The _POSIX_BARRIER is defined by unistd.h. Is there any way you could get to the test without including unistd.h before ?

**Comment by fgvanzee** [comment]
@kali I was mucking around with other things when this happened. Let me make sure this wasn't all my own damn fault.

**Comment by fgvanzee** [comment]
Yep, false alarm. I removed `#include "unistd.h"` because I thought it was only needed for something else that I was moving.
