### ISSUE TITLE
Please remove the debian directory

### ISSUE THREAD

**Issue by cdluminate** [flame/blis#257]
Superseded by https://salsa.debian.org/science-team/blis

**Comment by fgvanzee** [comment]
@cdluminate I can remove it. Or I can move it out of the way into `build/old`.
@nschloe Any preference/comment on this matter?

**Comment by nschloe** [comment]
> Any preference/comment on this matter?

Drop it.

**Comment by fgvanzee** [comment]
@cdluminate @nschloe The `debian` directory has been removed in `master` as of 5fdddf6.
