### ISSUE TITLE
Undefined references to ``GOMP_parallel``

### ISSUE THREAD

**Issue by poulson** [flame/blis#26]
When I try to test for BLIS's support for dgemm_, I see the following link error, which does not seem to be covered by your build system wiki:

"""
/usr/bin/gcc-4.9   -DCHECK_FUNCTION_EXISTS=dgemm_    CMakeFiles/cmTryCompileExec3961259244.dir/CheckFunctionExists.c.o  -o cmTryCompileExec3961259244 -rdynamic /home/poulson/Install/lib/libblis.a -lpthread -lm
/home/poulson/Install/lib/libblis.a(bli_init.o): In function `bli_init':
bli_init.c:(.text+0xb4): undefined reference to`GOMP_critical_name_start'
bli_init.c:(.text+0xc6): undefined reference to `GOMP_critical_name_end'
/home/poulson/Install/lib/libblis.a(bli_init.o): In function`bli_finalize':
bli_init.c:(.text+0x1d0): undefined reference to `GOMP_critical_name_start'
bli_init.c:(.text+0x1e2): undefined reference to`GOMP_critical_name_end'
/home/poulson/Install/lib/libblis.a(bli_mem.o): In function `bli_mem_acquire_m':
bli_mem.c:(.text+0x77): undefined reference to`GOMP_critical_name_start'
bli_mem.c:(.text+0x8f): undefined reference to `GOMP_critical_name_end'
/home/poulson/Install/lib/libblis.a(bli_mem.o): In function`bli_mem_release':
bli_mem.c:(.text+0xfa): undefined reference to `GOMP_critical_name_start'
bli_mem.c:(.text+0x112): undefined reference to`GOMP_critical_name_end'
/home/poulson/Install/lib/libblis.a(bli_threading_omp.o): In function `bli_level3_thread_decorator._omp_fn.0':
bli_threading_omp.c:(.text+0x5): undefined reference to`omp_get_thread_num'
/home/poulson/Install/lib/libblis.a(bli_threading_omp.o): In function `bli_level3_thread_decorator':
bli_threading_omp.c:(.text+0x99): undefined reference to`GOMP_parallel'
collect2: error: ld returned 1 exit status
"""

**Comment by fgvanzee** [comment]
Are you linking with `-fopenmp`?

**Comment by poulson** [comment]
Nope, should I? (https://code.google.com/p/blis/wiki/BuildSystem#Linking_to_BLIS)

**Comment by fgvanzee** [comment]
If you are building BLIS with `gcc` and OpenMP is enabled, then yes.

**Comment by poulson** [comment]
In that case, it might be worth updating the build instructions (as they currently seem to imply that this is not needed). After looking through ``config/sandybridge/make_defs.mk``, I see that OpenMP is being linked. For now, I will have my build system try to link with BLIS without specifying the OpenMP LD_FLAGS, and, if that fails, try with the OpenMP LD_FLAGS.

**Comment by fgvanzee** [comment]
I agree, the build instructions should be updated to provide guidance for OpenMP. Also with regards to POSIX threads.

**Comment by poulson** [comment]
While OpenMP isn't always used by BLIS, I would recommend linking to it in your example and mentioning that it isn't strictly required for some configurations (I have Elemental link to OpenMP when building BLIS since I can't easily determine the results of the 'auto' configuration).

**Comment by Maratyszcza** [comment]
OpenMP isn't available on all platforms, and default linking to it will confuse users. OS X, Android, iOS, and Native Client don't have it.

**Comment by poulson** [comment]
@Maratyszcza Good point; I was mentally translating what I do in CMake, which is effectively
``find_package(OpenMP)`` followed by adding in the link flags ``${OpenMP_C_FLAGS}` (which is an empty string if OpenMP is not supported by the compiler)`. But I would disagree with saying OpenMP isn't supported by OSX, as it is only clang that does not support OpenMP (I use OpenMP via GCC in OS X fairly frequently).

And, as for creating the least confusion, I think that users will be both confused and aggravated if their link fails despite following the tutorial. The best compromise might be to mention that some compilers (especially GCC) support OpenMP, while some (e.g., Clang) do not. And so, if there are unresolved symbols including "omp", then the user should add OpenMP link flags (with ``-fopenmp`` being the most common way to do so).

**Comment by jeffhammond** [comment]
@Maratyszcza Given that the LLVM posing as GCC that you note doesn't support OpenMP also doesn't support Fortran, it seems irrelevant in this case, because the issue arises in the BLAS Fortran interface.

Personally, I think anyone who uses the native compiler on Mac, which is GCC 4.2.1 on top of LLVM, deserves what incompatibilities they get, because they've chosen to use the foul toolchain that Apple has given them.

**Comment by jeffhammond** [comment]
I am closing because this issue is stale and likely has been fixed already.  Please reopen if this is not the case.

**Comment by westfly** [comment]
find_package(OpenMP REQUIRED)
target_link_libraries(target PRIVATE OpenMP::OpenMP_CXX)
