### ISSUE TITLE
threading=pthreads is broken

### ISSUE THREAD

**Issue by isuruf** [flame/blis#273]
I'm trying to use pthreads-win32 as the threading library and there are linker errors now.

See https://ci.appveyor.com/project/isuruf/blis/builds/19668917/job/fhjfy9wwtl8ynocj?fullLog=true

OpenMP and no threading works fine. https://ci.appveyor.com/project/isuruf/blis/builds/19668917

**Comment by devinamatthews** [comment]
Ah, I believe @fgvanzee is aware of this issue and working on a fix.

**Comment by fgvanzee** [comment]
@devinamatthews I am? Haha, could you remind me?

**Comment by devinamatthews** [comment]
The pthread symbols would need to be in the .def file, so you were going to change them to `bli_pthread_...` to avoid conflicts.

**Comment by fgvanzee** [comment]
@devinamatthews Oh, yes. But the `bli_pthread_*` symbols are already present in the symbols `.def` file.

@isuruf Are you using the most up-to-date commit?

**Comment by fgvanzee** [comment]
@devinamatthews Oh I see what you're saying. You're saying I should migrate all other invocations of `pthread_*()` to use the equivalent `bli_pthread_*()`.

**Comment by fgvanzee** [comment]
Scratch that. I think it's complaining because the `pthread_*()` symbols are not exported in the `.def` file.

**Comment by devinamatthews** [comment]
Yes, but you don't want them to be in case the user program uses the real pthreads itself. Do the other thing.

**Comment by fgvanzee** [comment]
Is this the problem?
```c
// From frame/base/bli_pthread_wrap.c:

#if defined(_MSC_VER) && !defined(BLIS_ENABLE_PTHREADS)

// Define pthreads implementation for Windows...
// ...
```
Sorry this isn't more obvious to me. I'm having one of those days.

**Comment by fgvanzee** [comment]
True or false. *One* solution to this would be to remove the `pthread_*` entries from the `.def` file when compiling for Windows with `-t pthreads`.

**Comment by fgvanzee** [comment]
Okay, nevermind. Those symbols aren't there to begin with.

**Comment by fgvanzee** [comment]
Okay, let me ask this a different way.

@isuruf Do you see a way to fix this *without* moving to a `BLIS_EXPORT` regime?

**Comment by devinamatthews** [comment]
1. Change `pthread_...` -> `bli_pthread_...`.
2. Use `bli_pthread_...` exclusively.
3. In bli_pthread_wrap, add branch for not Windows and add simple wrappers around `pthread_...` functions.

**Comment by devinamatthews** [comment]
Oh, and
4. Add `bli_pthread_wrap...` to .def file.

**Comment by fgvanzee** [comment]
> 4. Add `bli_pthread_wrap...` to .def file.

What does this mean? Add `pthreads_*()` symbols to the `.def` file?

**Comment by devinamatthews** [comment]
No, then you might break user code. I mean `bli_pthread_*()`.

**Comment by isuruf** [comment]
I think the issue is that external pthreads is not getting linked in windows

**Comment by fgvanzee** [comment]
> I think the issue is that external pthreads is not getting linked in windows

Is there anything we can do to this fix, or is this an AppVeyor issue?

**Comment by isuruf** [comment]
I'd like that. I thought @devinamatthews implemented only parts necessary for `threading=no`. If not, that's great.

**Comment by fgvanzee** [comment]
Okay, sounds like we are all in agreement. Now, the question is, how to proceed.

I'm guessing that the first thing we need to do is change
```c
#if defined(_MSC_VER) && !defined(BLIS_ENABLE_PTHREADS)
```
to
```c
#if defined(_MSC_VER)
```
in `frame/base/bli_pthread_wrap.c`. And it may be that this is the only thing needed. Comments?

**Comment by devinamatthews** [comment]
Yes, plus the `bli_pthread_*()` thing. Defining pthreads symbols in the .def file is still a bad idea.

**Comment by fgvanzee** [comment]
Let me reinterpret your bullets to make sure I understand. It sounds like you're saying we also need to:
1. Replace all of BLIS's internal calls to `pthread_*()` with calls to `bli_pthread_*()`
2. Seems like mostly a restatement of (1) above.
3. This item I don't really understand. Why do we need a non-Windows branch of `bli_pthread_wrap.c`? How does this relate to the existing `bli_pthread_*()` wrappers in `bli_pthread.c`?
4. Also don't understand this item, since `bli_pthread_*()` is already present in the `.def` file.

**Comment by devinamatthews** [comment]
For 1+2 this would mean changing the names in bli_pthread_wrap.c as well which didn't seem the case currently. For 3., you would need simple wrappers like:

```
static inline int bli_pthread_create(...) { return pthread_create(...); }
```

For 4., if they're already there then great.

**Comment by fgvanzee** [comment]
So you're basically saying, "For Windows, let's stop defining `pthreads_*()` and instead always define and call `bli_pthreads_*()`. Within BLIS, stop calling `pthreads_*()` and instead call `bli_pthreads_*()`. Thus, the only time we will ever syntactically utter the name `pthreads_*()` is when we are on Linux/BSD and we are actually *calling* POSIX threads functions (which will only ever happen within the definitions of `bli_pthreads_*()`)."

**Comment by devinamatthews** [comment]
Yes. This is what I thought you had already suggested in the other thread.

**Comment by fgvanzee** [comment]
I see. No, I had only envisioned the much more limited policy of calling pthreads-like functionality via `bli_pthreads_*()` from Windows applications (like the testsuite) that need it. But what you suggest is probably the "better" thing to do anyway.

**Comment by fgvanzee** [comment]
@devinamatthews When you mentioned needing to add a non-Windows case to `bli_pthread_wrap.c`, did you basically envision that cpp branch containing the definitions in `frame/thread/bli_pthread.c`? I'm thinking of merging the two.

**Comment by fgvanzee** [comment]
FYI: I've merged `bli_pthread.c` and `bli_pthread_wrap.c` (into the former) so that a unified `bli_pthread*()` API is defined, with its implementation conditionally determined by Windows-ness and Apple-ness. For the core API, Windows uses Windows threads, non-Windows uses pthreads. Apple and Windows get barriers implemented in terms of other `bli_pthread_*()` functions, and Linux gets barriers implemented in terms of `pthread_barrier*()`.

I'll finish this up tomorrow and continue testing.

**Comment by fgvanzee** [comment]
Okay everyone, I think this is fixed now. (Appveyor passed the shared library build. It seemed to get stuck on the static build, but both passed on the previous commit so I think we're good.) Thanks for your help, @devinamatthews and @isuruf.

**Comment by devinamatthews** [comment]
Someone should test that it actually works under parallel conditions.

**Comment by fgvanzee** [comment]
> Someone should test that it actually works under parallel conditions.

Agreed. But not many people are set up for that. (Maybe @isuruf?) I'll give it a day. I'd like to get this next version out the door by Friday.

**Comment by isuruf** [comment]
I can test on my computer which has 6 cores. How do I test it?

**Comment by fgvanzee** [comment]
@isuruf I'm not sure how to best test it.

**IF** you could build the testsuite, link against the Windows DLL, and run the testsuite using the input files in the `testsuite` directory, I would say that it the easiest way to test the pthreads implementation. You wouldn't even need to use environment variables; instead, you could enable application-level threading simulation in `input.general` (change it from 1 to something greater than 1) so that the testsuite performs higher-level threading across (rather than within) each operation test.

But I don't know if that's something you care to set up. (On Linux, it's easy since we have various makefiles in place.)

**Comment by fgvanzee** [comment]
I just realized that Appveyor not only builds the library but also runs the `checkblis-fast` and `check` targets. I wonder if I should just add another specialized `input.general` and `input.operations` file that will employ the application-level threading simulation. Then it would be automated, for both Travis CI and Appveyor.

**Comment by devinamatthews** [comment]
I don't know if that is a sufficient test. Better to also run the testsuite with `BLIS_NUM_THREADS=6`.

**Comment by fgvanzee** [comment]
> I don't know if that is a sufficient test. Better to also run the testsuite with BLIS_NUM_THREADS=6.

Are you suggesting to do both at the same time? Or that multithreading within BLIS should be sufficient?

**Comment by devinamatthews** [comment]
Within BLIS should be sufficient I would think. But otherwise it doesn't test the memory pools, partial barriers, broadcasting, etc.

**Comment by fgvanzee** [comment]
Fair point.

**Comment by fgvanzee** [comment]
I'm going to proceed with my previous idea, since it's probably an important enough idea to test automatically. (That isn't to say it's a substitute for the more extensive Windows tests you are proposing.)

**Comment by fgvanzee** [comment]
FYI: I'm going to proceed with the version release. If pthreads is broken on Windows, that's okay--we'll fix it eventually.

**Comment by isuruf** [comment]
threading works fine. thanks for all the work.

**Comment by fgvanzee** [comment]
Thanks for the update, @isuruf.
