### ISSUE TITLE
Disallow 64-bit integers in BLAS combined with 32-bit integers in BLIS

### ISSUE THREAD

**Issue by fgvanzee** [flame/blis#274]
@jeffhammond recently pointed out that BLIS currently allows, via the `-b 64 -i 32` options to `configure`, one to build a BLIS library that uses 64-bit integers in the BLAS compatibility layer but only 32-bit integers within the BLIS API (and in BLIS internally), and that this could allow users to stumble into situations of self-harm.

Jeff suggests this as a solution:

> A good compromise here is to disallow 64b BLAS + 32b BLIS by default but have an override (e.g. `allow_truncation`) for folks who want to live dangerously.

which seems like a decent starting point.

**Comment by fgvanzee** [comment]
@devinamatthews If we're trying to prevent `-b 64 -i 32` (as an end outcome, not literally the `configure` settings), it means we need to know what the BLIS integer size is. But the BLIS integer size is automatically determined when it is not specified explicitly via `configure`. This would suggest that the logic of preventing `-b 64 -i 32` would need to be encoded in cpp macro conditionals. Agree? Am I missing anything here?

**Comment by devinamatthews** [comment]
I would literally disallow that in configure, and then but something like this in the code:

```C
#if BLIS_BLAS_INT_SIZE == 64
typedef gint_t int64_t
#else

**Comment by fgvanzee** [comment]
Are you saying that it would need to also be disallowed in `configure`? Or are you recommending this just so that we can give explicit feedback to the user in those cases where he attempts to give the `-b 64 -i 32` options?

**Comment by devinamatthews** [comment]
The latter.

**Comment by fgvanzee** [comment]
Got it. Thanks Devin.

**Comment by fgvanzee** [comment]
Commit f19c33a should take care of this issue.
