### ISSUE TITLE
mention Fedora packages

### ISSUE THREAD

**Issue by loveshack** [flame/blis#276]
The note in the README about packaging should be amended to say that there are now blis packages in current Fedora releases and EPEL7 (for RHEL7 and clones). My copr is now only useful for EPEL6 (which doesn't have a suitable gcc available in the build system) and for OpenSuSE. Obviously it isn't useful as a BLAS on ppc64, arm, and s390; I don't know how it compares with openblas on arm64.

**Comment by fgvanzee** [comment]
>The note in the README about packaging should be amended to say that there are now blis packages in current Fedora releases and EPEL7 (for RHEL7 and clones).

@loveshack That's great news. I didn't realize that was in the cards in the short-term. Would you mind drafting your preferred language edits to the relevant `README.md` section to provide us with a starting point? You don't have to, but I thought I would offer. (Oftentimes, people like me struggle to use the correct terminology when writing about distributions which I do not routinely use such as Fedora and Debian .)

**Comment by loveshack** [comment]
I obviously didn't send any text for the readme, as I thought I had.  Here's a suggested change.

```
diff --git a/README.md b/README.md
index f639bbf1..06fac47f 100644
--- a/README.md
+++ b/README.md
@@ -269,8 +269,8 @@ please read this thorough walkthrough of the configuration system.
 about using sandboxes in BLIS--that is, providing alternative implementations
 of the `gemm` operation--please read this document.
 
-External Linux packages
------------------------
+External GNU/Linux packages
+---------------------------
 
 Generally speaking, we **highly recommend** building from source whenever
 possible using the latest `git` clone. (Tarballs of each
@@ -286,9 +286,23 @@ sponsor and maintain BLIS packages within the Debian Linux distribution. The
 Debian package tracker can be found [here](https://tracker.debian.org/pkg/blis).
 (Also, thanks to [Nico Schlömer](https://github.com/nschloe) for previously
 volunteering his time to set up a standalone PPA.)
-- **Red Hat/Fedora**. [Dave Love](https://github.com/loveshack) provides rpm
-packages for x86_64, which he maintains at
-[Fedora Copr](https://copr.fedorainfracloud.org/coprs/loveshack/blis/).
+- **EPEL/Fedora**. There are official BLIS packages in Fedora and EPEL
+(for RHEL7+ and compatible distributions) with versions for 64-bit
+integers, OpenMP, and pthreads, as for OpenBLAS, and shims  which can
+be dynamically linked instead of reference BLAS.  For architectures
+other than x86_64, and maybe arm64, the packaged BLIS will be very
+slow because it uses unoptimized generic kernels, and OpenBLAS will be
+a lot faster.
+[Dave Love](https://github.com/loveshack) provides additional
+packages for EPEL6 in a
+[Fedora Copr](https://copr.fedorainfracloud.org/coprs/loveshack/blis/),
+and possibly versions more recent than the official repo for
+other EPEL/Fedora releases.  The source packages may build on other
+rpm-based distributions.
+- **OpenSuSE**. The copr referred to above has rpms for some OpenSuSE
+releases; the source rpms may build for others.
+- **GNU Guix**. Guix has BLIS packages, provides builds only for the
+generic target and some specific x86_64 micro-architectures.
 
 Discussion
 ----------
```

**Comment by fgvanzee** [comment]
Thanks, @loveshack. I made slight tweaks to your language and commited them to aafbca08.

I'm going to close this issue. Feel free to re-open if you have any more suggestions/updates.
