### ISSUE TITLE
Build fails on msys2/Windows with "expected '(' before '{' token"

### ISSUE THREAD

**Issue by cosstas** [flame/blis#277]
Configuration runs smooth:

> $ ./configure zen
configure: detected MINGW64_NT-10.0 kernel version 2.11.1(0.329/5/3).
configure: C compiler search list is: gcc clang cc.
configure: using 'gcc' C compiler.
configure: C++ compiler search list is: g++ clang++ c++.
configure: using 'g++' C++ compiler (for sandbox only).
configure: found gcc version 8.1.0 (maj: 8, min: 1, rev: 0).
configure: checking for blacklisted configurations due to gcc 8.1.0.
configure: found assembler ('as') version 2.30 (maj: 2, min: 30, rev: ).
configure: checking for blacklisted configurations due to as 2.30.
configure: reading configuration registry...done.
configure: determining default version string.
configure: could not find '.git' directory; using unmodified version file.
configure: starting configuration of BLIS 1.2.
configure: configuring with official version string.
configure: found shared library .so version '1.2.0'.
configure:   .so major version: 1
configure:   .so minor.build version: 2.0
configure: manual configuration requested; configuring with 'zen'.
configure: checking configuration against contents of 'config_registry'.
configure: configuration 'zen' is registered.
configure: 'zen' is defined as having the following sub-configurations:
configure:    zen
configure: which collectively require the following kernels:
configure:    zen
configure: checking sub-configurations:
configure:   'zen' is registered...and exists.
configure: checking sub-configurations' requisite kernels:
configure:   'zen' kernels...exist.
configure: no install prefix option given; defaulting to '/home/cyamin/blis'.
configure: no install libdir option given; defaulting to PREFIX/lib.
configure: no install includedir option given; defaulting to PREFIX/include.
configure: no install sharedir option given; defaulting to PREFIX/share.
configure: final installation directories:
configure:   libdir:     /home/cyamin/blis/lib
configure:   includedir: /home/cyamin/blis/include
configure:   sharedir:   /home/cyamin/blis/share
configure: no preset CFLAGS detected.
configure: no preset LDFLAGS detected.
configure: debug symbols disabled.
configure: disabling verbose make output. (enable with 'make V=1'.)
configure: disabling ARG_MAX hack.
configure: building BLIS as both static and shared libraries.
configure: threading is disabled.
configure: internal memory pools for packing buffers are enabled.
configure: libmemkind not found; disabling.
configure: the BLAS compatibility layer is enabled.
configure: the CBLAS compatibility layer is disabled.
configure: the internal integer size is automatically determined.
configure: the BLAS/CBLAS interface integer size is 32-bit.
configure: configuring for conventional gemm implementation.
configure: creating ./config.mk from ./build/config.mk.in
configure: creating ./bli_config.h from ./build/bli_config.h.in
configure: creating ./obj/zen
configure: creating ./obj/zen/config/zen
configure: creating ./obj/zen/kernels/zen
configure: creating ./obj/zen/ref_kernels/zen
configure: creating ./obj/zen/frame
configure: creating ./obj/zen/blastest
configure: creating ./obj/zen/testsuite
configure: creating ./lib/zen
configure: creating ./include/zen
configure: mirroring ./config/zen to ./obj/zen/config/zen
configure: mirroring ./kernels/zen to ./obj/zen/kernels/zen
configure: mirroring ./ref_kernels to ./obj/zen/ref_kernels
configure: mirroring ./ref_kernels to ./obj/zen/ref_kernels/zen
configure: mirroring ./frame to ./obj/zen/frame
configure: creating makefile fragments in ./obj/zen/config/zen
configure: creating makefile fragments in ./obj/zen/kernels/zen
configure: creating makefile fragments in ./obj/zen/ref_kernels
configure: creating makefile fragments in ./obj/zen/frame
configure: configured to build within top-level directory of source distribution.

However, make fails pretty soon:
>$ make
Generating monolithic blis.h...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Generated include/zen/blis.h
Compiling obj/zen/config/zen/bli_cntx_init_zen.o ('zen' CFLAGS for config code)
Compiling obj/zen/kernels/zen/1/bli_amaxv_zen_int.o ('zen' CFLAGS for kernels)
Compiling obj/zen/kernels/zen/1/bli_axpyv_zen_int.o ('zen' CFLAGS for kernels)
Compiling obj/zen/kernels/zen/1/bli_axpyv_zen_int10.o ('zen' CFLAGS for kernels)
Compiling obj/zen/kernels/zen/1/bli_dotv_zen_int.o ('zen' CFLAGS for kernels)
Compiling obj/zen/kernels/zen/1/bli_dotv_zen_int10.o ('zen' CFLAGS for kernels)
Compiling obj/zen/kernels/zen/1/bli_dotxv_zen_int.o ('zen' CFLAGS for kernels)
Compiling obj/zen/kernels/zen/1/bli_scalv_zen_int.o ('zen' CFLAGS for kernels)
Compiling obj/zen/kernels/zen/1/bli_scalv_zen_int10.o ('zen' CFLAGS for kernels)
Compiling obj/zen/kernels/zen/1f/bli_axpyf_zen_int_8.o ('zen' CFLAGS for kernels)
Compiling obj/zen/kernels/zen/1f/bli_dotxf_zen_int_8.o ('zen' CFLAGS for kernels)
Compiling obj/zen/kernels/zen/3/bli_gemm_small.o ('zen' CFLAGS for kernels)
Compiling obj/zen/kernels/zen/3/bli_gemm_zen_asm_d6x8.o ('zen' CFLAGS for kernels)
In file included from kernels/zen/3/bli_gemm_zen_asm_d6x8.c:39:
kernels/zen/3/bli_gemm_zen_asm_d6x8.c: In function 'bli_sgemm_zen_asm_6x16':
./frame/include/bli_x86_asm_macros.h:56:25: error: expected '(' before '{' token
 #define BEGIN_ASM __asm {
                         ^
./frame/include/bli_x86_asm_macros.h:152:21: note: in expansion of macro 'BEGIN_ASM'
 #define begin_asm() BEGIN_ASM()
                     ^~~~~~~~~
kernels/zen/3/bli_gemm_zen_asm_d6x8.c:102:2: note: in expansion of macro 'begin_asm'
  begin_asm()
  ^~~~~~~~~
compilation terminated due to -Wfatal-errors.
make: *** [Makefile:578: obj/zen/kernels/zen/3/bli_gemm_zen_asm_d6x8.o] Error 1

Used release 1.2 but current master fails the same way too.

**Comment by fgvanzee** [comment]
@cosstas Sorry about your trouble. This appears to be an issue building for Windows, and so I have very little in the way of useful expertise and therefore won't be able to reproduce your error myself. Hopefully someone else can chime in. Also, I notice that you are probably using the official AMD versino of BLIS. (Note that the latest version of BLIS here on github is 0.5.0.) Since we do not maintain that variant of BLIS, we can't easily comment on what might be causing the error.

Aside from waiting and hoping someone here may be able to help, you have two paths forward. You could contact AMD for support on this issue. (I think they have a github page where you can open issues.) Or, you could try our version of BLIS, which may help us determine if your problem is specific to the AMD-branded variant.

**Comment by isuruf** [comment]
Try changing the line https://github.com/flame/blis/blob/4bbb454bf3c361af9e97bfa394a73d610cd9002a/frame/include/bli_x86_asm_macros.h#L52

to,

```
#if (defined(_WIN32) && !defined(__clang__) && !defined(__MINGW32__)) || defined(__MIC__)
```

**Comment by cosstas** [comment]
@fgvanzee blis-master from this repository fails the same way. However, the fix suggested by @isuruf solves the above mentioned issue. Compilation fails later on, but I will present it in another issue.
Thank you both for your help.

**Comment by fgvanzee** [comment]
@isuruf Is the patch that you suggest above one that you feel is general-purpose? If so, I will commit that fix. Just let me know.

**Comment by isuruf** [comment]
@fgvanzee, yes, the patch should be added.

**Comment by fgvanzee** [comment]
@cosstas Would you like to share your full name so that you can be credited in the `CREDITS` file? Otherwise, I can just credit you by your github handle.

**Comment by cosstas** [comment]
@fgvanzee I have updated my profile, but so far there is nothing to get credit for. You do the magic and all I can do is test...

**Comment by fgvanzee** [comment]
@cosstas I understand that you may feel your contribution is not worth crediting, but I have instituted a policy whereby everyone gets credit, no matter how small the patch/pull-request/bug-report they provide. :) Think about like democracy: every vote counts!
