### ISSUE TITLE
LAPACK test failures when linking with BLIS

### ISSUE THREAD

**Issue by cosstas** [flame/blis#284]
Having successfully compiled BLIS in MSYS2/MINGW64 environment, I built LAPACK 3.8.0 (actually the latest master version) and linked with libblis.a. Compilation completed successfully, although I have to mention that the build process changed the libblis.a library file. This happened every time I linked against BLIS but never against openBLAS.
The LIN tests with openBLAS pass 100%, but with BLIS I get some failures. I attach the full test report:
[stest.out.txt](https://github.com/flame/blis/files/2605541/stest.out.txt)
Any hints regarding this issue?

**Comment by isuruf** [comment]
Tried with MinGW 8.2 in a haswell machine in appveyor. Can't reproduce with a cmake build. See log https://ci.appveyor.com/project/isuruf/blis/builds/20473397/job/3ud1ug163rp0v6yt

**Comment by cosstas** [comment]
I had a look at the log and while trying to replicate your build environment, I got quite confused. If you are kind enough, can you answer a few questions:
1. Why do you need cmake, since in msys2 make "works"?
2. Why specify MINGW Makefile generator under MSYS2 and then use mingw32-make? Shouldn't you use MSYS makefiles and then just make? MINGW makefiles are supposed to work under windows command prompt, not bash...
3. Why do you link against libblis.dll.a and not libblis.a?

**Comment by isuruf** [comment]
1. Personal preference.
2. No reason. Both are valid IMO.
3. libblis.dll.a is the import library for the dll. Linking against libblis.dll.a means you are linking against the dll, while libblis.a is the static library. In windows it doesn't matter, but in Linux if you link with libblis.a, you also have to link with -lpthread, but if you link with libblis.so, you don't have to.

**Comment by isuruf** [comment]
For 2. I remember now. make was not installed in the msys2 environment in appveyor, but mingw32-make was.

**Comment by cosstas** [comment]
Thank you for your explanations. One other question: Why does the lapack build process changes the libblis.a file? This has never occurred before with any other library file!

**Comment by isuruf** [comment]
> Why does the lapack build process changes the libblis.a file? 

I think this is some error in the Makefiles they provide. In the CMake build, you can use a external BLAs like blis, but in the Makefiles it compiles the BLAS functions and archive those files and libblis.a together, which is weird. Another reason to use the cmake build.

**Comment by cosstas** [comment]
All this time that I linked against openBLAS, this had never happened. Why only BLIS?

**Comment by cosstas** [comment]
Well, openBLAS includes lapack, so that could be the answer. I will try to install a cmake version that produces MINGW makefiles and try again...

**Comment by isuruf** [comment]
I think that's because OpenBLAS has the same object files like `dgemm.o`. When lapack tries to archive libopenblas.a and the .o file from lapack's blas, they are just ignored.

**Comment by cosstas** [comment]
@isuruf You rock! cmake build work like a charm, and all lapack tests passed! libblis.a stayed intact.
Thank you for all your help!
