### ISSUE TITLE
Reference kernels should use #pragma omd simd

### ISSUE THREAD

**Issue by devinamatthews** [flame/blis#286]
`#pragma omp simd` is my new favorite thing because it is a vectorization pragma *that actually results in vectorized code*. In the context of optimizing level 1 and 1f kernels, this means that in most situations hand-optimized kernels are totally unnecessary, and properly written reference kernels can do the job. For example, here is a full working example for `daxpyf` (excuse the C++):

```C++
#include <cstdint>

typedef int64_t dim_t;
typedef dim_t inc_t;
    
template <dim_t F>
void daxpyf(dim_t m, dim_t n, double alpha,
            const double* restrict a, inc_t inca, inc_t lda,
            const double* restrict x, inc_t incx,
                  double* restrict y, inc_t incy)
{
    double ax[F];

    for (dim_t j = 0;j < n;j++)
        ax[j] = alpha*x[j*incx];

    if (inca == 1 && incy == 1 && n == F)
    {
        #pragma omp simd
        for (dim_t i = 0;i < m;i++)
            for (dim_t j = 0;j < F;j++)
                y[i] += a[i+j*lda]*ax[j];
    }
    else
    {
        for (dim_t i = 0;i < m;i++)
            for (dim_t j = 0;j < n;j++)
                y[i*incy] += a[i*inca+j*lda]*ax[j];
    }
}

auto _ = daxpyf<8>;
```

which can be compiled with `g++ -c -O3 -march=native -std=c++11 -fopenmp-simd -Drestrict=__restrict`. `objdump` shows essentially the same result as the hand-coded `zen` version. In C, the template can be replaced with a macro expanded with an integer literal. All reference kernels should be updated to use similar constructs with `#pragma omp simd` and configure should be updated to detect when compilers support `-fopenmp-simd` and then use it.

**Comment by fgvanzee** [comment]
@devinamatthews This seems promising.

How confident are you that a slightly different compiler (maybe different version of `gcc`, or clang, or whatever) would not screw this up somehow?

I suppose maybe it doesn't matter as long as we only use this as a freebie optimization on the reference kernels.

**Comment by devinamatthews** [comment]
@tonyskjellum I think I should clarify a couple of things so that we can move onto the same page, since I'm not sure exactly how your comment fits in with what I've presented above.

1) The purpose of including the `#pragma omp simd` directive is only to induce vectorization, and doesn't affect multithreading. In fact, you can enable this and only this family of pragmas with the `-fopenmp-simd` flag and use whatever kind of threading you want.

2) This pragma would be used in the reference kernels for various L1 and L1f operations (the latter are used in the higher-level L2 code). The higher-level code (user-facing) would still handle all multithreading details (BLIS doesn't multithread L1/L2 but of course it could). The idea is to make it *really* clear to the compiler what we want so that we could avoid hand-written kernels for most architectures (beyond tuning blocking parameters).

This approach isn't quite good enough for the gemm microkernel, though :(.

**Comment by tonyskjellum** [comment]
I agree it won’t work for the GEMM microkernel :-) thanks for the follow up...
I understand what you’re saying ... 

Anthony Skjellum, PhD
205-807-4968

**Comment by fgvanzee** [comment]
I've employed these techniques in level-1v, level-1f, and level-3 (except `gemmtrsm`) kernels in bdd46f9. The commit also contains `configure` logic that verifies that `-fopenmp-simd` is a valid compiler flag.

@devinamatthews Please take a look at a sampling of the newly rewritten reference kernels (say, `axpyv`, `axpyf`, and `gemm`) and comment at your convenience.

**Comment by fgvanzee** [comment]
I see that some tests have failed. I'll investigate.

**Comment by fgvanzee** [comment]
Update: Bugs are now [fixed](https://github.com/flame/blis/issues/259#issuecomment-457424158).

**Comment by fgvanzee** [comment]
I think this is done now. I'm going to close this issue. @devinamatthews Thanks again for your work and help on this.
