### ISSUE TITLE
build issue on arm* architectures: 'user-specified configuration '' is NOT registered!

### ISSUE THREAD

**Issue by cdluminate** [flame/blis#291]
https://buildd.debian.org/status/package.php?p=blis

affects : arm64, armhf (using arm32 config), armel (using arm32 config)

e.g. on arm64
```
configure: could not find '.git' directory; using unmodified version file.
configure: starting configuration of BLIS 0.5.1.
configure: configuring with official version string.
configure: found shared library .so version '2.0.0'.
configure:   .so major version: 2
configure:   .so minor.build version: 0.0
configure: manual configuration requested; configuring with 'arm64'.
configure: checking configuration against contents of 'config_registry'.
configure: 'user-specified configuration '' is NOT registered!
configure: 
configure: *** Cannot continue with unregistered configuration ''. ***
configure: 
make[1]: *** [debian/rules:94: config_2-openmp] Error 1
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
make: *** [debian/rules:36: build-arch] Error 2
```

click "build-attempted" to see the full log.

**Comment by fgvanzee** [comment]
Thanks for this report. I recently disabled the `arm64` and `arm32` configuration families after realizing that they are missing the logic (e.g. in terms of `cpuid` on x86_64) that would allow BLIS to appropriately choose the correct sub-configuration at runtime. The ARM sub-configurations are still available, just not the families.

There are two ways forward:
- Adjust your packaging to explicitly specify one sub-configuration for each case; `cortex-a15` for `arm32` and `cortex-a57` for `arm64` will probably work in most cases?
- We re-enable the families, but have them contain only one sub-configuration, so that, in this interim period where we lack the runtime logic to choose, the families act as temporary aliases to the chosen sub-configurations.

**Comment by cdluminate** [comment]
The first solution sounds good. And the second is potentially causing problems due to ambiguity. I'll rebuild with solution one and get back to you.

**Comment by cdluminate** [comment]
Doesn't work.

```
configure: manual configuration requested; configuring with 'cortex-a57'.
./configure: line 294: config_registry_cortex-a57: bad substitution
./configure: line 294: kernel_registry_cortex-a57: bad substitution
./configure: line 294: config_registry_cortex-a57: bad substitution
configure: checking configuration against contents of 'config_registry'.
configure: 'user-specified configuration '' is NOT registered!
configure: 
configure: *** Cannot continue with unregistered configuration ''. ***
configure: 
make[1]: *** [debian/rules:94: config_2-openmp] Error 1
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
```

https://launchpadlibrarian.net/405900345/buildlog_ubuntu-disco-arm64.blis_0.5.1-2~ub2_BUILDING.txt.gz
https://launchpadlibrarian.net/405900346/buildlog_ubuntu-disco-armhf.blis_0.5.1-2~ub2_BUILDING.txt.gz

**Comment by fgvanzee** [comment]
@cdluminate Sorry, the actual sub-configuration names are `cortexa15` and `cortexa57`. Apologies for the typos. Give that a try.

**Comment by cdluminate** [comment]
I can build the package for arm now. BTW is there any way to make BLIS tests print something? The build process won't be killed if it keeps printing something regularly. I didn't find a loop in the main function of `test_libblis.c` so I think I need some pointers.

**Comment by fgvanzee** [comment]
> I can build the package for arm now. 

Glad to hear.

> BTW is there any way to make BLIS tests print something? The build process won't be killed if it keeps printing something regularly.

I'm not sure I understand the problem. How much time do you have to work with before the build process times out?

`make check`, which runs the BLAS test drivers and a fast version of the BLIS testsuite, runs in well under two minutes on most systems.

**Comment by cdluminate** [comment]
> > BTW is there any way to make BLIS tests print something? The build process won't be killed if it keeps printing something regularly.
> 
> I'm not sure I understand the problem. How much time do you have to work with before the build process times out?

The problem is some of the available architectures time out during building BLIS, for example riscv64 and mips64el. They were determined as `inactive` and timeout due to no output to stdout, nor stderr.

https://buildd.debian.org/status/package.php?p=blis

https://buildd.debian.org/status/fetch.php?pkg=blis&arch=riscv64&ver=0.5.1-2&stamp=1547676854&raw=0

```
E: Build killed with signal TERM after 450 minutes of inactivity
```

> `make check`, which runs the BLAS test drivers and a fast version of the BLIS testsuite, runs in well under two minutes on most systems.

Indeed most systems don't time out. However, if we can make the blis tests print something, the rest architectures won't be determined as "time out due to inactivity". Then mips* and riscv64 users could also use the package.

**Comment by cdluminate** [comment]
Ah, I just realized that `make test` runs the full test... So for the architectures that timeout during build, I can simply let them run `make check`. However I still tend to make them run full tests because Debian's build machines can be regarded as testers (they are real physical machines instead of emulated machines). In this way bugs (if any) have less chance to hide.

**Comment by fgvanzee** [comment]
> Ah, I just realized that make test runs the full test... 

Yes. Sorry that wasn't more obvious. There are a lot of nuances to the test infrastructure in BLIS.

> However I still tend to make them run full tests because Debian's build machines can be regarded as testers (they are real physical machines or native virtual machines instead of emulated machines). In this way bugs (if any) have less chance to hide.

I understand your desire to do "full" tests (via `make test`), and appreciate your caution. However, trust me that the full test for BLIS is not worth the extra time. We run the full test via Travis CI automatically every time we make a commit on github. IMHO, there's no need for you to shoulder that burden as well. The "fast" version of the BLIS testsuite is still quite comprehensive, with the biggest compromise being that it only tests problem sizes of 100. (But note that while `make check` runs the fast version of the BLIS testsuite, it still runs the full BLAS test drivers.)

**Comment by fgvanzee** [comment]
@cdluminate BTW, the reason we don't want to print output from the BLIS testsuite during the running of `make check` or `make test` is that most users don't want or need to see the (overwhelming) line-by-line results, only the summary of whether there was a failure or not, which is what we do. The thinking is that if a user wanted to see the line-by-line output scroll by, they could run the BLIS testsuite manually/locally via `cd testsuite; make; ./test_libblis.x`.

I'm not sure if there is an option of getting output from the BLAS test drivers, since they output directly to files.

**Comment by cdluminate** [comment]
> The "fast" version of the BLIS testsuite is still quite comprehensive, with the biggest compromise being that it only tests problem sizes of 100. (But note that while `make check` runs the fast version of the BLIS testsuite, it still runs the full BLAS test drivers.)

Does that mean it's safe to run the fast version on all architectures and skip the full version? The fast version would must significantly reduce build time for all architectures.

> @cdluminate BTW, the reason we don't want to print output from the BLIS testsuite during the running of `make check` or `make test` is that most users don't want or need to see the (overwhelming) line-by-line results, only the summary of whether there was a failure or not, which is what we do. The thinking is that if a user wanted to see the line-by-line output scroll by, they could run the BLIS testsuite manually/locally via `cd testsuite; make; ./test_libblis.x`.

Thanks for the pointer. And I think there is no need to make testers chatty if I only run the fast tests.

**Comment by cdluminate** [comment]
Debian's ppc64el machine got 180x speedup with fast tests. I'm closing this issue since all questions have been resolved.

**Comment by fgvanzee** [comment]
> Does that mean it's safe to run the fast version on all architectures and skip the full version? The fast version would must significantly reduce build time for all architectures.

Yes, absolutely. The fast version is safe to run for all architectures. (The modest compromises it makes are not specific to any one hardware type.) And the BLAS test drivers are always run in their entirety, so that should convey a decent amount of confidence.

> Debian's ppc64el machine got 180x speedup with fast tests. I'm closing this issue since all questions have been resolved.

Great to hear.
