### ISSUE TITLE
configure script broken on BSD?

### ISSUE THREAD

**Issue by cdluminate** [flame/blis#293]
https://buildd.debian.org/status/fetch.php?pkg=blis&arch=kfreebsd-i386&ver=0.5.1-2&stamp=1547645236&raw=0
https://buildd.debian.org/status/fetch.php?pkg=blis&arch=kfreebsd-amd64&ver=0.5.1-2&stamp=1547643767&raw=0

The latest buildlogs on Debian/kfreebsd-{amd64,i386} suggests that there is some problem in sed expressions used in the configure script:

```
configure: creating ./config.mk from ./build/config.mk.in
sed: -e expression #1, char 17: unknown option to `s'
configure: creating ./bli_config.h from ./build/bli_config.h.in

...


make[2]: Entering directory '/<<PKGBUILDDIR>>/2-openmp'
Makefile:428: *** Cannot proceed: config.mk not detected! Run configure first.  Stop.
make[2]: Leaving directory '/<<PKGBUILDDIR>>/2-openmp'
```

I think Debian/kfreebsd is using the BSD version of sed instead of the GNU version. Maybe similar problem may happen on FreeBSD?

**Comment by fgvanzee** [comment]
Hmm, yes, that seems to be a problem. It might be a quoting issue. I can't imagine that BSD sed wouldn't understand `s///` notation.

Perhaps @ararslan and/or @iotamudelta could comment. They have worked with BLIS on FreeBSD and may have encountered this before, or possibly know of a workaround.

**Comment by ararslan** [comment]
I just tried configuring (with `auto`), building, and testing from a fresh clone on FreeBSD 11.2 and had no issues at all. This is using the default BSD `sed`.

**Comment by fgvanzee** [comment]
Good eye, @isuruf, and thanks for pointing this out.

@cdluminate I've pushed a commit (eec2e183) to `master` to hopefully fix this. Please try it out at your convenience.

**Comment by cdluminate** [comment]
@fgvanzee That commit amended the original configure error. And from the latest builddlogs I realized that I need to patch the header again to fix OS detection. (expected to be as easy as the hurd one)

**Comment by fgvanzee** [comment]
@cdluminate Okay, it sounds like the edits in eec2e18 are good. If you have no other concerns (at least, with the state of our upstream repository) please close the issue when you are ready.
