### ISSUE TITLE
AVX2 vgather macros take incorrect number of arguments?

### ISSUE THREAD

**Issue by fgvanzee** [flame/blis#296]
It appears that the macros defined in `bli_x86_asm_macros.h` for the AVX2 gather instructions take only two arguments:

https://github.com/flame/blis/blob/b1f5ce8622b682b79f956fed83f04a60daa8e0fc/frame/include/bli_x86_asm_macros.h#L783-L790

while Intel and [others](https://stackoverflow.com/questions/35356533/what-efficient-way-to-load-x64-ymm-register-with-4-seperated-doubles/35357883) document them as taking three arguments:
```asm
vgatherqpd ymm0, [rsi+xmm7*8], ymm1
```
It's an easy fix. However, I wanted to bring this to the attention of @devinamatthews since he was the original author of these macros (which I am growing to appreciate more and more as time goes on), mostly to get a more knowledgeable set of eyes to confirm the bug.

(According to the Intel documentation and [intrinsics guide](https://software.intel.com/sites/landingpage/IntrinsicsGuide/), this issue doesn't affect the scatter instructions since they were omitted altogether from AVX2. However, it may still affect the scatter *macros* as they relate to AVX-512.)

**Comment by tonyskjellum** [comment]
Avx-512 has new instructions for some of these ...

Anthony Skjellum, PhD
205-807-4968

**Comment by fgvanzee** [comment]
@tonyskjellum Yes, AVX-512 appears to have the full complement of gather and scatter instructions. Notice that in this issue, I am referring specifically to macros that implement the AVX2 instructions (though some of the same macros are used for AVX-512 as well).

I heard from someone at Intel once that the reason only gather instructions were present in AVX2 is because during the design for Haswell, the engineers found out they would have enough room on the silicon for one or the other, but not both, and they decided that (a) one was better than neither, and (b) gather instructions would be more generally beneficial than scatter, hence the outcome.

**Comment by devinamatthews** [comment]
@fgvanzee I only had AVX512 in mind when I wrote them. In order to support AVX2 as well you would have to change them to variadic macros a la SAR/SAL.

**Comment by devinamatthews** [comment]
I don't think anyone is ever going to use AVX2 gather so I'm closing.
