### ISSUE TITLE
arm64 family support from OpenBLAS?

### ISSUE THREAD

**Issue by loveshack** [flame/blis#299]
In case no-one's spotted it and the method would be useful since arm64 family has been dropped: I'd forgotten to say that OpenBLAS has acquired DYNAMIC_ARCH support, as they call it on Linux in
https://github.com/xianyi/OpenBLAS/commit/d5aeff636f2d8ba99d1e5ed511c3770970f440af
I don't know how much you can rely on the kernel support it needs.

**Comment by fgvanzee** [comment]
@loveshack Could you clarify the gist of your comment? I'm having trouble understanding what you are suggesting.

**Comment by loveshack** [comment]
I thought you needed a cpuid-type mechanism to dispatch on arm64 micro-arches, and that shows how to do it.
Apologies if that's wrong.
-- 
Sent from a pocket telegraph machine; excuse the result.

**Comment by fgvanzee** [comment]
Oh, right! I understand now. Sorry I didn't follow at first. Yes, someone should look at what they do to solve this problem. (Not sure if that will be me, but we know one place to look now.) Thanks for pointing this out.

**Comment by loveshack** [comment]
I added /proc-based support for arm32 (which isn't in OpenBLAS) to the PR.
That completes support for families of the supported architectures.  (See also a comment on #335.)

**Comment by devinamatthews** [comment]
I think the action is in #344 now, closing.
