### ISSUE TITLE
revising optimization flags

### ISSUE THREAD

**Issue by loveshack** [flame/blis#300]
I noticed that several configurations, specifically the AMD ones, just use -O2, which means they'll have no vectorization past the optimized kernels -- just GEMM?  (They also use -fomit-frame-pointer, which is redundant with gcc -O, but obviously harmless.)
It may  be sensible generally to build non-critical routines with -O2 rather than O3, as O2 is generally better tested, may produce smaller code, and should build faster. However, -O3, or something like it, should presumably be in CRVECFLAGS, at least.
Also, with GCC, at least CRVECFLAGS should have -funsafe-loop-optimizations added to get the rest of the reference kernels vectorized (see #259) and minimize worries about correctness, i.e.
```
# Flags specific to reference kernels.
CROPTFLAGS     := $(CKOPTFLAGS) -O3
ifeq ($(CC_VENDOR),gcc)
CRVECFLAGS     := $(CKVECFLAGS) -funsafe-loop-optimizations
else
CRVECFLAGS     := $(CKVECFLAGS)
endif
```
in all the make_defs fragments, or perhaps somewhere common.
-funsafe-loop-optimizations vectorizes all the routines -ffast-math does (on haswell) apart from frame/util/bli_util_unb_var1.c.

I could contribute the changes if they seem sensible, depending on whether common gcc flags should be duplicated in the make fragments or be abstracted somewhere.

**Comment by fgvanzee** [comment]
@loveshack I agree that the optimization flags for both optimized kernels and reference kernels can be raised to `-O3` for all x86_64-based configurations. I would go further and say that I'm comfortable with `-O3` for general framework code. In other words, I'm okay using `-O3` wherever any optimization is permitted.

I would also be open to including `-funsafe-loop-optimizations`. I've played with it a little bit, combining the option with `-Wunsafe-loop-optimizations` and, at least with gcc 5.4.0, the only warnings come from packed and banded level-2 operations in the BLAS compatibility layer, which are currently implemented via `f2c`-based translations from Fortran (since BLIS does not natively implement these operations).

> -funsafe-loop-optimizations vectorizes all the routines -ffast-math does (on haswell) apart from frame/util/bli_util_unb_var1.c.

Could you explain the above comment? I don't quite follow. Are you suggesting that no optimization flags be used when compiling `bli_util_unb_var1.c`? Or suggesting that that is already the case? (I can't find evidence in the top-level Makefile that this file is given any special treatment.)

**Comment by fgvanzee** [comment]
Quick update: I'm having trouble getting the new flags through our Travis CI tests. I get the following error:
```
+sde-external-8.16.0-2018-01-30-lin/sde64 -cpuid_in ./travis/cpuid/piledriver.def -- ./test_libblis.x
TID 0 SDE-ERROR: Executed instruction not valid for specified chip (ICELAKE): 0x9172a5: bextr_xop rax, rcx, 0x103
Image: /home/travis/build/flame/blis/test_libblis.x+0x5172a5 (in multi-region image, region# 0)
Function: bli_dsetv_piledriver_ref
Instruction bytes are: 8f ea f8 10 c1 03 01 00 00 
```
I'm still trying to isolate exactly what is causing the problem. At first I figured it was the addition of `-funsafe-loop-optimizations`, but I backed out all of those changes and the error persists. I'm now making sure this isn't being caused by a change on Travis's side by rerunning the corresponding test from a recent commit that had previously passed. (And indeed it did pass again.) The only other (seemingly) relevant changes I made are the bump from `-O2` to `-O3` for some configurations and removal of `-fomit-frame-pointer`.

@devinamatthews Any thoughts?

**Comment by devinamatthews** [comment]
@fgvanzee it looks like an AMD "TBM" instruction whatever that is.

**Comment by fgvanzee** [comment]
Thanks for sussing that out. gcc isolates the TBM instruction set via `-mtbm`, and so I can probably fix this nonsense with `-mno-tbm`. (And maybe disable [XOP and LWP](https://en.wikipedia.org/wiki/XOP_instruction_set#History) while I'm at it.)

**Comment by fgvanzee** [comment]
That fixed it. Extra thanks, Devin.

**Comment by fgvanzee** [comment]
@loveshack I've reverted back to using `-funsafe-loop-optimizations`. Feel free to review those changes while we do further testing in the lead up to merging back into `master`.

**Comment by jeffhammond** [comment]
If you are going to use Intel SDE to try to emulate AMD processors, I recommend setting compiler flags that limit the code generation to the union ISA (`Intel & AMD`) and confirm any exceptions to this with the SDE documentation.
The following seem like relevant references:
- https://en.wikipedia.org/wiki/Bit_Manipulation_Instruction_Sets#TBM_(Trailing_Bit_Manipulation)
- https://en.wikipedia.org/wiki/XOP_instruction_set#CPUs_with_XOP

**Comment by loveshack** [comment]
Oh heck. Sorry I've wasted your time with a typo somehow. The option should be -funsafe-math-optimizations, not loop. It must have been either some paste error or a bad Emacs expansion.
I did test the vectorization with the right flag before I found the option to treat the kernels separately. The comment was that compared with fast-math, it only missed vectorization in the one file, which isn't a ukernel.
I did try unsafe-math-optimizations, but it didn't help dgemm, and has been removed from recent gcc anyhow.
I'll look at the change when I can. Apologies for the error.
-- 
Sent from a pocket telegraph machine; excuse the result.

**Comment by loveshack** [comment]
It occurs to me that changed flags should be checked with the testsuite
on other architectures than x86_64; I don't know if you (can) do that.
I can do it on the Fedora architectures by modifying the build, but I
only have access to most of them via the build system if something needs
debugging, and arm might time out.  It probably makes sense to do that
with the new gemm kernel, though.

**Comment by fgvanzee** [comment]
@jeffhammond I'm having trouble following your suggestion. Are you suggesting that we enable FMA4, XOP, TBM, and LWP, and then somehow ignore the invalid instruction errors that come out of the SDE?

@loveshack It's okay, these things happen. I'm just glad I didn't spend *too* much time on it. :) As for using `-funsafe-math-optimizations`, I'm a bit more wary of these kinds of optimizations than those implied by `-funsafe-loop-optimizations`. Let me play with it a bit and see how the BLAS test drivers and BLIS testsuite respond to them.

> It occurs to me that changed flags should be checked with the testsuite on other architectures than x86_64; I don't know if you (can) do that.

@loveshack I think our way of doing this is typically to let [Travis CI](https://travis-ci.org/flame/blis/) chew on the new build (which uses the SDE as one of the tests) and see what happens. But I may be misunderstanding your comment.

**Comment by loveshack** [comment]
> As for using
> `-funsafe-math-optimizations`, I'm a bit more wary of these kinds of
> optimizations than those implied by `-funsafe-loop-optimizations`. Let
> me play with it a bit and see how the BLAS test drivers and BLIS
> testsuite respond to them.

I think I said somewhere that I successfully ran the full testsuite with
it (actually fast-math, I think) for Haswell.

>> It occurs to me that changed flags should be checked with the
> testsuite on other architectures than x86_64; I don't know if you
> (can) do that.
>
> @loveshack I think our way of doing this is typically to let [Travis
> CI](https://travis-ci.org/flame/blis/) chew on the new build (which
> uses the SDE as one of the tests) and see what happens. But I may be
> misunderstanding your comment.

That sounds like multiple x86_64 micro-architectures as opposed to, say,
aarch64, which is what I meant.  (You can run under qemu emulation, but
rather slowly.)  Apart from x86 and x86_64, the Fedora build system has
ppc64le, armhf, aarch64, and s390 for building packages, if that's
useful.  Also I currently have access to various generations of real
x86_64 from Magny Cours (probably not for long) through to SKX.

**Comment by fgvanzee** [comment]
> I think I said somewhere that I successfully ran the full testsuite with it (actually fast-math, I think) for Haswell.

I must have missed that. (Sorry.) But please humor me. I am somewhat conservative when it comes to numerical issues, mostly because I am wary of issues lurking in that region just beyond my expertise. :)

> That sounds like multiple x86_64 micro-architectures as opposed to, say, aarch64, which is what I meant.

Ohhh, I see what you mean. You meant other architectures such as ARM or Power. Yeah, our methods of testing changes of any sort for those non-x86_64 architectures is more limited.

**Comment by loveshack** [comment]
Note that the Intel compiler(s?) default to something like fast-math, or some subset, so you'd need to turn that off in rules for icc if you're worried.
-- 
Sent from a pocket telegraph machine; excuse the result.

**Comment by jeffhammond** [comment]
> Are you suggesting that we enable FMA4, XOP, TBM, and LWP, and then somehow ignore the invalid instruction errors that come out of the SDE?

No, the opposite.  Disable these instructions unless you know SDE supports them.

**Comment by jeffhammond** [comment]
@loveshack Correct, ICC defaults to flags that are similar to `-ffast-math` by default at any level of optimization, but not `-O0`.  See https://github.com/Reference-LAPACK/lapack/issues/43#issuecomment-244949746 and https://github.com/elemental/Elemental/issues/179 for background.

**Comment by fgvanzee** [comment]
> the union ISA (Intel & AMD)

@jeffhammond Then maybe you meant the intersection ISA? :)

> Correct, ICC defaults to flags that are similar to `-ffast-math` by default at any level of optimization, but not `-O0`.

This makes me feel better. Thanks for that.

**Comment by loveshack** [comment]
> @loveshack Correct, ICC defaults to flags that are similar to
> `-ffast-math` by default at any level of optimization, but not `-O0`.

And -O0 isn't the default.  (I'm too familiar with ifort issues from
other people using it, but I don't know if it's actually the same
compiler as icc.)  I did think the icc default would fail more of
floating point paranoia than it actually does.

> See
> https://github.com/Reference-LAPACK/lapack/issues/43#issuecomment-244949746
> and https://github.com/elemental/Elemental/issues/179 for background.

To someone like me who's often had to cope with complaints about
compiler behaviour on incorrect code, the issue shouldn't be whether
optimizations break code, but whether they break correct code
(e.g. Kahan summation, which presumably you could use for ?asum).
Obviously one can argue somewhat values of "break" for FP, but defaults
really should be correct for the language.  (It surprises me that this
has only come up fairly recently for LAPACK.)

**Comment by loveshack** [comment]
>> Correct, ICC defaults to flags that are similar to `-ffast-math` by
>> default at any level of optimization, but not `-O0`.
>
> This makes me feel better. Thanks for that.

For what it's worth, sharing a concern for correctness, I don't
understand why.  What gave me some confidence is passing the test suite,
the existing tuned implementations, and established implementations that
do something similar.  I was taking into account that GCC says NEON
isn't conformant anyhow, and OpenBLAS has SIMD versions of similar sorts
of kernels to the ones that vectorize with unsafe-math.  I also assume
that BLAS was OK in the past with the default(?) non-conforming Alpha
floating point, though I don't remember details of that -- not SIMD
anyhow.

This seems like the sort of thing that should have been analysed, but I
can't find anything relevant.

**Comment by jeffhammond** [comment]
> the union ISA (Intel & AMD)
>
> @jeffhammond <https://github.com/jeffhammond> Then maybe you meant the
> intersection ISA? :)
>

Doh!
-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by fgvanzee** [comment]
> No, the opposite. Disable these instructions unless you know SDE supports them.

Glad we are in agreement, then. And that is what I have done: the AMD-only instruction sets have been disabled in all AMD configurations (except bulldozer, since its microkernels use FMA4, I think).

**Comment by zerothi** [comment]
I would be against adding `-ffast-math` by default. I think for these libraries users should get what they expect, a numerically safe and predictable library. We have in our physics applications found that using unsafe math operations worsens iterations, although the performance is higher. So even for Intel we recommend forcing these things: `-prec-div -prec-sqrt -fp-model source` to ensure some kind of consistency.

Adding a `configure` option with `fast-math`/`unsafe-math` would probably be the most clear and informative way of handling this?

**Comment by isuruf** [comment]
Another issue with `-ffast-math` is that it affects other libraries in the same process as a library compiled `-ffast-math`. For example `-ffast-math` implies no subnormals which is a global flag and every other library is affected.

**Comment by fgvanzee** [comment]
> For what it's worth, sharing a concern for correctness, I don't understand why. What gave me some confidence is passing the test suite, the existing tuned implementations, and established implementations that do something similar. 

The reason it made me feel a little better is that plenty of people trust icc (perhaps a little too much), and I was assuming Intel would not abuse such trust by choosing risky defaults in their compiler. But you make (or imply) a good point, Dave, in that I should probably not fall for such herd mentality. If it's the wrong decision, two projects making the wrong decision doesn't help make the world better for the user community.

I'm open to being persuaded on `-ffast-math`, but so far, I haven't seen enough evidence to get me there. My gut tells me that whatever performance benefit is attainable with such an option (which I suspect is quite small in practice) is just not worth the risk.

**Comment by loveshack** [comment]
> I would be against adding `-ffast-math` by default.

[Actually just -funsafe-math-optimizations is enough for CRVECFLAGS, but
that can probably be reduced to -fassociative-math.]

> I think for these
> libraries users should get what they expect, a numerically safe and
> predictable library.

If the resulting vectorization is a problem with BLAS implementations,
something should be added to the test suite.  OpenBLAS and MKL (?) do
vectorize reductions, presumably with similar effect to using
unsafe-math-optimizations.  I think BLIS is currently similar with the
simd pragma.  Also, optimized BLAS with ARM Neon, may have similar
effects in other kernels, as the GCC doc comments.

> We have in our physics applications found that
> using unsafe math operations worsens iterations, although the
> performance is higher. So even for Intel we recommend forcing these
> things: `-prec-div -prec-sqrt -fp-model source` to ensure some kind of
> consistency.

I'm consistently rude about the Intel defaults, and cared about GCC
correctness as a maintainer.  That sort of thing can make some types of
calculation simply fail, but the question is whether it, or hand-imposed
vectorization, significantly breaks the generic kernels despite the test
suite.  [See a previous comment about compiler vectorization versus simd
pragmas.]

A numerical analyst told me this is Nick Higham's domain, and I should
probably ask about it, but I may not get in a useful interrupt.

> Adding a `configure` option with `fast-math`/`unsafe-math` would
> probably be the most clear and informative way of handling this?

You can do that with CFLAGS, but you can only turn off the simd pragmas
by hacking configure.

**Comment by loveshack** [comment]
> Another issue with `-ffast-math` is that it affects other libraries in
> the same process as a library compiled `-ffast-math`.

It's not used at link time.  -fassociative-math probably does enough
anyhow, but I haven't checked.

**Comment by devinamatthews** [comment]
@loveshack Yes, the numerical approximations needed by most of BLIS are pretty tame and covered by either `-ffast-math` or `-funsafe-math-optimizations` (the latter enables FMA, right? also note that vectorization can actually *improve* accuracy, especially in dot...). However, what we haven't discussed is complex arithmetic. There, the difference between `-ffast-math` and `-funsafe-math-optimizations` is the option `-fcx-limited-range` which can be dangerous. Currently this affects `[cz]invertv` and linear solves, but I think there was at one time an `invscal` operation too? More code could very well be added at some point that divides complex numbers.

**Comment by devinamatthews** [comment]
Update: I compiled the following code with gcc 8.2, clang 7.0.0, and icc 19.0.1 on Godbolt,

```C
#include <complex.h>

void zinvscal(int n, const double complex * restrict alpha,
              double complex * restrict x, int incx)
{
    const double complex ialpha = 1/(*alpha);
    for (int i = 0;i < n;i++) x[i] *= ialpha;
}
```

My assumption here is that for complex numbers, the approximation `x/y = x*(1/y)` is good enough, but `1/y = conj(y)/norm(y)` is not. This means that the compiler should do something special to compute `ialpha` (i.e. gcc should use `__divdc3`), but the loop can be vectorized. Here are the results for different compilers and flags (all -O3 and targeting Haswell):

Compiler \ Flags | Default | `-funsafe-math-optimizations` or `-fp-model fast=1` | + `-ffinite-math-only` | `-ffast-math` or `-fp-model fast=2`
---|---|---|---|---
gcc | Uses `__divdc3` and `__muldc3` in loop | Same | Same | `__divdc3` optimized to `conj(y)/norm(y)` 
clang | Same as gcc except checks for NaN outside of __muldc3 | Loop vectorized but still checks for NaN | Loop fully vectorized | Same as gcc
icc | Uses `__divdc3` (inlined), loop vectorized | Same | N/A | Same as gcc

So, it seems that according to the assumptions above, the "right" flags are `-funsafe-math-optimizations -ffinite-math-only` for clang and the default flags for icc, but there don't seem to be a single set of flags for gcc that do what I want.

Unless of course people are OK with `-fcx-limited-range` and then `-ffast-math` or `-fp-model fast=2` should be fine for BLIS.

**Comment by devinamatthews** [comment]
I should also mention that if you change the inner loop to:
```C
for (int i = 0;i < n;i++) x[i] /= *alpha;
```
then every compiler only vectorizes with the highest flags (i.e. they don't seem to separate the `x/y = x*(1/y)` and `1/y = conj(y)/norm(y)` optimizations).

**Comment by fgvanzee** [comment]
@devinamatthews Thanks for reporting these details, Devin. It sounds like your preliminary conclusion is that gcc flags should not be modified yet, but that we could begin using `-funsafe-math-optimizations -ffinite-math-only` for clang?

**Comment by devinamatthews** [comment]
@fgvanzee do you have any comment of `-fcx-limited-range`? @loveshack do you have any suggestions for gcc flags?

**Comment by fgvanzee** [comment]
> @fgvanzee do you have any comment of `-fcx-limited-range`?

I'm afraid I don't have anything super-intelligent to add at this time.

Forgive me if I'm reading your table incorrectly, but it sounds like while there is no one set of flags that does what you want in gcc, `-funsafe-math-optimizations` seems to be a step in the right direction. Is the only thing missing the vectorization of the loop?

**Comment by devinamatthews** [comment]
@fgvanzee Yes. Although, I suppose since BLIS uses level-0 macros we could implement complex multiplication in terms of real multiplication which would recover vectorizability with just `-funsafe-math-optimizations`.

**Comment by fgvanzee** [comment]
> since BLIS uses level-0 macros we could implement complex multiplication in terms of real multiplication which would recover vectorizability with just -funsafe-math-optimizations.

Bingo. So perhaps the emerging consensus is:

* gcc: `-funsafe-math-optimizations`
* clang: `-funsafe-math-optimizations -ffinite-math-only`
* icc: (no new flags)

Should `-ffinite-math-only` be used for gcc as well?

**Comment by devinamatthews** [comment]
The other thing that `-ffinite-math-only` affects is multiplying by zero. Most kernels special case this (e.g. beta=0), but for example if you fake real*complex as complex*complex with an imaginary zero component then this matters.

**Comment by fgvanzee** [comment]
>The other thing that -ffinite-math-only affects is multiplying by zero.

Then it sounds like it's not that important in our case, for either gcc or clang. BLIS's level-0 scalar macros almost always manually optimize situations where you are multiplying by real x complex to avoid the zero imaginary component entirely.

**Comment by devinamatthews** [comment]
I think `-funsafe-math-optimizations` and `-O3` have percolated into all the configs.
