### ISSUE TITLE
add version script for BLAS/CBLAS-only purposes

### ISSUE THREAD

**Issue by cdluminate** [flame/blis#301]
If a user only wants to take BLIS as a BLAS/CBLAS implementation, he/she might want to hide the `bli_*` symbols instead of always exposing them to the dynamic linker. The following version script is exactly for this purpose:

```
{
  # Export BLAS and CBLAS symbols
  global:
    cblas_*;
    *_;
    CBLAS_*;
    RowMajorStrg;

  # Hide everything else.
  local:
    bli_*;
    *;
};
```

And it can be used like this:
```diff
Build a libblas.so.3 shared object.

Index: blis/Makefile
===================================================================
--- blis.orig/Makefile
+++ blis/Makefile
@@ -649,6 +649,7 @@ else
 	@$(LINKER) $(SOFLAGS) -o $(LIBBLIS_SO_OUTPUT_NAME) $? $(LDFLAGS)
 endif
 endif
+	$(LINKER) $(SOFLAGS) -o $(BASE_LIB_PATH)/$(DEB_LIBBLAS) $? $(LDFLAGS) -Wl,--soname,$(DEB_LIBBLAS) -Wl,--version-script=debian/version_script.lds
 
 # Local symlink for shared library.
 # NOTE: We use a '.loc' suffix to avoid filename collisions in case this
```

This script makes sense for Debian package because I have to compile two shared objects: one is standard libblis (SONAME=libblis.so.2), and another one (compiled from the same set of object files) is compiled as libblas (SONAME=libblas.so.3, used as BLAS alternative).

Should I submit a PR and put the version script somewhere?

**Comment by fgvanzee** [comment]
@cdluminate Thanks for the suggestion. Yes, let's try to make your life a little easier. Please start a PR. (If I have any tweaks, I can suggest them and/or push them to the PR branch prior to merge.)

**Comment by isuruf** [comment]
I've got a PR at https://github.com/flame/blis/pull/302 that will help. (It doesn't use gcc specific version scripts).

It defines `BLIS_EXPORT_BLIS` and `BLIS_EXPORT_BLAS` and a configure time option can enable blis and blas functions.

**Comment by fgvanzee** [comment]
> I've got a PR at #302 that will help. (It doesn't use gcc specific version scripts).

Yes, thanks for pointing this out. (For some reason, my brain did not see the relation between the two.)

Would Isuru's PR get us close to a solution that would work for you, @cdluminate?

**Comment by isuruf** [comment]
I didn't realize that you wanted to build the library twice without exporting symbols. #302, #303 will not be enough for you.

**Comment by fgvanzee** [comment]
@isuruf No worries. Your work on symbol export is still definitely welcome and needed.
@cdluminate Once things settle down with the export stuff, go ahead and submit a PR. We'll figure out a solution that works for you.

**Comment by devinamatthews** [comment]
It's not clear to me what additions to the BLIS code and/or build system are still missing to make this happen. It seems that the rest is a matter of packaging? Please reopen or submit a PR if that's not the case.
