### ISSUE TITLE
Makefile is not compatible on Mac

### ISSUE THREAD

**Issue by ludlows** [flame/blis#315]
> OS X does not ship gcc anymore - The Xcode/CLT packages provide a /usr/bin/gcc shim, but it is actually clang.

> Homebrew does not install gcc as "gcc", but as "gcc-5", to avoid conflicts. So you'd want to do something like make CC=gcc-5 (depending on how the build system for this particular software looks for the compiler).

Here is the problem: I was trying to build the code, however clang is the default gcc on Mac. 
The linux gcc is renamed as gcc-7 on Mac . is there a way to generated corresponding Makefile to build the code successfully?

I tried to add one line code "CC := gcc-8" in the generated Makefile but still got errors like "clang: error: unsupported option '-fopenmp'"

Thanks.

**Comment by isuruf** [comment]
Run `./configure --help` for info on how to set the compiler.

**Comment by ludlows** [comment]
Thanks @isuruf .

it works.

Here is my command: 
> $./configure -t openmp -p ~/blis CC=gcc-8 auto 

`gcc-8` depends on the version of gcc on your Mac.

Hope it helps.

**Comment by ludlows** [comment]
So I just close the issue here
