### ISSUE TITLE
Distro-specific opportunity for flatten-headers.py to be un-runnable

### ISSUE THREAD

**Issue by fgvanzee** [flame/blis#318]
The version of python found by `configure` is not necessarily the one used by `build/flatten-headers.py` when it is executed via the top-level `Makefile`.

Currently, `build/flatten-headers.py` uses `python`, whatever that may be (python2 or python3). In virtually every instance I've seen of BLIS being built, `configure` finds `python`, which is actually a symbolic link to `python2` or `python3`, perhaps through another level of indirection with links, launchers, etc.

However, if a Linux distribution were to supply `python3` (or `python2`), but **not** `python`, then the BLIS build system would fail with the following error (or something similar):
```
$ make
Generating monolithic blis.h/usr/bin/env: ‘python’: No such file or directory
Makefile:459: recipe for target 'include/haswell/blis.h' failed
make: *** [include/haswell/blis.h] Error 127
```
There is no easy solution to this that does not involve modification of the `build/flatten-headers.py` file as a function of which python was detected by `configure`. This would involve renaming the file to `build/flatten-headers.py.in`, replacing `python` on the first line with some anchor, such as `@python@`, and adding logic to `configure` to substitute in the value of `${found_python}` for that anchor at configure-time.

**Comment by isuruf** [comment]
`PYTHON=python3 make` doesn't work?

**Comment by devinamatthews** [comment]
Is `build/flatten-headers.py` both python2 and python3 compatible?

**Comment by devinamatthews** [comment]
There's also this curious construction found in the comments [here](https://blogs.gnome.org/mcatanzaro/2018/02/16/on-python-shebangs/):

```sh
#!/bin/sh
'''which' python2.7 > /dev/null && exec python2.7 "$0" "$@" || exec python "$0" "$@"
'''
```

**Comment by jdiamondGitHub** [comment]
In my experience, it would be really unusual to hook python 3 that way, as most systems have to explicitly specify "python3" for python v3, with "python" defined to be python 2. Of course, that might change eventually - like when Python 4 is released.

-- 
 Jeff Diamond
 jeff_diamond@fastmail.com



On Sun, Jun 9, 2019, at 3:36 PM, Field G. Van Zee wrote:
> The version of python found by `configure` is not necessarily the one used by `build/flatten-headers.py` when it is executed via the top-level `Makefile`.

> Currently, `build/flatten-headers.py` uses `python`, whatever that may be (python2 or python3). In virtually every instance I've seen of BLIS being built, `configure` finds `python`, which is actually a symbolic link to `python2` or `python3`, perhaps through another level of indirection with links, launchers, etc.

> However, if a Linux distribution were to supply `python3` (or `python2`), but *not* `python`, then the BLIS build system would fail with the following error (or something similar):

> `$ make
Generating monolithic blis.h/usr/bin/env: ‘python’: No such file or directory
Makefile:459: recipe for target 'include/haswell/blis.h' failed
make: *** [include/haswell/blis.h] Error 127
`

**Comment by devinamatthews** [comment]
@jdiamondGitHub @fgvanzee  I've dealt with systems where `python == python3` but never one where `python` just didn't exist and `python[23]` did.

**Comment by fgvanzee** [comment]
@isuruf @jdiamondGitHub @devinamatthews To give you all a little background: I was never able to reproduce this bug exactly, but a student in Robert's new MOOC (titled [Programming for High-Performance](http://ulaff.net/)) ran into exactly this problem. The student may have been working on some Linux distribution running in a VM, maybe in the cloud--who knows. Point being, it was an unconventional system, and I deduced from the `configure` output that the student provided that the system did *not* have `python` (at least, not in the user's `$PATH` variable?), but *did* have `python3`. Furthermore, running `./configure PYTHON=python3 auto` did not seem to help the student. What finally fixed their problem was manually changing the first line of `flatten-headers.py` to `#!/usr/bin/env python3` (from `#!/usr/bin/env python`).

To clarify, I never meant to convey that this issue was pressing or would affect lots and lots of people. Instead, I opened it merely to document the issue so that eventually, sometime in the future, we could fix it--especially if the right opportunity came along in the form of related changes that would be made anyway.

**Comment by bonakdarf92** [comment]
@fgvanzee I was able to reproduce the error because I ran into it myself. This comes from moronic idea to get everything running on windows without knowledge about cygwin and so on. Apperently both of us tried to use cygwin as workaround and get blis running, but since no requierements for cygwin are given path and bash errors occur during make process.

For everybody else trying to get blis running on windows 
1) get a cygwin with python, perl, gcc, dos2unix, nginx and everything else preventing you from ./configure
2) Convert all files with dos2unix with the command 
``` Terminal
find . -type f -print0 | xargs -0 dos2unix
```
3) change the first line of "flatten-headers.py" according to @fgvanzee post

**Comment by bonakdarf92** [comment]
@fgvanzee 
Yesterday i found a quiet interesting site about cygwin and which packages are needed. I tried a new installation with all the instructions and it worked flawless.
https://www.math.ucla.edu/~wotaoyin/windows_coding_cygwin.html
I think this might be a solution for all windows users. What is your opinion ?

**Comment by fgvanzee** [comment]
@bonakdarf92 I'm glad you found a guide that worked for you.

Is it your suggestion that I update the system requirements mentioned in Intro of the [BuildSystem.md](https://github.com/flame/blis/blob/master/docs/BuildSystem.md) document to contain a sentence or two for those using cygwin? (I would be fine linking, within the new text, to the site you found as a tip for cygwin people.)

**Comment by isuruf** [comment]
> ./configure PYTHON=python3 auto did not seem to help the student.

I think this is not saved by configure. So, you need to do `PYTHON=python3 make` too.

**Comment by fgvanzee** [comment]
@isuruf Good point. I tried `PYTHON=python3 make` in my simulated broken environment and it worked.

**Comment by fgvanzee** [comment]
I'm going to declare `PYTHON=python3 make` as the official solution to this admittedly rare scenario. If someone runs into this problem and this fix doesn't work, please re-open this issue.
