### ISSUE TITLE
get SDE from the right place

### ISSUE THREAD

**Issue by jeffhammond** [flame/blis#319]
https://github.com/mmcloughlin/meow/blob/871e50784daff1c9ec5ef66fe3d8fda6bbcd42cf/.travis.yml is a way better way to download SDE than my hack.  They are very smart.  We should emulate their smartness.

The important part is the following, which I verified locally:
```yaml
install:
- export "SDE_VERSION_NAME=sde-external-8.16.0-2018-01-30-lin"
- curl --verbose
       --form accept_license=1
       --form form_id=intel_licensed_dls_step_1
       --output /dev/null
       --cookie-jar jar.txt
       --location
       https://software.intel.com/protected-download/267266/144917
- curl --verbose
       --cookie jar.txt
       --output sde.tar.bz2
       https://software.intel.com/system/files/managed/2a/1a/${SDE_VERSION_NAME}.tar.bz2
```

**Comment by devinamatthews** [comment]
1. Is this an "Intel-blessed" method?
2. What if Intel changes the links?

**Comment by devinamatthews** [comment]
@fgvanzee after OOB discussion this looks like a good way to go. Also, it should allow PRs to pass the testsuite!

**Comment by fgvanzee** [comment]
@devinamatthews Could you put together a PR for what you had in mind?
