### ISSUE TITLE
Compilation fails on IBM Power systems ppc64le for blis 0.24 and up 

### ISSUE THREAD

**Issue by chenglinzhang** [flame/blis#320]
blis 0.1.10 compiles on ppc64le fine. The versions 0.24 and up fail to compile. I am using IBM Power8, and the Cython version is 0.26. gcc version is 5.4.0.

**Comment by cdluminate** [comment]
@chenglinzhang Could you please post the exact error messages or the buildlog? I've ever built BLIS on Power8 and I have a Power9 VM for daily use and I cannot imagine what might go wrong.

**Comment by devinamatthews** [comment]
I'm closing until and unless some more information comes in.
