### ISSUE TITLE
comparison with libxsmm

### ISSUE THREAD

**Issue by loveshack** [flame/blis#326]
The small-dimension performance figures don't include a comparison with libxsmm for x86_64.  I'd expect that, or some justification for not doing so.  (I don't remember at what dimensions it starts being relevant.)

**Comment by devinamatthews** [comment]
From the libxsmm github page: "a problem-size suitable for LIBXSMM falls approximately within (M N K)^1/3 <= 64". From the graphs in PerformanceSmall.md it seems that most of the invocations might just end up being regular BLAS.

**Comment by loveshack** [comment]
> From the libxsmm github page: "a problem-size suitable for LIBXSMM
> falls approximately within (M N K)^1/3 <= 64". From the graphs in
> PerformanceSmall.md it seems that most of the invocations might just
> end up being regular BLAS.

Probably, but I'd expect "small" to mean the sort of region addressed by
libxsmm, and larger dimensions below the performance shoulder to count
as "medium".  I think it's worth saying for justification/clarity that
you're not addressing such cases.

**Comment by fgvanzee** [comment]
@loveshack It was my understanding that MKL uses libxsmm where applicable. I could be wrong. (Intel MKL 2019 update 3's [release notes](https://software.intel.com/en-us/articles/intel-math-kernel-library-release-notes-and-new-features) allude to new JIT functionality for small `sgemm`/`dgemm`.) This was why I hadn't tested libxsmm separately. But now that you mention it, I am curious. So I'll investigate testing libxsmm in the future.

**Comment by loveshack** [comment]
I don't know what MKL does, but it's non-free (I couldn't distribute
cp2k linked against it, for instance), and Pabst said it only got its
small matrix support because it was being beaten by libxsmm.  Presumably
our Intel consultant knows more.

If you clarify what's meant by "small" there, and maybe say BLIS doesn't
aim to cover it, that would be fine.  It just seemed odd not to mention
libxsmm in that context.

**Comment by fgvanzee** [comment]
One person's "small" may be another person's "medium" may be another person's "tiny." I'll just add libxsmm to the graphs and let the audience decide which region to focus in on.

**Comment by jeffhammond** [comment]
> I don't know what MKL does, but it's non-free (I couldn't distribute
> cp2k linked against it, for instance),


Look again.  It might have changed.  It’s free as in beer now and for a few
years. You can get it from Yum and Apt repos as well as maybe Anaconda and
some other thing. Internet has details.

and Pabst said it only got its
> small matrix support because it was being beaten by libxsmm. Presumably
> our Intel consultant knows more.
>

I think that’s a fair statement. Competition is good in every dimension.
-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by rvdg** [comment]
I always argue that companies should financially support BLIS so as to make sure that products like MKL are at their best.  Even if BLIS does not attain the best performance, it makes others attain best performance, and that helps the community.  (And then, of course, there is the fact that BLIS can more easily expand functionality beyond the BLAS.)

**Comment by loveshack** [comment]
> One person's "small" may be another person's "medium" may be another
> person's "tiny." I'll just add libxsmm to the graphs and let the
> audience decide which region to focus in on.

Sure, but I think most people involved with machine learning and
materials computation would expect "small" to be in the libxsmm region
and expect the comparison.  I'd be happy with some disclaimer saying it
isn't relevant.

**Comment by loveshack** [comment]
>> I don't know what MKL does, but it's non-free (I couldn't distribute
>> cp2k linked against it, for instance),
>
>
> Look again.  It might have changed.  It’s free as in beer now and for a few
> years. You can get it from Yum and Apt repos as well as maybe Anaconda and
> some other thing. Internet has details.

I know what the licence says -- unlike most, I actually read them...  It
may be free of charge, but it obviously isn't free software.  Apart from
that excluding use in relevant GNU/Linux distributions, cp2k has no GPL
exception.  (My all-free software build was reportedly faster than an
Intel compiler+MKL+MPI one on Sandy Bridge anyway.)

**Comment by loveshack** [comment]
> @loveshack @jdiamondGitHub The new performance graphs are up, with
> libxsmm included. The libxsmm library comes with some pretty serious
> limitations, though, including (from their
> [website](https://github.com/hfp/libxsmm)):

Sure, but it covers the applications which need "small" matrix support
in the sense people like me probably understand it.

**Comment by jeffhammond** [comment]
@loveshack If MKL redistribution is a bottleneck for you, write me an email and I'll try to solve it.

**Comment by fgvanzee** [comment]
I'm going to consider this issue closed. @loveshack please reopen if you have any remaining concerns.
