### ISSUE TITLE
don't use popen

### ISSUE THREAD

**Issue by loveshack** [flame/blis#335]
On ARM, frame/base/bli_cpuid.c currently calls popen, and surely shouldn't.  It's at least surprising to have the library spawning a shell -- which may be prevented by SELINUX etc. anyway -- and it's probably worthy of a CVE in case it's run by a privileged process.  (See popen(3) and system(3).)

If BLIS must check /proc/cpuinfo, it should just read it and examine it line-wise.

On aarch64, this business doesn't seem to add anything that isn't determined by the compilation target anyhow, and #299 refers to a possible mechanism for distinguishing aarch64 micro-architectures.  Actually it doesn't look as though it's doing anything useful on 32-bit ARM either.

**Comment by fgvanzee** [comment]
@loveshack I've reimplemented the ARM version of `bli_cpuid_query()` in terms of `fopen()` and `fgets()` in 1cfe8e2.

And yes, you are correct: the current implementation of `bli_cpuid_query_id()` doesn't really do much with the results. The reason is that `/proc/cpuinfo` isn't guaranteed to have the information we need in order to discern a CortexA57 from a ThunderX2 from a whatever. If I were an expert at ARM hardware, this would have been done already [1], but this is one of those corners of BLIS for which we are waiting for someone with more ARM expertise and/or access to step up and propose a better solution.

Dave: Notice that things work fine if you configure BLIS to target the correct hardware by selecting the corresponding configuration (e.g. `cortexa57`, `thunderx2`, etc.). The comments above only pertain to the building of a "fat" library that does its CPU detection at runtime.

[1] **Note to industry**: I have access to precisely *zero* ARM-based systems right now. If our industry partners want this to be better supported, those organizations with interests in BLIS on ARM hardware should consider providing us with accounts on their machines.

**Comment by loveshack** [comment]
> And yes, you are correct: the current implementation of
> `bli_cpuid_query_id()` doesn't really do much with the results. The
> reason is that `/proc/cpuinfo` isn't guaranteed to have the
> information we need in order to discern a CortexA57 from a ThunderX2
> from a whatever.

I the current code didn't seem to attempt that anyway, so didn't seem
useful.

> If I were an expert at ARM hardware, this would have
> been done already [1], but this is one of those corners of BLIS for
> which we are waiting for someone with more ARM expertise and/or access
> to step up and propose a better solution.

I don't understand the issue.  I referenced what OpenBLAS does, which
doesn't seem to demand any ARM expertise, though I don't know on which
Linux versions it works.  (I assume it's dependent on Linux support.)

> [1] **Note to industry**: I have access to precisely *zero* ARM-based
> systems right now. If our industry partners want this to be better
> supported, those organizations with interests in BLIS on ARM hardware
> should consider providing us with accounts on their machines.

I've previously used qemu for testing ARM (not aarch64) builds of
something I maintain, which was tolerable on a Sandy Bridge system.  I
don't know whether it's useful for aarch64, but I'd have hoped one of
the ThunderX2 sites would provide access, especially if you show BLIS
beating the proprietary BLAS.  I could ask in the UK, but it's probably
easier for you in the US.  I think ARM have a proprietary emulator too,
but I haven't paid attention.

**Comment by jlinford** [comment]
@fgvanzee @loveshack, here's how to get an account on two of my favorite Arm HPC systems:
- Isambard: Cray XC50 with ThunderX2 CPUs.  In production, open to all, and currently being used for real science, e.g. drug development.  Contact Professor Simon McIntosh-Smith at cssnmis@bristol.ac.uk to request an account.
- Catalyst: 12,000 ThunderX2 cores available at three university sites.  Join the Catalyst user group at https://arm-hpc.groups.io/g/catalyst and post a message to request system access.

You very much *can* discern a CortexA57 from a ThunderX2 from a whatever via /proc/cpuinfo.  `lscpu` is patched on recent Linux distros, but if you're using an older distro you can use this https://github.com/karelzak/util-linux/pull/564/files.

**Comment by loveshack** [comment]
> @fgvanzee @loveshack, here's how to get an account on two of my
> favorite Arm HPC systems:
> - Isambard: Cray XC50 with ThunderX2 CPUs.  In production, open to
> all, and currently being used for real science, e.g. drug development.
> Contact Professor Simon McIntosh-Smith at cssnmis@bristol.ac.uk to
> request an account.

I don't think that's right now; I've talked to a Bristol support person
recently.  See
https://gw4-isambard.github.io/docs/user-guide/requestaccount.html,
which demands a PI/project, and I've no idea on the rules for foreign
users.

> - Catalyst: 12,000 ThunderX2 cores available at three university
> sites.  Join the Catalyst user group at
> https://arm-hpc.groups.io/g/catalyst and post a message to request
> system access.

I don't know about the others, but at least EPCC's isn't generally
available (and there are conditions on potential access that may not be
appropriate).  I have access to a local system anyhow.

> You very much *can* discern a CortexA57 from a ThunderX2 from a
> whatever via /proc/cpuinfo.

Yes (presumably modulo Linux version), and also under /sys, but you
surely shouldn't do it via the filesystem.  Anyhow, I implemented the
selection (similarly to OpenBLAS) pending more testing and understanding
exactly how families are supposed to work in BLIS.  (I'm looking at a
strange checkblas error.)

I don't know the equivalent for arm32 (though the data do appear in
cpuinfo in Fedora), or the best fallbacks for other likely arch64
μ-arches like thunderx1.

**Comment by isuruf** [comment]
@fgvanzee, you can get access to the gcc compile farm. List at https://cfarm.tetaneutral.net/machines/list/ . Registration form https://cfarm.tetaneutral.net/users/new/

**Comment by fgvanzee** [comment]
@isuruf Thanks for pointing this out, Isuru.

**Comment by loveshack** [comment]
I should have referenced #344 for the arm64 implementation and comments
on arm32.

(I'm not very interested in the arm32 implementation, and it would be
best if someone can say how to without reading /proc.  Also I only have
access to cortexa9 for actual arm32.)

**Comment by jeffhammond** [comment]
@loveshack What is the issue with reading `/proc`?  Everything I can find suggests that this is the best method for querying ARM CPUs (e.g. https://en.wikichip.org/wiki/arm/armv8#ARMv8_Extensions_and_Processor_Features).  Furthermore, when other sources exist, they appear to be inaccessible from userspace (e.g. https://www.kernel.org/doc/Documentation/arm64/cpu-feature-registers.txt).

**Comment by loveshack** [comment]
> @loveshack What is the issue with reading `/proc`?

I don't think it's fundamentally wrong if you don't have a better
option.  A cpuid-like mechanism (as suggested by Linux and IBM doc) seems
generally better to me.

* You don't rely on undocumented (?) formats.  (But the ARM /sys files don't
  have that issue.)
* /proc isn't guaranteed to be mounted or accessible.  (Yes, plenty will
  break if not -- it was in my old node health checks.).
* Not relevant one-off, as in this case, but reading /proc
  isn't necessarily cheap, as I've found in other cases.
* I'd generally avoid i/o when possible, but it's more work anyhow to
  read and parse files.

> Everything I can
> find suggests that this is the best method for querying ARM CPUs
> (e.g. https://en.wikichip.org/wiki/arm/armv8#ARMv8_Extensions_and_Processor_Features).
> Furthermore, when other sources exist, they appear to be inaccessible
> from userspace
> (e.g. https://www.kernel.org/doc/Documentation/arm64/cpu-feature-registers.txt).

The relevant register is available to userspace as that reference says
-- noted in my changes, which were tested on A72 and ThunderX1.
OpenBLAS has similar code in production.  The ThunderX2 I can access was
installed with Ubuntu, for some reason, whose gcc fails building BLIS,
but I may try to get on Isambard sometime.  I haven't asked the
Furber/Goodacre ARMy here about access to other hardware, but there
probably isn't any point without doing tuning work for it.

Reading /proc may be necessary on arm32 -- I don't know.  See comments
in the code if someone cares.  (Just avoid popen!)

[I can only test the equivalent ppc64le implementation on POWER8
currently.]

**Comment by loveshack** [comment]
If you need convincing, this is on a Fedora 29 KVM instance on
ThunderX1.  Similarly on non-virtualized Ubuntu 18.04 on ThunderX2.

```
[loveshack@aarch64-test02 ~][PROD]$ head /proc/cpuinfo
processor	: 0
BogoMIPS	: 200.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer	: 0x43
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0x0a1
CPU revision	: 1

processor	: 1
[loveshack@aarch64-test02 ~][PROD]$ cat /sys/devices/system/cpu/cpu0/regs/identification/midr_el1 
0x00000000431f0a11
[loveshack@aarch64-test02 ~][PROD]$ cat cpuid.c
#include <asm/hwcap.h>
#include <stdio.h>
#include <sys/auxv.h>

#define get_cpu_ftr(id) ({                                    \
              unsigned long __val;                            \
              asm("mrs %0, "#id : "=r" (__val));              \
              printf("%-20s: 0x%016lx\n", #id, __val);        \
      })

int main(void)
{

      if (!(getauxval(AT_HWCAP) & HWCAP_CPUID)) {
              fputs("CPUID registers unavailable\n", stderr);
              return 1;
      }

      get_cpu_ftr(ID_AA64ISAR0_EL1);
      get_cpu_ftr(ID_AA64ISAR1_EL1);
      get_cpu_ftr(ID_AA64MMFR0_EL1);
      get_cpu_ftr(ID_AA64MMFR1_EL1);
      get_cpu_ftr(ID_AA64PFR0_EL1);
      get_cpu_ftr(ID_AA64PFR1_EL1);
      get_cpu_ftr(ID_AA64DFR0_EL1);
      get_cpu_ftr(ID_AA64DFR1_EL1);

      get_cpu_ftr(MIDR_EL1);
      get_cpu_ftr(MPIDR_EL1);
      get_cpu_ftr(REVIDR_EL1);

#if 0
      /* Unexposed register access causes SIGILL */
      get_cpu_ftr(ID_MMFR0_EL1);
#endif

      return 0;
}
[loveshack@aarch64-test02 ~][PROD]$ cc cpuid.c && ./a.out
ID_AA64ISAR0_EL1    : 0x0000000000011120
ID_AA64ISAR1_EL1    : 0x0000000000000000
ID_AA64MMFR0_EL1    : 0x00000000ff000000
ID_AA64MMFR1_EL1    : 0x0000000000000000
ID_AA64PFR0_EL1     : 0x0000000000000011
ID_AA64PFR1_EL1     : 0x0000000000000000
ID_AA64DFR0_EL1     : 0x0000000000000006
ID_AA64DFR1_EL1     : 0x0000000000000000
MIDR_EL1            : 0x00000000431f0a11
MPIDR_EL1           : 0x0000000080000000
REVIDR_EL1          : 0x0000000000000000
[loveshack@aarch64-test02 ~][PROD]$ 
```

**Comment by loveshack** [comment]
Concerning cpuid-like mechanisms versus reading /proc, I should have mentioned that presumably you need to ensure you use the right cpuinfo entry for the processor you're actually running on in case of heterogeneous hardware. That may only be an issue in the ARM world currently and I don't know how relevant it is outside phones.  (I _assume_ cpuid-like things report the core they're run on...)

Anyhow, in the absence of something better, I added arm32 to #344 using /proc/cpuinfo (with a fixme).

**Comment by devinamatthews** [comment]
Looks like the original issue (`popen`) is fixed.

**Comment by jeffhammond** [comment]
I'm not sure if it matters, but this is what Isambard TX2 looks like:

```
-----------------------------------------------------------
  GW4 Isambard "XCI" - Cray XC50 Arm/ThunderX2
  Login node: xcil00
-----------------------------------------------------------

xcil00:~> uname -a
Linux xcil00 4.12.14-150.17_5.0.90-cray_ari_s #1 SMP Tue Apr 28 21:17:03 UTC 2020 (3e6e478) aarch64 aarch64 aarch64 GNU/Linux

xcil00:~> lscpu
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              256
On-line CPU(s) list: 0-255
Thread(s) per core:  4
Core(s) per socket:  32
Socket(s):           2
NUMA node(s):        2
Model:               2
BogoMIPS:            400.00
NUMA node0 CPU(s):   0-31,64-95,128-159,192-223
NUMA node1 CPU(s):   32-63,96-127,160-191,224-255
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics cpuid asimdrdm

xcil00:~> cat /proc/cpuinfo
processor	: 0
BogoMIPS	: 400.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics cpuid asimdrdm
CPU implementer	: 0x43
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0x0af
CPU revision	: 2
...
```
