### ISSUE TITLE
CSR SPMV

### ISSUE THREAD

**Issue by tks2004** [flame/blis#336]
Does BLIS support CSR SPMV operations?

**Comment by fgvanzee** [comment]
@tks2004 Could you clarify what you mean by CSR? I'm not immediately familiar with the term. Come to think of it, it's not clear what you mean by SPMV, either.

**Comment by devinamatthews** [comment]
CSR == compressed sparse row (i.e. store list of non-zero (i,m_ij) pairs for each j)
SPMV == sparse gemv

**Comment by fgvanzee** [comment]
@devinamatthews Ah, thanks for that.
@tks2004 The answer, unfortunately, is no. BLIS does not currently offer any sparse operations. Perhaps @rvdg can suggest where to look for such implementations?

**Comment by rvdg** [comment]
Victor Eijkhout would be the person to ask.

**Comment by jeffhammond** [comment]
I am closing this issue because the question was answered by Field already.
