### ISSUE TITLE
checkblas failure for cortexa53

### ISSUE THREAD

**Issue by loveshack** [flame/blis#341]
I'm puzzled by this and don't have the enthusiasm to debug it, but thought I should at least record it.

I built for the cortexa53 target on aarch64, and make checkblas failed with the errors below. However, the full blis test succeeded.  This was on a thunderx1 KVM VM with gcc 8.3.1 under Fedora 29.  It also fails if I build the Fortran version directly.

However, the test passes doing the same thing on a cortexa72 VM ("Amazon Linux 2") with gcc 7.3.1 (Red Hat 7.3.1-5).

```
 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
                       EXPECTED RESULT                    COMPUTED RESULT
       1  (    .167333    ,    .442557    )  (    .167333    ,    .442557    )
       2  (    .217320    ,    .108337    )  (    .217320    ,    .108337    )
       3  (    .329789    ,   -.166362E-01)  (    .329789    ,   -.166362E-01)
       4  (    .250089    ,   -.910139E-01)  (   -.609890E+10,   -.275225E+10)
       5  (    .796754    ,   -.565034E-01)  (    .796754    ,   -.565034E-01)
 ******* CTBMV  FAILED ON CALL NUMBER:
    747: CTBMV ('L','N','U',  5,  4, A,  6, X, 2)                               .

 CTPMV  PASSED THE TESTS OF ERROR-EXITS

 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
                       EXPECTED RESULT                    COMPUTED RESULT
       1  (    .686813    ,   -.156843    )  (    .686813    ,   -.156843    )
       2  (   -.101935    ,    .100522    )  (   -.101935    ,    .100522    )
       3  (   -.365189E-01,    .520084E-01)  (   -.365189E-01,    .520084E-01)
       4  (    .305346    ,    .135281    )  (   -.529970E+10,    .843656E+10)
       5  (    .884216    ,    .264764    )  (    .884216    ,    .264764    )
 ******* CTPMV  FAILED ON CALL NUMBER:
    171: CTPMV ('L','N','U',  5, AP, X, 2)                                      .


 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
                       EXPECTED RESULT                    COMPUTED RESULT
       1  (    .749251E-02,    .242757    )  (   -32.3105    ,    128.059    )
       2  (     .00000    ,     .00000    )  (    .349610E-01,   -.424232    )
       3  (    .167333    ,    .306693    )  (   -.229271E+10,   -.484016E+10)
       4  (    .796703    ,    .298701    )  (    .796703    ,    .298701    )
       5  (    .127373    ,   -.356643    )  (    .127373    ,   -.356643    )
 ******* CTBSV  FAILED ON CALL NUMBER:
    723: CTBSV ('U','N','U',  5,  4, A,  6, X, 2)                               .

 CTPSV  PASSED THE TESTS OF ERROR-EXITS

 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
                       EXPECTED RESULT                    COMPUTED RESULT
       1  (    .926573    ,   -.356643    )  (    .160330    ,    .189820    )
       2  (     .00000    ,     .00000    )  (    .683755E-01,    .389953E-01)
       3  (    .117383    ,    .498502    )  (   -.271229E+10,   -.426074E+10)
       4  (    .247253    ,    .429570E-01)  (    .247253    ,    .429570E-01)
       5  (    .774226E-01,   -.348651    )  (    .774226E-01,   -.348651    )
 ******* CTPSV  FAILED ON CALL NUMBER:
    147: CTPSV ('U','N','U',  5, AP, X, 2)                                      .
```

**Comment by fgvanzee** [comment]
I know I sound like a broken record on this topic, but this behavior may be the result of a bug in gcc--specifically, in version 8.3.x. We've observed this (or a similar) failure in the packed level-2 BLAS operations in enough contexts--and all of them *only recently*--that I think the odds of it being a compiler problem are higher than normal.

**Comment by dnparikh** [comment]
Could these numerical errors be related to the fact that ARM's NEON is not fully compliant to IEEE floating point? I've had some experience where NEON was causing numerical issues in the BLAS testsuite.

**Comment by loveshack** [comment]
> Could these numerical errors be related to the fact that ARM's NEON is
> not fully compliant to IEEE floating point? I've had some experience
> where NEON was causing numerical issues in the BLAS testsuite.

I don't think it's Neon-specific.  -funsafe-math-optimizations is used
generally, and this error occurs with other targets using the generic
micro-kernel.  (Neon is used anyhow in BLIS and OpenBLAS, and I assumed
the vectorization that should be enabled by -funsafe-math-optimizations
would be wanted for ARM.)

Note that this is specifically in the BLAS interface.  The blis
interface test suite passes in the cases I've tried.

**Comment by loveshack** [comment]
Duplicate of an unresolved part of #329.

**Comment by loveshack** [comment]
I should have asked if there's a relevant gcc bug report about gcc 8.3, but see the comments about compilers in #342.
