### ISSUE TITLE
Possily-incomplete make showconfig output

### ISSUE THREAD

**Issue by loveshack** [flame/blis#347]
If I configure for the arm64 family I added and use make showconfig, I get this output:
```
configuration family:    arm64
sub-configurations:      thunderx2 cortexa57 cortexa53 generic
requisite kernels sets:  armv8a generic
kernel-to-config map:    armv8a:thunderx2 generic:generic
```
i.e. the map doesn't show all the sub-configs.  Is it supposed to show only the one non-generic kernel?
It's probably not important, and I haven't investigated.

**Comment by fgvanzee** [comment]
@loveshack The above output seems correct to me. Your concern probably stems from some nuance to the kernel-to-config map that you probably aren't aware of. It's not trying to map a kernel set to *every* subconfiguration; rather, it's trying to map *every* kernel set (in the requisite kernel sets) to *one* subconfiguration (of the subconfigurations implied by the family). For umbrella families that contain several subconfigurations, some subconfigs will not go un-mapped-to. This is normal.
