### ISSUE TITLE
allow environment to select family members 

### ISSUE THREAD

**Issue by loveshack** [flame/blis#350]
OpenBLAS has a facility that's sometimes useful to bypass cpuid-type runtime selection to select the architecture.
I implemented that under #345 (for BLIS_CORETYPE, rather than OPENBLAS_CORETYPE) but I don't know where best to document it.
(I'm afraid I've accumulated several features in that branch as they're inter-dependent.)

**Comment by devinamatthews** [comment]
@loveshack thanks for all the stuff in #345 (I'm cranking through the issues and I'll get to the PRs in a bit). Since there is a number of different things in there, though, would it be possible to split it into multiple independent PRs? I might recomment this later.

**Comment by loveshack** [comment]
> @loveshack thanks for all the stuff in #345 (I'm cranking through the
> issues and I'll get to the PRs in a bit). Since there is a number of
> different things in there, though, would it be possible to split it
> into multiple independent PRs? I might recomment this later.

It wasn't possible to separate the concerns, and it's all mixed up,
unfortunately.  I was working on incorporating changes for Fedora and
other things, but now I have to merge against more conflicts because the
repo has changed under me.  Damn github.  I could do something with some
assurance that it will get dealt with reasonably timely and not have to
wait a year between iterations.
