### ISSUE TITLE
banish non-use warning generates warning with XLC

### ISSUE THREAD

**Issue by jeffhammond** [flame/blis#356]
@fgvanzee I don't care about this warning, but since it seems your goal is to banish warnings, you should know that the attempt to do so here has the opposite effect with XLC
```sh
blastest/f2c/lread.c:353:4: warning: explicitly assigning value of variable of type 'FILE *' (aka 'struct _IO_FILE *') to itself [-Wself-assign]
        f = f;  /* banish non-use warning */
        ~ ^ ~
```
If you are unconcerned by this, feel free to close the issue.

**Comment by fgvanzee** [comment]
I'll look at a patch to avoid the warning. Thanks.

**Comment by devinamatthews** [comment]
```C
(void)unused;
```
Is the idiomatic way I think.

**Comment by fgvanzee** [comment]
I agree with @devinamatthews.
