### ISSUE TITLE
POWER9: 1500-065: (S) Too many registers are required in the asm statement.

### ISSUE THREAD

**Issue by jeffhammond** [flame/blis#357]
@nicholaiTukanov 

I see the following error when I build the test suite.
```
      57  1500-065: (S) Too many registers are required in the asm statement.
1586-346 (U) An error occurred during code generation.  The code generation return code was 1.
make: *** [obj/power9/kernels/power9/3/bli_gemm_power9_asm_d12x6.o] Error 1
make: *** Waiting for unfinished jobs....
```

The configuration was as follows.
```sh
./configure -p $HOME/BLIS/power9-seq -t no CC=xlc_r power9
```

**Comment by fgvanzee** [comment]
@jeffhammond I happen to know what's going on here, so I'll chime in ahead of Nicholai's comment.

Basically, as the commit log entry suggests, you can't use `xlc`. The compiler has issues with recognizing the use of certain general-purpose registers in the GNU extended inline assembly clobber list. Please use `gcc` instead, kthnx.

**Comment by jeffhammond** [comment]
Works for me.  I have no affection for XLC.
