### ISSUE TITLE
POWER9: blacklist GCC 4.8.5

### ISSUE THREAD

**Issue by jeffhammond** [flame/blis#358]
The default version of GCC in certain Linux distributions is too old to build the POWER9 kernels.  I recall BLIS has a blacklist like this for e.g. Haswell.  It should be applied to POWER9 as well.
```sh
gcc: note: valid arguments to ‘-mcpu=’ are: 401 403 405 405fp 440 440fp 464 464fp 476 476fp 505 601 602 603 603e 604 604e 620 630 740 7400 7450 750 801 821 823 8540 8548 860 970 G3 G4 G5 a2 cell e300c2 e300c3 e500mc e500mc64 e5500 e6500 ec603e native power3 power4 power5 power5+ power6 power6x power7 power8 powerpc powerpc64 powerpc64le rs64 titan
gcc: error: unrecognized argument in option ‘-mtune=power9’
```
I will try to work on this but make no commitments.

**Comment by fgvanzee** [comment]
I agree that we should blacklist compiler versions. I'll need to forensically track the power9 support through the gcc version history and insert the appropriate logic.

**Comment by jeffhammond** [comment]
I am working on this...

**Comment by jeffhammond** [comment]
I am trying to figure out if GCC-5 supports POWER9 but https://www.olcf.ornl.gov/wp-content/uploads/2018/12/summit_workshop_walkup.pdf recommends GXX 6.4 and 8.1.  The GCC 5.5.0 compiler build is more complicated than later versions.

**Comment by fgvanzee** [comment]
Alright, you can have this one. :) Thanks for your help, Jeff.

**Comment by jeffhammond** [comment]
I am giving up on building GCC 5.5.0 and will set the minimum version for POWER9 to GCC-6.

**Comment by devinamatthews** [comment]
Unlike certain compilers *coughclangcough* the GCC documentation should specify the available mcpu/march options, right? It's pretty easy to go through the documentation by version--just pick a past version, go to the right page, and then edit the url.

**Comment by jeffhammond** [comment]
@devinamatthews I looked.  GCC docs were reorganized between version 5 and 7, so it wasn't easy to find.  Feel free to update https://github.com/flame/blis/pull/360 once you find the answer.

**Comment by fgvanzee** [comment]
What Jeff said. So... *almost* that easy. :)

**Comment by devinamatthews** [comment]
I change my vote to gcc 6 :smile:.

**Comment by jeffhammond** [comment]
https://gcc.gnu.org/onlinedocs/gcc-5.5.0/gcc/RS_002f6000-and-PowerPC-Options.html#RS_002f6000-and-PowerPC-Options indicates no POWER9 support in GCC-5.  I had to manually navigate to this page because Google can't find it.

**Comment by jeffhammond** [comment]
> Unlike certain compilers coughclangcough the GCC documentation should specify the available mcpu/march options, right?

If this is a comment on ICC, `icc -help codegen` always lists the supported processors in the context of the `-x` options.

**Comment by devinamatthews** [comment]
*coughclangcough* as in "making users read the source code is sufficient documentation".
