### ISSUE TITLE
functions defined in header (or default visibility problem in shared library?)

### ISSUE THREAD

**Issue by kyungminlee** [flame/blis#366]
It seems that the default visibility is hidden after https://github.com/flame/blis/issues/304. The problem, however, is that some `blis.h` *defines* a number of functions which call the internal functions (e.g. `bli_thread_obroadcast` calls `bli_thrcomm_bcast`), and this causes link error when using shared library.

For example, with blis built with `./configure --enable-cblas haswell` compiling the following `blistest.c` produces the following error.
```c
#include "blis.h"
int main(void) {
    double A[6] = {1.0, 2.0, 1.0, -3.0, 4.0, -1.0}, B[9];
    cblas_dgemm(CblasColMajor, CblasNoTrans, CblasTrans, 3, 3, 2, 1, A, 3, A, 3, 2, B, 3);
    return 0;
}
```
```
$ gcc -o blistest blistest.c -Llib/haswell -Iinclude/haswell -lblis -lm
/tmp/cciOH0kz.o: In function `bli_thread_obroadcast':
blistest.c:(.text+0xef01): undefined reference to `bli_thrcomm_bcast'
/tmp/cciOH0kz.o: In function `bli_thread_obarrier':
blistest.c:(.text+0xef29): undefined reference to `bli_thrcomm_barrier'
/tmp/cciOH0kz.o: In function `bli_thread_range_jrir_sl':
blistest.c:(.text+0xefcc): undefined reference to `bli_thread_range_sub'
collect2: error: ld returned 1 exit status
```
Either the functions need to be compiled into the library, or the default visibility should be set to all?

**Comment by fgvanzee** [comment]
Thanks for pointing this out, @kyungminlee, and for the example code. I was indeed able to reproduce the problem.

My preferred solution is that the functions be annotated for export so that they are always compiled into the shared library. I've committed fe2560a, which hopefully fixes this bug.

Please let us know if you encounter any further difficulties.

**Comment by kyungminlee** [comment]
Your solution seems to work well. Thanks

**Comment by vkirangoud** [comment]
Similar issue is encountered again when dgemm sup is added. 
I get this error "in function `bli_gemmsup_ref_var1n2m_opt_cases'
test_blas.c:(.text+0x116b8): undefined reference to `bli_abort'"

this error got resolved if we make bli_abort() visible using BLIS_EXPORT_BLIS.

**Comment by fgvanzee** [comment]
@vkirangoud I don't quite follow how I would reproduce your issue. But if you can help me reproduce the linker error by providing further details, I'll fix it.
