### ISSUE TITLE
False result from cblas_sdsdot

### ISSUE THREAD

**Issue by ACSimon33** [flame/blis#367]
I encountered a small bug in the CBLAS compatibility layer with the cblas_sdsdot routine.
The routine should compute the dot product and add the scalar alpha:

<pre>dot <- alpha + x^T * y</pre>

But the routine actually adds the scalar alpha twice. The bug is in the following routine:
(frame/compat/cblas/f77_sub/f77_dot_sub.c)

<pre>void PASTEF772(sds,dot,sub) 
    (
        const f77_int* n,
        const float*  sb,
        const float*   x, const f77_int* incx,
        const float*   y, const f77_int* incy,
        float*   rval
    )
{
    *rval = *sb + PASTEF77(sds,dot)
        (
	   n,
	   sb,
	   x, incx,
	   y, incy
        );
}</pre>

This line:
<pre>*rval = *sb + PASTEF77(sds,dot)</pre>
passes the call onto the BLAS layer version of sdsdot but then continues to add the scalar nevertheless.

So either the call has to be mapped onto PASTEF77(**ds**,dot):
<pre>*rval = *sb + (float) PASTEF77(ds,dot)</pre>
OR the addition of the scalar has to be omitted:
<pre>*rval = PASTEF77(sds,dot)</pre>

**Comment by devinamatthews** [comment]
@fgvanzee To get the correct rounding we would need either the second option `*rval = PASTEF77(sds,dot)` or something like this:

```
*rval = (double) *sb + PASTEF77(ds,dot)
```
right?

**Comment by ACSimon33** [comment]
You are right. Then there is actually another bug in the BLAS layer:

<pre>
float PASTEF77(sd,sdot)
     (
       const f77_int* n,
       const float*   sb,
       const float*   x, const f77_int* incx,
       const float*   y, const f77_int* incy
     )
{
	float r = ( float )PASTEF77(d,sdot)( n,
	                                     x, incx,
	                                     y, incy );
	return r + *sb;
}
<pre/>

**Comment by fgvanzee** [comment]
@ACSimon33 Thank you for bringing this bug to our attention! We're happy to fix it.

However, I'm a having a little trouble following all of the different proposed options to fix the (now multiple) bug(s). I defer to you and Devin to choose the option that is "best." You can submit via a PR, or simply spell out exactly what lines you want me to change.

**Comment by ACSimon33** [comment]
@devinamatthews @fgvanzee My suggestion is to change the BLAS layer routine to:

<pre>
float PASTEF77(sd,sdot)
    (
        const f77_int* n,
        const float*   sb,
        const float*   x, const f77_int* incx,
        const float*   y, const f77_int* incy
    )
    {
	double r = ( double ) *sb + PASTEF77(ds,dot)( n,
	                                              x, incx,
	                                              y, incy );
	return ( float ) r;
    }
</pre>
(frame/compat/bla_dot.c line 96)

And for the CBLAS layer routine I would change the subroutine to:

<pre>
void PASTEF772(sds,dot,sub) 
    (
        const f77_int* n,
        const float*  sb,
        const float*   x, const f77_int* incx,
        const float*   y, const f77_int* incy,
        float*   rval
    )
    {
        *rval = PASTEF77(sds,dot)( n,
                                   sb
	                           x, incx,
	                           y, incy );
    }
</pre>
(frame/compat/cblas/f77_sub/f77_dot_sub.c line 69)

**Comment by fgvanzee** [comment]
@ACSimon33 Thanks for that summary; I can do that. I'll let @devinamatthews comment before I proceed, though.

**Comment by devinamatthews** [comment]
Looks good to me except that the temporary in `frame/compat/bla_dot.c` is not necessary, you can just return the expression that it is assigned to directly.

**Comment by fgvanzee** [comment]
@ACSimon33 Please take a look at 5271107 and confirm that it fixes the two bugs.

**Comment by ACSimon33** [comment]
@fgvanzee Thanks. Works perfectly.
