### ISSUE TITLE
Ice Lake client

### ISSUE THREAD

**Issue by jeffhammond** [flame/blis#369]
I measured on a pre-production part so I won't publish the numbers, but I've tested BLIS on Ice Lake client (supports AVX-512) and find that the SKX config performs better than the Haswell one nearly all of the time, when the SKX config has an optimized version.  When SKX lacks an optimized implementation, the Haswell config performs much better.

This is interesting, because this CPU has one 512-bit FMA port.  However, the power behavior on Ice Lake is improved (see https://software.intel.com/sites/default/files/managed/9e/bc/64-ia-32-architectures-optimization-manual.pdf section 2.1.1.5 for details).

I will work on an Ice Lake client config later.

https://github.com/flame/blis/issues/368 applies here.

**Comment by devinamatthews** [comment]
Closed in favor of #415.
