### ISSUE TITLE
What are the difference between blis-sup and blis-conv? Is the micro - kernel?

### ISSUE THREAD

**Issue by lingweiyang** [flame/blis#376]

**Comment by fgvanzee** [comment]
@lingweiyang If I understand your question correctly, the answer may be found (at least in part) in the [General Information](https://github.com/flame/blis/blob/master/docs/PerformanceSmall.md#general-information) section of the [PerformanceSmall.md](https://github.com/flame/blis/blob/master/docs/PerformanceSmall.md) document:

> The legend in each graph contains two entries for BLIS, corresponding to the two black lines, one solid and one dotted. The dotted line, **"BLIS conv"**, represents the conventional implementation that targets large matrices. This was the only implementation available in BLIS prior to the addition to the small/skinny matrix support. The solid line, **"BLIS sup"**, makes use of the new small/skinny matrix implementation for certain small problems.

These two different implementations do in fact use different sets of microkernels. The conventional implementation always packs matrices A and B, and therefore its microkernel is rather simple. The small/skinny implementation, however, does not require matrices A and B to be packed (though it allows this if an expert user requests it), and therefore its microkernel framework is necessarily more sophisticated.

**Comment by lingweiyang** [comment]
Thanks for your answer! Is blis-sup's micro-kernel code open source?

**Comment by lingweiyang** [comment]
Thank you for your answer. What is the difference between bli_gemmsup_rd_haswell_asm_d6x8.c and bli_gemmsup_rv_haswell_asm_d6x8.c?

> @lingweiyang If I understand your question correctly, the answer may be found (at least in part) in the [General Information](https://github.com/flame/blis/blob/master/docs/PerformanceSmall.md#general-information) section of the [PerformanceSmall.md](https://github.com/flame/blis/blob/master/docs/PerformanceSmall.md) document:
> 
> > The legend in each graph contains two entries for BLIS, corresponding to the two black lines, one solid and one dotted. The dotted line, **"BLIS conv"**, represents the conventional implementation that targets large matrices. This was the only implementation available in BLIS prior to the addition to the small/skinny matrix support. The solid line, **"BLIS sup"**, makes use of the new small/skinny matrix implementation for certain small problems.
> 
> These two different implementations do in fact use different sets of microkernels. The conventional implementation always packs matrices A and B, and therefore its microkernel is rather simple. The small/skinny implementation, however, does not require matrices A and B to be packed (though it allows this if an expert user requests it), and therefore its microkernel framework is necessarily more sophisticated.

**Comment by lingweiyang** [comment]
Thank you for your answer. Are there any other differences besides micro-kernel? Are the parameters of blis-sup's micro-kernel a,b, and c the whole matrix or a partial matrix?

**Comment by lingweiyang** [comment]
> @lingweiyang如果我正确理解您的问题，则可以（至少部分）在[PerformanceSmall.md](https://github.com/flame/blis/blob/master/docs/PerformanceSmall.md)文档的“ [常规信息”](https://github.com/flame/blis/blob/master/docs/PerformanceSmall.md#general-information)部分中找到答案：[](https://github.com/flame/blis/blob/master/docs/PerformanceSmall.md)
> 
> > 每个图形中的图例包含两个BLIS条目，分别对应于两条黑线，一条为实线，一条为虚线。虚线**“ BLIS conv”**表示针对大型矩阵的常规实现。这是在添加小型/骨感矩阵支持之前，BLIS中唯一可用的实现。实线**“ BLIS sup”**对某些小问题使用了新的小/瘦矩阵实现。
> 
> 这两种不同的实现实际上确实使用了不同的微内核集。传统的实现总是打包矩阵A和B，因此其微内核相当简单。但是，小型/瘦的实现不需要打包矩阵A和B（尽管如果专家用户要求，也可以打包矩阵），因此其微内核框架必定会更加复杂。

**Comment by lingweiyang** [comment]
> @lingweiyang如果我正确理解您的问题，则可以（至少部分）在[PerformanceSmall.md](https://github.com/flame/blis/blob/master/docs/PerformanceSmall.md)文档的“ [常规信息”](https://github.com/flame/blis/blob/master/docs/PerformanceSmall.md#general-information)部分中找到答案：[](https://github.com/flame/blis/blob/master/docs/PerformanceSmall.md)
> 
> > 每个图形中的图例包含两个BLIS条目，分别对应于两条黑线，一条为实线，一条为虚线。虚线**“ BLIS conv”**表示针对大型矩阵的常规实现。这是在添加小型/骨感矩阵支持之前，BLIS中唯一可用的实现。实线**“ BLIS sup”**对某些小问题使用了新的小/瘦矩阵实现。
> 
> 这两种不同的实现实际上确实使用了不同的微内核集。传统的实现总是打包矩阵A和B，因此其微内核相当简单。但是，小型/瘦的实现不需要打包矩阵A和B（尽管如果专家用户要求，也可以打包矩阵），因此其微内核框架必定会更加复杂。

Thank you for your answer. Are there any other differences besides micro-kernel? Are the parameters of blis-sup's micro-kernel a,b, and c the whole matrix or a partial matrix?

**Comment by fgvanzee** [comment]
> Thank you for your answer. Are there any other differences besides micro-kernel?

There are some other differences, but they are rather technical and go beyond the scope of a GitHub issue to discuss.

>  Are the parameters of blis-sup's micro-kernel a,b, and c the whole matrix or a partial matrix?

The BLIS sup microkernels operate on submatrices (what we call "micropanels"), just as the conventional microkernel does. The difference is in the assumed storage format of those micropanels.
