### ISSUE TITLE
Probable error in thread partition function void bli_thread_partition_2x2()

### ISSUE THREAD

**Issue by kvaragan** [flame/blis#377]
In the file frame/thread/bli_thread.c at line no 1060. 
```c
// Return early small prime numbers of threads.
if ( n_thread < 4 )
{
    *nt1 = ( work1 >= work2 ? n_thread : 1 );
    *nt2 = ( work1 <  work2 ? n_thread : 1 );
}
```
Are we missing the "return" statement here...

**Comment by fgvanzee** [comment]
@kvaragan Good catch, Kiran. Thank you for this report. I have submitted a fix to the `amd` branch (commit 9f3a8d4).
