### ISSUE TITLE
Should cblas files be using same includes as Fortran blas compat files?

### ISSUE THREAD

**Issue by tkelman** [flame/blis#38]
Compare:
https://github.com/flame/blis/blob/0b126de1342c11c65623bcb38e258e21e9244e3d/frame/compat/bla_gemm.c#L35

vs
https://github.com/flame/blis/blob/0b126de1342c11c65623bcb38e258e21e9244e3d/frame/compat/cblas/src/cblas_dgemm.c#L1-L4

**Comment by tkelman** [comment]
Sorry wrong button, posted this before it was complete, here's the rest:

`blis.h` does include `bli_config_macro_defs.h`, but the cblas files currently do not. `bli_type_defs.h` defaults to `typedef long int f77_int` if `BLIS_BLAS2BLIS_INT_TYPE_SIZE` is not defined yet, whereas `bli_config_macro_defs.h` always sets `BLIS_BLAS2BLIS_INT_TYPE_SIZE` to 64. On 64 bit Windows, `long int` is 32 bits, leading to segfaults when I try to call cblas functions and the integer sizes don't match. For now I can fix this by manually modifying all the `bli_config.h` files to `#define BLIS_BLAS2BLIS_INT_TYPE_SIZE 64`, but I think making the cblas includes consistent with the Fortran blas should make this no longer necessary.

**Comment by fgvanzee** [comment]
@tkelman, it seems there are two ways to fix this. Please confirm whether you agree or not.
1. Add `#include "bli_config_macro_defs.h"` (after `#include "bli_config"`) to each `cblas_*.c` file. This would allow `bli_config.h` the opportunity to define `BLIS_BLAS2BLIS_INT_TYPE_SIZE`, and, if it is not defined, it would be defined with the default value.
2. Replace the outer four `#include` statements in each `cblas_*.c` file with `#include "blis.h"`. This accomplishes the same thing as above, and makes the files syntactically similar to the corresponding files that define the BLAS compatibility layer (ie: `compat/bla_*.c`). 
There was probably a reason why I did the piecemeal `#include` approach that currently exists in the `cblas_*.c` files, I just can't remember what that reason would have been.

**Comment by tkelman** [comment]
I believe either of those would fix this issue, yes. Option 2 would be cleaner.

**Comment by fgvanzee** [comment]
@tkelman, I tried option 2 and realized why I had not gone that route to begin with. It has to do with the differing definitions (prototypes) for `xerbla_()` in CBLAS versus the BLAS compatibility layer. This is one of those issues that makes me want to throw something. Anyhow, I ended up going with option 1 and it seems to compile okay. Please test it out (commit f86b94f) and let me know how it works.

**Comment by tkelman** [comment]
At the risk of elevating your blood pressure, what's the xerbla issue? That commit is sufficient to close this issue as far as I'm concerned. You might expect a patch regarding the defaults for integer sizes from some of the numpy maintainers soonish.

**Comment by fgvanzee** [comment]
The function prototype for `xerbla_()` that the BLAS compatibility layer provides (in `compat/f2c/bla_xerbla.h`):
```
  int PASTEF770(xerbla)(character *srname, integer *info, ftnlen srname_len);
```
as well as its corresponding definition (in `compat/f2c/bla_xerbla.c`) differs from the prototype that the CBLAS provides (in `compat/cblas/src/cblas_f77.h`):
```
  void F77_xerbla(FCHAR, void *);
```
