### ISSUE TITLE
BLIS misdetects 2017 MBP

### ISSUE THREAD

**Issue by devinamatthews** [flame/blis#385]
My 2017 MBP is not correctly detected as `haswell` at runtime, although `configure auto` builds the `haswell` kernels. CPU info:

```
machdep.cpu.vendor: GenuineIntel
machdep.cpu.brand_string: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
machdep.cpu.family: 6
machdep.cpu.model: 158
machdep.cpu.extmodel: 9
machdep.cpu.extfamily: 0
machdep.cpu.stepping: 9
```

**Comment by jeffhammond** [comment]
How is it detected at runtime?

**Comment by devinamatthews** [comment]
In theory it is straightforward:

```C
	// Check for expected CPU features.
	const uint32_t expected = FEATURE_AVX  |
	                          FEATURE_FMA3 |
	                          FEATURE_AVX2;

	if ( !bli_cpuid_has_features( features, expected ) ) return FALSE;

	return TRUE;
```

so I don't know that the problem is.

**Comment by jeffhammond** [comment]
Sorry, I meant "what result is obtained from detection, if not Haswell?"

**Comment by devinamatthews** [comment]
I turned on all the printing in bli_cpuid.c and this looks like it might be the problem:

```
fma3: 0
```

I'll have to dig in to the cpuid leaves.

**Comment by devinamatthews** [comment]
Something very odd is up. This code:

```C
print_binary(*features);
print_binary(FEATURE_SSE3);
print_binary(FEATURE_SSSE3);
print_binary(FEATURE_SSE41);
print_binary(FEATURE_SSE42);
print_binary(FEATURE_AVX);
print_binary(FEATURE_FMA3);

fprintf(stderr, "sse3: %d\n", bli_cpuid_has_features(features, FEATURE_SSE3));
fprintf(stderr, "ssse3: %d\n", bli_cpuid_has_features(features, FEATURE_SSSE3));
fprintf(stderr, "sse4.1: %d\n", bli_cpuid_has_features(features, FEATURE_SSE41));
fprintf(stderr, "sse4.2: %d\n", bli_cpuid_has_features(features, FEATURE_SSE42));
fprintf(stderr, "avx: %d\n", bli_cpuid_has_features(features, FEATURE_AVX));
fprintf(stderr, "fma3: %d\n", bli_cpuid_has_features(features, FEATURE_FMA3));
```

Produces this output:

```
0000 0000 0000 0000 0000 0000 0111 1111 
0000 0000 0000 0000 0000 0000 0000 0001 
0000 0000 0000 0000 0000 0000 0000 0010 
0000 0000 0000 0000 0000 0000 0000 0100 
0000 0000 0000 0000 0000 0000 0000 1000 
0000 0000 0000 0000 0000 0000 0001 0000 
0000 0000 0000 0000 0000 0000 0100 0000 
sse3: 0
ssse3: 0
sse4.1: 1
sse4.2: 1
avx: 1
fma3: 0
```

**Comment by devinamatthews** [comment]
OK, this is crazy, but what is actually being checked is not the feature bits themselves, but the *pointer* to the feature bits. I have no idea how this ever "worked".

**Comment by devinamatthews** [comment]
Luckily, the checking the pointer thing only applied to the debugging output which, while very confusing, is not the core issue. I did find something else. After configure with `./configure auto`, both configure and BLIS_ARCH_DEBUG show the active config as `haswell`. When I then edit the files [kernels/zen/1/bli_amaxv_zen_int.c] and [ref_kernels/1/bli_amaxv_ref.c] to print `here zen` and `here ref`, respectively, I get this confusing output:

libblis: selecting sub-configuration 'haswell'.
here ref

from a simple program that just calls `idamax`. Confusingly, same happens after `./configure haswell`. I'm not actually sure *how* I got it to use the vectorized kernel to test #382.

**Comment by fgvanzee** [comment]
> After configure with ./configure auto, both configure and BLIS_ARCH_DEBUG show the active config as haswell. When I then edit the files kernels/zen/1/bli_amaxv_zen_int.c and ref_kernels/1/bli_amaxv_ref.c to print here zen and here ref, respectively, I get this confusing output:

@devinamatthews This is normal. The `haswell` subconfig uses part of the `zen` kernel set. AMD contributed several non-level3 kernels in the `zen` kernel set, but we use them for both `haswell` and `zen` subconfigs (and others).

**Comment by devinamatthews** [comment]
Yes, but isn't haswell supposed to use the zen level 1 kernels, hence #380? Here it uses the reference kernel even though it says it haswell is selected.

**Comment by fgvanzee** [comment]
> Yes, but isn't haswell supposed to use the zen level 1 kernels, hence #380? Here it uses the reference kernel even though it says it haswell is selected.

Yes, but did you not see that I disabled use of the intrinsics `zen` kernel `amaxv` in e186d71? The kernel is still there, but I un-registered it.

**Comment by devinamatthews** [comment]
Ugh. Can you reenable it when you merge #382?

**Comment by devinamatthews** [comment]
Well, given that then this is a false alarm.
