### ISSUE TITLE
BLAS test failed

### ISSUE THREAD

**Issue by hexi03** [flame/blis#387]
Hi, I got it when i do "make check",
OS: Windows64
MSYS2 with GCC: 9.3.0 and bash 4.4.23(2)-release (x86_64-pc-msys)
ryzen 2600x
I did:
./configure zen
make CC='gcc -mavx -march=native -msse4.2' -j 6
make install
*reboot*
make CC='gcc -mavx -march=native -msse4.2' check
and I got something like 
>  ***** ILLEGAL VALUE OF PARAMETER NUMBER  1 NOT DETECTED BY DGEMM  *****

I attached log and out. files with errors(tests with number 1 are passed):
 
[out.cblat2.txt](https://github.com/flame/blis/files/4370509/out.cblat2.txt)
[out.cblat3.txt](https://github.com/flame/blis/files/4370512/out.cblat3.txt)
[out.dblat2.txt](https://github.com/flame/blis/files/4370517/out.dblat2.txt)
[out.dblat3.txt](https://github.com/flame/blis/files/4370519/out.dblat3.txt)
[out.sblat2.txt](https://github.com/flame/blis/files/4370521/out.sblat2.txt)
[out.sblat3.txt](https://github.com/flame/blis/files/4370522/out.sblat3.txt)
[out.zblat2.txt](https://github.com/flame/blis/files/4370523/out.zblat2.txt)
[out.zblat3.txt](https://github.com/flame/blis/files/4370524/out.zblat3.txt)
[output.testsuite.txt](https://github.com/flame/blis/files/4370525/output.testsuite.txt)

[make.txt](https://github.com/flame/blis/files/4370487/make.txt)
[make install.txt](https://github.com/flame/blis/files/4370490/make.install.txt)
[make check.txt](https://github.com/flame/blis/files/4370530/make.check.txt)
[configure_log.txt](https://github.com/flame/blis/files/4370492/configure_log.txt)

**Comment by isuruf** [comment]
@fgvanzee, is it possible to make tests link against the static library on windows?
@hexi03, can you try `./configure --disable-shared zen`? This is an issue with the test suite itself. Test suite can't use the DLL library even though the DLL library works fine.

**Comment by hexi03** [comment]
Оk, now I got "check-blastest.sh: All BLAS tests passed!". Thanks

**Comment by fgvanzee** [comment]
@isuruf Thanks for your help here. 

> @fgvanzee, is it possible to make tests link against the static library on windows?

I don't see why not. We simply have to default to one or the other.
- For Linux/OSX, we default to using the static library [when linking the test drivers], but we use the shared library instead if the static is disabled.
- On Windows, for some reason, the convention is reversed: it uses the shared library by default, but uses the static library instead if the shared is disabled.

@isuruf @hexi03 What are your thoughts on this? Which convention do you prefer / should we use for Windows?

**Comment by isuruf** [comment]
I remember now. I don't think the windows builds support building static and shared library at the same time.

**Comment by fgvanzee** [comment]
@isuruf So, shall we leave it as-is?
