### ISSUE TITLE
Expert Interfaces - selective packing enabled

### ISSUE THREAD

**Issue by kvaragan** [flame/blis#392]
Hi,
When using expert interface for GEMM
The initialization of rntm_t object enables selective packing by default. 
 _bli_rntm_init() 
bli_rntm_clear_pack_a( rntm );
bli_rntm_clear_pack_b( rntm );

static void bli_rntm_clear_pack_a( rntm_t* rntm )
{
    bli_rntm_set_pack_a( TRUE, rntm );
}
static void bli_rntm_clear_pack_b( rntm_t* rntm )
{
    bli_rntm_set_pack_b( TRUE, rntm );
}_

As a result - expert interface for GEMM is inconsistent with BLAS APIs. In BLAS APIs these are disabled by default.
To explicitly disable packing we have used these APIs bli_rntm_set_pack_a(0,   &rntm);
   bli_rntm_set_pack_b(0, &rntm);
But is there any reason for enabling these packing by default in expert interfaces. Can we go ahead and change the default behavior in the rntm initialization.

**Comment by fgvanzee** [comment]
@kvaragan You raise a fair point. The default initialization of `rntm_t` objects via `bli_rntm_init()`, for use with the expert APIs (e.g. `bli_gemm_ex()`), is inconsistent with the default behavior of the non-expert APIs--that is, native APIs (e.g. `bli_gemm()`/`bli_dgemm()`) and BLAS APIs (e.g. `dgemm_()`). Currently, expert APIs enable packing of A and B by default while the non-expert APIs disable packing of of A and B by default.

I will change the definition of `bli_rntm_init()` to bring the default behavior of expert APIs in line with default behavior of non-expert APIs. That is, all APIs will disable packing of A and B by default.

Feel free to comment.

**Comment by fgvanzee** [comment]
Closing under the assumption that this issue was fixed. Please re-open if necessary.
