### ISSUE TITLE
error: redefinition of ‘unsigned int __get_cpuid_max(unsigned int, unsigned int*)

### ISSUE THREAD

**Issue by BhaskarNallani** [flame/blis#393]
When included cpuid.h in test_gemm.c  facing with below error.

error: redefinition of ‘unsigned int __get_cpuid_max(unsigned int, unsigned int*)’
10:26:45  __get_cpuid_max (unsigned int __ext, unsigned int *__sig)

Some application developer have a need of including #include "cpuid.h" for various reasons. 

Bhaskar

**Comment by BhaskarNallani** [comment]
@fgvanzee ,
Yes, the problem is with the "cpuid.h" and don't know why it doesn't have safeguards.

I tried calling __get_cpuid_max function in the driver code test_gemm.c  with out including cpuid.h and it is working fine. 

So we can ask application developers to use definitions of cpuid.h because it is already included in the blis.h.

Bhaskar

**Comment by devinamatthews** [comment]
@fgvanzee a better solution is to move `#include "cpuid.h"` to `bli_cpuid.c`.

**Comment by fgvanzee** [comment]
@devinamatthews Good idea. I've tested this out and it seems to work as intended. Will commit the fix shortly.

**Comment by fgvanzee** [comment]
@BhaskarNallani Please give 477ce91 a try.

**Comment by BhaskarNallani** [comment]
@fgvanzee @devinamatthews 
Thank you for the right fix. 
I verified it.
