### ISSUE TITLE
Problems using blis_gemm with gint_t matrices

### ISSUE THREAD

**Issue by everton1984** [flame/blis#399]
I'm trying to run some tests with integer matrix multiplication, I just created a basic test using `bli_obj_create` I ran into some issues with `bli_setijm` that I was able to fix for myself and then I realized that `bli_gemm` has a check for float datatypes. Is there a proper way to circumvent this or a correct approach to multiply integer matrices?

**Comment by devinamatthews** [comment]
BLIS does not currently support integer data types. We are working on adding this in the near(ish) future.

**Comment by everton1984** [comment]
I thought it supported, since there's a sandybridge kernel for ints...curious. Is there a discussion list or something similar on how to actually come to this? I have a significant interest on making BLIS working for integers for AI/ML applications.

**Comment by fgvanzee** [comment]
@everton1984 I'm assuming you're referring to the `bli_gemm_sandybridge_int_d8x4.c` file in `kernels/sandybridge/3`? If so, I'm afraid you've misinterpreted (understandably) what the `int` infix in that filename refers to. Here, we use `int` to distinguish from the neighboring `asm` file. Here, `int` and `asm` refer to the *way* the kernels were implemented--intrinsics vs assembly--not the datatype for which the kernels were implemented.

As Devin said, we don't currently support integer arithmetic for most operations. Sorry for the misunderstanding (and disappointment).

**Comment by everton1984** [comment]
> @everton1984 I'm assuming you're referring to the `bli_gemm_sandybridge_int_d8x4.c` file in `kernels/sandybridge/3`? If so, I'm afraid you've misinterpreted (understandably) what the `int` infix in that filename refers to. Here, we use `int` to distinguish from the neighboring `asm` file; `int` and `asm` refer to the _way_ the kernels were implemented--intrinsics vs assembly--not the datatype for which the kernels were implemented.
> 
> As Devin said, we don't currently support integer arithmetic for most operations. Sorry for the misunderstanding (and disappointment).

Yeah you're right there. No problem, so I believe there's the intention of adding integer support, has any work being done towards that? Do you mind if I study the code and make a proposition?

**Comment by fgvanzee** [comment]
> Yeah you're right there. No problem, so I believe there's the intention of adding integer support, has any work being done towards that? 

BLIS's current development effort (still in early stages) is to expand floating-point support (e.g. bfloat16). But additional support for integers is something we are considering, yes. 

> Do you mind if I study the code and make a proposition?

I'm not sure what you had in mind, but we don't have any integer-specific kernel code to study yet. Or did you mean the framework code?

**Comment by everton1984** [comment]
@fgvanzee I mean the framework.

**Comment by fgvanzee** [comment]
> @fgvanzee I mean the framework.

Oh, certainly. You're more than welcome to provide us with feedback!

**Comment by everton1984** [comment]
@fgvanzee Great, please keep this issue open then so I can use it as a way to discuss my proposals.

**Comment by jeffhammond** [comment]
@everton1984 You might check out https://github.com/hfp/libxsmm. As stated there, "Supported GEMM datatypes are: FP64, FP32, bfloat16, int16, and int8."  There is also https://github.com/pytorch/QNNPACK, which supports int8.  I couldn't figure out what types https://github.com/Maratyszcza/NNPACK/ supports but it might have integer support.

**Comment by everton1984** [comment]
@jeffhammond Thanks, however I have other reasons to need Blis that limits the possibilities of using other libs.

**Comment by devinamatthews** [comment]
@everton1984 since #407 opened up I think this discussion should move over there so it's all in one place.
