### ISSUE TITLE
Provide xerbla_array

### ISSUE THREAD

**Issue by isuruf** [flame/blis#400]
This is a blas function that should be provided by blis.

https://github.com/Reference-LAPACK/lapack/blob/9fb29d8ea47d643ad44a67d3da5de36e280143f5/BLAS/SRC/xerbla_array.f

**Comment by jeffhammond** [comment]
You are right but also 🤮to everything about XERBLA.

**Comment by fgvanzee** [comment]
@isuruf I'm having trouble understanding why `xerbla_array()` is needed. Could you help me understand the difference between a Fortran string and a string of single characters?

**Comment by isuruf** [comment]
`xerbla_array` is needed because `scipy` is using it and when switching the blas implementation to blis, there is a missing symbol error.

As to why it is needed at all, Fortran strings sends the length of the string as a hidden argument. (an argument at the end of the argument list and defaults to 1). You can see this in the f2ced version at https://github.com/flame/blis/blob/c53b5153bee585685bf95ce22e058a7af72ecef0/frame/compat/f2c/bla_xerbla.c#L46

`xerbla_array` uses an array of characters and explicitly adds the length of the array to its argument list so that other compilers like a C compiler doesn't have to guess how the particular Fortran compiler sends the length of the Fortran string.

**Comment by fgvanzee** [comment]
Thanks, @isuruf. Can you clarify what you would expect to happen if the string length passed into `xerbla_array_()` is less than zero? Should this cause the local `char` array to be passed into `xerbla_()` with uninitialized values? I'm looking at the netlib code, and that's what it would *seem* to do. But the description contains a note that  "If called with a non-positive SRNAME_LEN, XERBLA_ARRAY will call XERBLA with a string of all blank characters." Does Fortran implicitly initialize all `char` arrays to contain blank characters (is that the same as a space character)?

**Comment by isuruf** [comment]
https://github.com/Reference-LAPACK/lapack/blob/9fb29d8ea47d643ad44a67d3da5de36e280143f5/BLAS/SRC/xerbla_array.f#L111 makes it blank.

**Comment by isuruf** [comment]
blank=space characters

**Comment by fgvanzee** [comment]
@isuruf Thanks again. I've implemented `xerbla_array_()` in 787adad7. Please give it a try.

**Comment by isuruf** [comment]
Thanks @fgvanzee. I'll try git master with scipy and report back.

**Comment by fgvanzee** [comment]
Have you had a chance to try this out, @isuruf?

**Comment by fgvanzee** [comment]
@isuruf Checking again.

**Comment by isuruf** [comment]
Thanks for the reminder. This was a bug report from a user, so I'll bug him again to check BLIS master.

**Comment by isuruf** [comment]
I checked with scipy and it works now.
