### ISSUE TITLE
pass CC_VENDOR to configure

### ISSUE THREAD

**Issue by ajaypanyala** [flame/blis#402]
Is it possible to explicitly specify `CC_VENDOR` to `configure` ?

I am having an issue with configure trying to query compiler vendor when using Intel OneAPI compilers (based on clang)
https://dynamicinstaller.intel.com/oneapi/toolkits/base-kit/linux/

I end up getting the following error when running `make` (since `CC_VENDOR` is empty string)
```config/sandybridge/make_defs.mk:78: *** gcc, icc, or clang is required for this configuration..  Stop.```

**Comment by fgvanzee** [comment]
@ajaypanyala It may be better for us to instead fix the `cc_vendor` detection in `configure`.

What is the output when you run your compiler with `--version`?

**Comment by ajaypanyala** [comment]
```
Intel(R) oneAPI DPC++ Compiler 2021.1-beta06 (2020.4.0.0415)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

**Comment by devinamatthews** [comment]
@fgvanzee FYI if it's based on clang then we should resolve it as clang not icc, despite it being an Intel product.

**Comment by fgvanzee** [comment]
@devinamatthews That sounds fine, but what do we key off of? `oneAPI`? `DPC++`?

**Comment by devinamatthews** [comment]
oneAPI should do it until the next branding change.

**Comment by fgvanzee** [comment]
@ajaypanyala Please try out d51245e and let us know if it works for you.

**Comment by ajaypanyala** [comment]
@fgvanzee That works. Thanks!

**Comment by fgvanzee** [comment]
Great, @ajaypanyala! I'll close this issue now.
