### ISSUE TITLE
How to obtaining numerically reproducible results?

### ISSUE THREAD

**Issue by tuxzz** [flame/blis#406]
Does blis offer bit-to-bit reproducible result on multiple runs on the same machine? If I need a bit-to-bit reproducible result, how can I configure blis and my program?

**Comment by fgvanzee** [comment]
> Does blis offer bit-to-bit reproducible result on multiple runs on the same machine? 

I think the short answer is "no." But perhaps @rvdg can comment on this topic.

**Comment by rvdg** [comment]
I would have to think about this more deeply than I tend to have an attention span for…

Let me kick this around with people who are more into this.

It is certainly the case that “same machine” would have to mean a machine with the same blocking parameters.  My gut says that if then the machine has one core, the answer is possibly yes.  It may even be that if the machine has the same number of threads that the answer is yes.

**Comment by fgvanzee** [comment]
@rvdg Thanks for chiming in.

@tuxzz It may be that the answer is "yes" after all; I may have been confusing this issue with inter-machine bit reproducibility, which is an interest of some and definitely not something that BLIS currently guarantees.

**Comment by jeffhammond** [comment]
It all boils down to the sequence {k} in C[i,j]=Sum({k}) A[i,k]*B[k,j].
Anything that changes {k} breaks reproducibility. Blocking, of which
parallelism is a special case, reorders {k}.

Inter-machine portability requires disabling FMA (or using slow software
emulation on processors that don’t have it), and using the same blocking
factors everywhere. That’s probably going to reduce performance enough that
no one will care anymore.

In terms of parallelism, it shouldn’t matter if parallelization happens
only on C blocks such that only one thread writes to a given element of C,
which eliminates the parallel reduction over K. It also assumes IJ
parallelism doesn’t change the blocking factors.

MKL has conditional numerical reproducibility but it has a performance
cost. I’ve never used it but I’m sure folks can find details online.
-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by rvdg** [comment]
I have had a conversation about this with Greg Henry (at Intel).  He may want to get involved in this conversation and repeat some of what he explained.,

My gut is that most of the level-3 BLAS in BLIS either already is reproducible, or could be easily made so.  However, Greg points out that compilers do all kinds of weird things with edge cases for code where the actually computation loop is written in C.  As a result, the level-1 and level-2 parts of BLIS may not be reproducible at all...

**Comment by rvdg** [comment]
I’m happy to chime in on anything in this thread if I’m copied, although Robert and Jeff have already summarized some major points here. I will say that CNR in MKL is a performance hit, but in many cases it’s only a minor hit.

               I think one of the biggest difficulties with reproducibility is testing it. Testers that just measure accuracy won’t necessarily catch reproducibility bugs- that requires whole new tests. And as I mentioned to Robert, you need to be careful with compiler options. I can share compiler options that _help_ with reproducibility for the Intel compilers, but I’m not sure about GCC.

Greg

**Comment by devinamatthews** [comment]
@tuxzz I think the consensus is that BLIS "probably" is bit-for-bit reproducible on the same machine when using the same number of threads (and maybe even with different numbers). Please let us know if you discover otherwise.
