### ISSUE TITLE
Building on RPi4

### ISSUE THREAD

**Issue by dnoan** [flame/blis#408]
Hello,
I am building BLIS on the new RPi4. I want to build for generic ARM64 but this doesn't seem to work:

`./configure --enable-threading=openmp --enable-blas --enable-cblas arm64`

If I configure with the `auto` flag, it gives the following warning:

`Unable to automatically detect hardware type!`

How can I build a generic ARMv8 64-bit distribution of BLIS?

**Comment by fgvanzee** [comment]
@dnoan IIRC, the `auto` and `arm64` configuration targets doesn't work for ARMv8. You'll need to choose a subconfiguration and target it manually. Something like:
```
./configure [...] cortexa57
```
