### ISSUE TITLE
multi-threaded

### ISSUE THREAD

**Issue by lingweiyang** [flame/blis#418]
How can I use BLIS in multi-threaded applications?

**Comment by lingweiyang** [comment]
I want to run batch GEMM. Using OpenMP and BLIS.

**Comment by gmargari** [comment]
Hi @lingweiyang , maybe you can check here:
https://github.com/flame/blis/blob/master/docs/Multithreading.md

**Comment by lingweiyang** [comment]
Thank you for your answer. Do you know how to evaluate the proportion of GEMM synchronization and packing overhead in BLIS?

**Comment by hominhquan** [comment]
@lingweiyang You can add a `static` global counter in https://github.com/flame/blis/blob/master/frame/3/gemm/bli_gemm_ker_var2.c and accumulate the total time of `bli_gemm_ker_var2()` (macro-kernel) with `bli_clock()` for example. 

The difference between the accumulated macro-kernel time and the total time of `cblas_sgemm()` is the cost of all non-computational parts: init context, control-tree, memory pool, algorithm, loops, function calls, packing, thread creation, thread synchro ...

Then, AFAIK, there is currently no automatic way to do fine-grained profiling in BLIS. It could be for a future enhancement ?

**Comment by lingweiyang** [comment]
If BLIS can be more convenient for fine-grained analysis, it is helpful to guide future optimization.

**Comment by lingweiyang** [comment]
For bli_ thread_ set_ ways (4,1,4,4,1), is it 16 threads pack collaboratively the panel of B?
