### ISSUE TITLE
[ARMSVE] Some <arm_sve.h> Seems Conflicting with "blis.h"

### ISSUE THREAD

**Issue by xrq-phys** [flame/blis#420]
Dear BLIS developers,

I'm recently trying to configure and extend BLIS to the sve512 architecture (A64fx processor). The current configure strategy is to compile all armsve kernels at once and determine SVE vector length at runtime by `incd` instruction. But when I was trying to compile the sve256 packing kernel the following error appeared:
```
In file included from ../kernels/armsve/1m/bli_dpackm_armsve256_asm_8xk.c:39:
/opt/arm/arm-linux-compiler-20.1_Generic-AArch64_RHEL-7_aarch64-linux/lib/clang/9.0.1/include/arm_sve.h:42:14: fatal error: typedef redefinition with different types ('bool' vs 'gint_t' (aka 'long'))
typedef bool bool_t;
             ^
include/armsve/blis.h:540:18: note: previous definition is here
typedef  gint_t  bool_t;
                 ^
```

It seems that `arm_sve.h` provided by ARM Allinea Studio is conflicting some parts of BLIS typedef.
A current workaround is to not use set the packing kernel and avoid compiling the specific file `bli_dpackm_armsve256_asm_8xk.c`, but would it be possible to propose any fix?

PS: `arm_sve.h` vendored by `gcc` doesn't seem to give this error.

**Comment by devinamatthews** [comment]
Yes, using typenames that end in _t is generally not a good idea. Especially something as generic as bool_t. @fgvanzee since BLIS is C99, why aren't we using the actual bool type?

**Comment by devinamatthews** [comment]
BTW thanks for working on ARM SVE support, that would be really great!

**Comment by fgvanzee** [comment]
> Yes, using typenames that end in _t is generally not a good idea. Especially something as generic as bool_t. @fgvanzee since BLIS is C99, why aren't we using the actual bool type?

Why isn't *ARM* using the actual `bool` type hmmm? :)

More seriously, I think it was because I wasn't sure what size integer I wanted to use to define a boolean. By using `bool_t` everywhere, I could `typedef` it to `gint_t` or `guint_t` or `char` or `bool` or whatever at a later date.

@xrq-phys Thank you for working on this. I'll look into how best to accommodate your needs, probably by renaming `bool_t` to something else. You can probably assume that you will *not* have to work around the type name conflict in the medium-term.

**Comment by xrq-phys** [comment]
@fgvanzee That'll be great!

I can currently work with GCC 10 and somehow wait for a Arm compiler support. Thanks a lot!
(Although from my own tests GCC seems to outperform Arm compilers on BLIS source code...)

**Comment by xrq-phys** [comment]
Compilation of `kernels/armsve/1m/bli_dpackm_armsve256_asm_8xk.c` confirmed.
Config: GCC 9.3.1 for inline asm and `armclang` for all others (because of LLVM's register clobbering problem #207 #421).

Thanks a lot!

**Comment by fgvanzee** [comment]
@xrq-phys Are you saying that you no longer encounter the `bool_t` "previous definition is here" error? If so, I'm a little surprised since `bool_t` has not yet been removed from BLIS (though it **has** been redefined to be a C99 `bool`).

**Comment by devinamatthews** [comment]
@fgvanzee or gcc 9.3.1 might be allowing a repeated typedef (with the same target type) by default: https://stackoverflow.com/a/8595191.

**Comment by fgvanzee** [comment]
Oh, that's right. @xrq-phys's initial comment was about the ARM compiler, whereas gcc was fine. Sorry for the confusion.

**Comment by xrq-phys** [comment]
I guess Clang's also having this C11 feature enabled by default.

BTW [`arm_sve.h`](https://github.com/gcc-mirror/gcc/blob/releases/gcc-10/gcc/config/aarch64/arm_sve.h) in GCC 10 seems to imply its SVE intrinsics are directly handled while that provided by ARM Allinea Studio has lots of aliases.
