### ISSUE TITLE
Implemented ?tpsv()

### ISSUE THREAD

**Issue by gmargari** [flame/blis#427]
It seems from [bla_tpsv.c](https://github.com/flame/blis/blob/master/frame/compat/attic/bla_tpsv.c) that it is not implemented in compatibility layer, and I didn't find it in BLIS documentation.
It exists in [Netlib documentation](http://www.netlib.org/blas/#_level_2).

**Comment by devinamatthews** [comment]
There is another file: [frame/compat/f2c/bla_tpsv.c](https://github.com/flame/blis/blob/766769eeb944bd28641a6f72c49a734da20da755/frame/compat/f2c/bla_tpsv.c), and it seems to be in the exported symbols list. Is the symbol `dtpsv_` listed if you run `nm libblis.a`?

**Comment by gmargari** [comment]
I'm sorry, I didn't make myself clear at all. I am able to link against `tpsv_`, I would just like an equivalent `bli_xxxx` function so we can link our code both with MKL and BLIS and use the BLIS function.

**Comment by devinamatthews** [comment]
Ah, that is unlikely to happen. There is a CBLAS function defined if you enable the CBLAS interface but that's it. BLIS doesn't otherwise support packed matrices so there wouldn't be anything to gain from a `bli_xxx` function.

**Comment by gmargari** [comment]
Alright, thanks @devinamatthews !
