### ISSUE TITLE
Quest: undefined reference to 'blis_abort'

### ISSUE THREAD

**Issue by shana34** [flame/blis#428]
hello，
        After installing the blis with configure 'zen', I tryied #include "blis.h" in my code. But, when I compile it with command "gcc -fopenmp -lm -lblis *.c -o a.out", I receive the error of ld as written by my title.
        Besides, when I tried commands :  "gcc -fopenmp -c *.c -o *.o" & "gcc *.o $(PREFIX)/lib/zen/libblis.a -fpenmp -lm -o a.out", I make it successfully. How to solve  or explain this question?

**Comment by devinamatthews** [comment]
@shana34 Does the error also happen if you do `gcc -fopenmp *.c -o a.out -lblis -lm`, this is, put the libraries after the source files?

**Comment by shana34** [comment]
@devinamatthews pity to say that yes, it still happens, In function `bli_gemmsup_ref_var1n2m_opt_cases': test.c:(.text+0x11661): undefined reference to `bli_abort'

**Comment by devinamatthews** [comment]
OK. Before I try to reproduce, please share your environment details (OS version, compiler version, output of `configure`, etc.).

**Comment by devinamatthews** [comment]
Oh, also BLIS version, either a release number or git commit ID.

**Comment by shana34** [comment]
Linux version 3.10.0-957.el7.x86_64 (root@centos-build-7.6) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Fri Oct 25 22:34:08 UTC 2019

**Comment by shana34** [comment]
@devinamatthews if 'output of configure' refers to the output of "./configure --prefix=$(PREFIX) -t openmp zen"?

**Comment by devinamatthews** [comment]
To make my life a little easier, can you reproduce the bug with the following minimal program:

```C
extern int bli_gemmsup_ref_var1n2m_opt_cases();
int main(int argc, char** argv) { return bli_gemmsup_ref_var1n2m_opt_cases(); }
```

**Comment by devinamatthews** [comment]
> @devinamatthews if 'output of configure' refers to the output of "./configure --prefix=$(PREFIX) -t openmp zen"?
Yes

**Comment by fgvanzee** [comment]
FTR, this sounds identical to a closed issue that @vkirangoud commented on in [1]. I asked for elaboration but no response yet.

[1] https://github.com/flame/blis/issues/366

**Comment by shana34** [comment]
./test.c:3:12: error: conflicting types for ‘bli_gemmsup_ref_var1n2m_opt_cases’
 extern int bli_gemmsup_ref_var1n2m_opt_cases();
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ./test.c:1:0:
/home/test/blis/include/blis/blis.h:35841:18: note: previous definition of ‘bli_gemmsup_ref_var1n2m_opt_cases’ was here
 BLIS_INLINE void bli_gemmsup_ref_var1n2m_opt_cases
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by devinamatthews** [comment]
That minimal program would be without `blis.h`; the real thing that I'm looking for is a short 3-4 line program that reliably reproduces the error. If you can send one that works, or verify that the one I sent also triggers the error.

**Comment by shana34** [comment]
Oh, the one you sent to me tell me that : gcc -fopenmp ./test.c -o a.out -lblis -lm
/tmp/ccRmriX4.o: In function `main':
test.c:(.text+0x15): undefined reference to `bli_gemmsup_ref_var1n2m_opt_cases'
collect2: error: ld returned 1 exit status

**Comment by shana34** [comment]
so I add #include "blis.h" in it, for my simple code : 
#include "blis.h"
#include "omp.h"

int main(void){
        #pragma omp parallel num_threads(6)
        printf("Hello.h\n");
        return 0;
}

**Comment by shana34** [comment]
compiled by command: "gcc -fopenmp ./test.c -o a.out -lblis -lm"

**Comment by devinamatthews** [comment]
OK, I'll use that program.

**Comment by shana34** [comment]
thx
