### ISSUE TITLE
add -d DEBUG will be caused error

### ISSUE THREAD

**Issue by chengguosun** [flame/blis#432]
hi,
i compiled the latest blis0.7.0, and added -d DEBUG option when configuring zen architecture, but make caused one error, the confiure command and errors are as follows:
command:
./configure  --enable-debug --enable-shared --enable-blas --enable-cblas -t openmp zen
 errors:
kernels/haswell/3/sup/bli_gemmsup_rd_haswell_asm_d6x8m.c:724:1: error: bp cannot be used in asm here
 }
 ^
compilation terminated due to -Wfatal-errors.
kernels/haswell/3/sup/bli_gemmsup_rd_haswell_asm_d6x8n.c: In function ‘bli_dgemmsup_rd_haswell_asm_6x8n’:
kernels/haswell/3/sup/bli_gemmsup_rd_haswell_asm_d6x8n.c:786:1: error: bp cannot be used in asm here
 }

I'm not sure why. I'm looking forward to your answer.

**Comment by devinamatthews** [comment]
This looks similar to #417. Please try the latest commit on the `master` branch and see if that fixes the problem.

**Comment by chengguosun** [comment]
The problem has been resolved through the merger of the latest commits, thanks for your work.
