### ISSUE TITLE
Multithreading degrades performance for TRSM when matrices are small

### ISSUE THREAD

**Issue by gmargari** [flame/blis#439]
Hi all,

I hope you're doing well and are all safe.

I was running some benchmarks with BLIS 0.7.0 and noticed that using multiple thread seems to degrade performance for `DTRSM` when matrices are small. If matrices are "big enough", multithreading indeed improves performance.

What I did was calling `DTRSM` with `NxN` matrices (both `A` and `B`), where `N` = 2, 4, ..., 1024. Matrices were zeroed. I did multiple (e.g. 100) calls and kept the lowest time. Before each batch of calls I set with `bli_thread_set_num_threads()` the number of threads to either 1 or the number of physical cores.

Results (copied by hand from internal network) from **i7-6800K**, 6 physical cores:

```
| N:    2 | threads:  1 | time:     5 |
| N:    2 | threads:  6 | time:    41 |

| N:    4 | threads:  1 | time:     8 |
| N:    4 | threads:  6 | time:    40 |

| N:    8 | threads:  1 | time:     6 |
| N:    8 | threads:  6 | time:    37 |

| N:   16 | threads:  1 | time:     7 |
| N:   16 | threads:  6 | time:    37 |

| N:   32 | threads:  1 | time:     7 |
| N:   32 | threads:  6 | time:    40 |

| N:   64 | threads:  1 | time:    20 |
| N:   64 | threads:  6 | time:    47 |

| N:  128 | threads:  1 | time:   103 |
| N:  128 | threads:  6 | time:    76 |

| N:  256 | threads:  1 | time:   537 |
| N:  256 | threads:  6 | time:   235 |

| N:  512 | threads:  1 | time:  3188 |
| N:  512 | threads:  6 | time:  1131 |

| N: 1024 | threads:  1 | time: 23792 |
| N: 1024 | threads:  6 | time:  8134 |
```

Results (copied by hand) from **Threadripper 1950X**, 16 physical cores:

```
| N:    2 | threads:  1 | time:     5 |
| N:    2 | threads: 16 | time:    84 |

| N:    4 | threads:  1 | time:     3 |
| N:    4 | threads: 16 | time:    82 |

| N:    8 | threads:  1 | time:     4 |
| N:    8 | threads: 16 | time:    84 |

| N:   16 | threads:  1 | time:     4 |
| N:   16 | threads: 16 | time:    82 |

| N:   32 | threads:  1 | time:     6 |
| N:   32 | threads: 16 | time:    84 |

| N:   64 | threads:  1 | time:    17 |
| N:   64 | threads: 16 | time:    96 |

| N:  128 | threads:  1 | time:    99 |
| N:  128 | threads: 16 | time:   124 |

| N:  256 | threads:  1 | time:   647 |
| N:  256 | threads: 16 | time:   274 |

| N:  512 | threads:  1 | time:  4895 |
| N:  512 | threads: 16 | time:  1283 |

| N: 1024 | threads:  1 | time: 41044 |
| N: 1024 | threads: 16 | time:  4787 |
```

Background: our FEM solver code performs a factorization which, depending on the model, ends up doing many thousands calls to `DTRSM` with small matrices (e.g. in the order of 10x10).

**Comment by gmargari** [comment]
Centos 7.6 with gcc 4.9.2 (`g++ test.cpp -lm -fopenmp -std=c++11 libblis.a`)

**Comment by devinamatthews** [comment]
To add to @hominhquan's comment, while BLAS performance on very small matrices is typically bad, trying to use multiple threads will be even worse. There needs to be a significant amount of work for threading to provide a benefit, something on the order of m=n=k=500 or more.

Bottom line: if you're doing thousands of 10x10 solves then BLIS/BLAS isn't the right library for you Good luck!
