### ISSUE TITLE
power9 assembler warnings

### ISSUE THREAD

**Issue by loveshack** [flame/blis#440]
I can only currently run on power8, so can't test, but building bli_gemm_power9_asm_d12x6 with gcc 9.3.1 and binutils 2.32 produces "invalid register expression" warnings. Generating .s first and compiling that shows it's for the statements containing %r0, e.g.

kernels/power9/3/bli_gemm_power9_asm_d12x6.s:186: Warning: invalid register expression

This is with the version from current master.

**Comment by nicholaiTukanov** [comment]
Thank you for mentioning this. 

I noticed this when I wrote the kernel, but it has never caused any errors in results. Therefore, I left the warning alone.

**Comment by devinamatthews** [comment]
@nicholaiTukanov shouldn't the lines like https://github.com/flame/blis/blob/6a4aa986ffc060d3e64ed230afe318b82630f8b2/kernels/power9/3/bli_gemm_power9_asm_d12x6.c#L98-L99 just be:

```
cmpwi r11, 0
beq DCONSIDERKLEFT
```

etc.?

**Comment by nicholaiTukanov** [comment]
@devinamatthews I think you're right... That's probably where the warnings come from.

I am going to run some more tests to make sure the semantics don't change.
