### ISSUE TITLE
SKX throttling possible improvement

### ISSUE THREAD

**Issue by loveshack** [flame/blis#441]
I was puzzled by BLIS' greater throttling on SKX parallel DGEMM compared with MKL.  I haven't tried to compare the kernels, as I'm not familiar enough with assembler, but https://github.com/xianyi/OpenBLAS/pull/2646 has a change which might be relevant if it hasn't been considered.

**Comment by jeffhammond** [comment]
What's the evidence for greater throttling?  I am not sure that the OpenBLAS issue is accurate.  AVX512 FMA instructions throttle the most.  Data movement instructions should be in the AVX512-light bucket so optimizing them away should _increase_ the thermal pressure.  I suspect that what is happening in OpenBLAS is the code is just running faster.

I am happy to be wrong and will gladly change assessment if someone has frequency measurement data, but I do not see that here or there.

**Comment by jeffhammond** [comment]
I'm going to close this.  BLIS could optimize DGEMM better for SKX but it is unrelated to frequency, power or thermals.

**Comment by devinamatthews** [comment]
@loveshack as a follow-up, we don't have the manpower to focus on SKX or other Intel architectures currently (especially since they haven't funded us in years), but we would welcome any PRs on this topic.

**Comment by jeffhammond** [comment]
As far as I understand it from a more expert colleague, OpenBLAS changed
from 12x2 to 6x4 tiling in the microkernel, which reduces back end
bottlenecks. Unless BLIS did an equivalent thing, what they observed isn’t
relevant. --
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by loveshack** [comment]
So it looks as if only the AMD version is worth considering for a BLAS.

I'm afraid contributions and suggestions don't seem to be very welcome
in practice, in contrast to OpenBLAS.  If even AMD's changes don't get
merged in a year, no-one will bother.  Especially so if it would involve
a lot of research for something like SKX improvements.

**Comment by jeffhammond** [comment]
>
>
>
> So it looks as if only the AMD version is worth considering for a BLAS.
>

This is false and the performance data shown in the wiki proves it.

BLIS was the first open-source BLAS implementation for AVX512, and the only
to support KNL. It supported Blue Gene/Q, supports Power, supports many
variants of ARM, and has great support for pre-AVX512 x86 from both AMD and
Intel.


>
> I'm afraid contributions and suggestions don't seem to be very welcome


I welcome issues that are based on data about BLIS, either the source code
or performance measurements of BLIS.

You didn’t report an issue with BLIS or suggest anything constructive. You
reported that another project made a claim about their implementation that
itself was lacking evidence, and you didn’t provide any evidence that the
OpenBLAS finding was relevant to BLIS if it was even true about OpenBLAS.

What are we supposed to do - thank you for a pointer to speculation by
OpenBLAS developers about AVX512? That project is years behind BLIS in
terms of having a correct and efficient AVX512 port - why do we need to
learn from them?

If the BLIS team needs to understand SKX microarchitecture, they can (and
did) ask Intel.


> a lot of research for something like SKX improvements


What improvements do you want? You haven’t asked for anything here, other
than for other people to determine if speculation regarding another project
is relevant and fix a problem that might not exist.
-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/
