### ISSUE TITLE
performance problem with openmp trmm on skx

### ISSUE THREAD

**Issue by loveshack** [flame/blis#442]
I ran the test/3 performance comparison with release 0.7 using openmp on all 32 cores of an SKX node and found that trmm performance is dire.  It's similar for a single full socket. Serial skx two-socket haswell are reasonable, though. 
I can't attach the figure here, sigh, so currently it's at https://personalpages.manchester.ac.uk/staff/dave.love/l3_perf_skx_nt32.pdf
For what it's worth, openblas was 0.3.10, and mkl oneapi-2021.1-beta06; I should re-scale for throttling, but the effect is obvious.

**Comment by jeffhammond** [comment]
how does it work on a single socket with affinity enabled?

**Comment by devinamatthews** [comment]
For `trmm`, there is some monkeying around with the block sizes that goes on. Maybe the fact that `MR=16` and `NR=14` don't have many common multiples is the problem? @fgvanzee?

**Comment by fgvanzee** [comment]
Dave's results are definitely not consistent with the results I found during my last SkylakeX performance gathering [1].

@loveshack Did you disable frequency throttling beforehand? Your performance kind of looks like what I recall seeing when I only had access to a system on which I had no root privileges.

When running these tests, I **always** use `cpupower` to set both the governor (`performance`) and the minimum clock rate (whatever `cpupower` says is the hardware limit, which was 2.0 GHz in my case).

[1] https://github.com/flame/blis/blob/master/docs/Performance.md#skylakex-results

**Comment by devinamatthews** [comment]
@fgvanzee I understand why you do the frequency throttling, but for predicting "real-world" performance it is probably counterproductive.

**Comment by loveshack** [comment]
> how does it work on a single socket with affinity enabled?

Similarly, but without the strange structure in the s case, which I
thought might be a clue.  Assume I use core binding, actually OMP_PLACES
for convenience and generality.

**Comment by loveshack** [comment]
I wanted to compare current implementations, and that's on a fairly
typical HPC system on which I'm not at liberty to change the setup,
unfortunately.  I got the average frequency reported by perf for a dgemm
run at the start of the job, as I said before.  I'm not interested in
the absolute best performance, and would normally expect to be using the
serial version for HPC anyway.  Why would throttling have a pathological
effect on just trmm?  This suggests not using BLIS in the real world.

**Comment by loveshack** [comment]
Actually, mentioning affinity, I thought I should check.  I was sure the
physical cores corresponded to logical ones on those nodes, but lstopo
says they don't.  I don't know if I was wrong originally, or the BIOS
changed incompatibly in the interim.  I wish everything used hwloc.

Anyhow, I'll try to get new results over the weekend; I guess that's it,
but I'm surprised it only affected trmm.  (I used jc=4, ic=8 for 32
cores, but should probably have left them unset for a realistic
comparison.)

**Comment by devinamatthews** [comment]
@fgvanzee is `trmm` calling `bli_trmm3` or `bli_trmm`? The former seems to have the same threading restrictions as `bli_trsm`.

**Comment by fgvanzee** [comment]
> @fgvanzee is `trmm` calling `bli_trmm3` or `bli_trmm`? 

Are you asking about the BLAS routines `?trmm_()`? If so, they call `trmm` (not `trmm3`).

> The former seems to have the same threading restrictions as `bli_trsm`. [edit: I mean latter]

Could you elaborate on why you think this?

**Comment by devinamatthews** [comment]
I was looking [here](https://github.com/flame/blis/blob/810e90ee806510c57504f0cf8eeaf608d38bd9dd/frame/base/bli_rntm.c#L81).

**Comment by fgvanzee** [comment]
@devinamatthews That is the correct place to look. But the restrictions on `trmm` are not the same as those of `trsm`. `trmm_r` restricts jc-level parallelism whereas `trsm` (l or r) restricts only ir-level parallelism. Though maybe your point was just that they were restricted at all?

If Dave used my test drivers in `test/3` without modifying them, he would be using `trmm_ru`:
```c
#if 0
    side   = BLIS_LEFT;
#else
    side   = BLIS_RIGHT;
#endif
#if 0
    uploa  = BLIS_LOWER;
#else
    uploa  = BLIS_UPPER;
#endif
```
so in theory *maybe* this is related.

@loveshack 
1. Are the strange `trmm` results reproducible over multiple runs?
2. What happens if you change the driver to execute `trmm_ll` or `trmm_lu`?

**Comment by devinamatthews** [comment]
I didn't mean that they're exactly the same, just that parallelism is nixed along on dimension. If we have a trmm that doesn't have that fairly serious restriction then why aren't we using it as default?

**Comment by devinamatthews** [comment]
I also guess I don't understand the need for such a restriction. Unlike trsm, trmm has no data dependencies between elements o C...

**Comment by fgvanzee** [comment]
> I didn't mean that they're exactly the same, just that parallelism is nixed along on dimension. If we have a trmm that doesn't have that fairly serious restriction then why aren't we using it as default?

Good question. What probably happened is I probably accidentally committed a temporary change.

> Unlike trsm, trmm has no data dependencies between elements o C...

I would love for that restriction to not be needed. But, these restrictions are largely left over from Tyler's initial implementation, and I'm not in the right state of mind to work through this at the moment. Let me get back to you.

**Comment by rvdg** [comment]
Just a small comment:  Trmm is probably the least important of all level-3 BLAS.  It is just not a common operation and rarely a performance critical one.

**Comment by fgvanzee** [comment]
Okay, I *think* I understand why there is a restriction on `trmm_r` but not `trmm_l`. The asymmetry comes from the fact that the jc loop, in our Goto-like algorithm, *always* partitions the right-hand matrix operand. When that matrix operand is general/dense, as in `trmm_l`, everything is fine. But when that matrix is triangular, you run into dependency issues **given** that you are updating the other matrix in-place (modulo the packing buffer, of course). I think allowing jc-level parallelism allows a race condition given that we don't synchronize in the pc loop.

**Comment by fgvanzee** [comment]
@rvdg I disagree slightly. Given that our UT Householder transform-based QR factorization relies on `trmm` (and assuming that Householder/QR is pretty important, which I think it is), I would say something like `hemm` or `her2k` is of relative less importance. But that's just my gut.

**Comment by rvdg** [comment]
Notice that I was careful to say it is not performance critical…. It is not really performance critical when applying the UT transform, since it ends up being a b x b times b x n trmm.

**Comment by fgvanzee** [comment]
> Notice that I was careful to say it is not performance critical…. It is not really performance critical when applying the UT transform, since it ends up being a b x b times b x n trmm.

@rvdg Touche.

**Comment by loveshack** [comment]
This does appear to have been a problem with the specified affinity not matching the hardware and/or specifying the thread dimensions.  It went away when just using OMP_NUM_THREADS and OMP_PLACES=cores OMP_PROC_BIND=close (which the el7 libgomp supports, even if it's not documented).
