### ISSUE TITLE
additional error with the undefined sanitizer

### ISSUE THREAD

**Issue by loveshack** [flame/blis#444]
After

CC=gcc-10 LDFLAGS='-g -fsanitize=undefined' CFLAGS='-g -fsanitize=undefined' ./configure skx 

with current master, in addition to the previously-reported left shift errors, there's this one that occurs several times from make check:

Running sblat2.x < './blastest/input/sblat2.in' (output to 'out.sblat2')
blastest/f2c/lread.c:709:15: runtime error: member access within misaligned address 0x7ffc243f9824 for type 'union flex', which requires 8 byte alignment
0x7ffc243f9824: note: pointer points here
  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00
              ^ 

I guess it's only relevant to the tests, and harmless, but I'm very out of practice with libf2c.

**Comment by devinamatthews** [comment]
The f2c'ed stuff is pretty terrible. I would ignore this.

**Comment by devinamatthews** [comment]
I'm going to close this because the reported error happens in the BLAS testsuite code, not BLIS proper.
