### ISSUE TITLE
openmp data races reported by sanitizer

### ISSUE THREAD

**Issue by loveshack** [flame/blis#445]
I guess this isn't of interest, but I might as well post the result.

After

CC=gcc-10 LDFLAGS='-g -fsanitize=thread' CFLAGS='-g -fsanitize=thread' ./configure -t openmp skx

with current master on a four-core workstation I get a megabyte of output from

OMP_NUM_THREADS=4 make check

These are the unique summary lines.  I haven't tried to make sense of the traces and perhaps an openmp-specific tool like Archer would be helpful.

SUMMARY: ThreadSanitizer: data race frame/0/copysc/bli_copysc.c:128 in bli_cccopysc
SUMMARY: ThreadSanitizer: data race frame/1m/packm/bli_packm_cntl.c:65 in bli_packm_cntl_create_node
SUMMARY: ThreadSanitizer: data race frame/1m/packm/bli_packm_cntl.c:66 in bli_packm_cntl_create_node
SUMMARY: ThreadSanitizer: data race frame/base/bli_error.c:143 in bli_error_checking_level
SUMMARY: ThreadSanitizer: data race frame/base/bli_query.c:75 in bli_obj_equals
SUMMARY: ThreadSanitizer: data race frame/thread/bli_l3_decor_openmp.c:101 in bli_l3_thread_decorator._omp_fn.0
SUMMARY: ThreadSanitizer: data race frame/thread/bli_l3_decor_openmp.c:106 in bli_l3_thread_decorator._omp_fn.0
SUMMARY: ThreadSanitizer: data race include/skx/blis.h:19964 in bli_thrcomm_num_threads
SUMMARY: ThreadSanitizer: data race include/skx/blis.h:2011 in bli_obj_init_full_shallow_copy_of
SUMMARY: ThreadSanitizer: data race include/skx/blis.h:2013 in bli_obj_init_full_shallow_copy_of
SUMMARY: ThreadSanitizer: data race include/skx/blis.h:2014 in bli_obj_init_full_shallow_copy_of
SUMMARY: ThreadSanitizer: data race include/skx/blis.h:2015 in bli_obj_init_full_shallow_copy_of
SUMMARY: ThreadSanitizer: data race include/skx/blis.h:2016 in bli_obj_init_full_shallow_copy_of
SUMMARY: ThreadSanitizer: data race include/skx/blis.h:2017 in bli_obj_init_full_shallow_copy_of
SUMMARY: ThreadSanitizer: data race include/skx/blis.h:2019 in bli_obj_init_full_shallow_copy_of
SUMMARY: ThreadSanitizer: data race include/skx/blis.h:2020 in bli_obj_init_full_shallow_copy_of
SUMMARY: ThreadSanitizer: data race include/skx/blis.h:2021 in bli_obj_init_full_shallow_copy_of
SUMMARY: ThreadSanitizer: data race include/skx/blis.h:2023 in bli_obj_init_full_shallow_copy_of
SUMMARY: ThreadSanitizer: data race include/skx/blis.h:2024 in bli_obj_init_full_shallow_copy_of
SUMMARY: ThreadSanitizer: data race include/skx/blis.h:2025 in bli_obj_init_full_shallow_copy_of
SUMMARY: ThreadSanitizer: data race include/skx/blis.h:2026 in bli_obj_init_full_shallow_copy_of
SUMMARY: ThreadSanitizer: data race include/skx/blis.h:2028 in bli_obj_init_full_shallow_copy_of
SUMMARY: ThreadSanitizer: data race include/skx/blis.h:2031 in bli_obj_init_full_shallow_copy_of
SUMMARY: ThreadSanitizer: data race include/skx/blis.h:2032 in bli_obj_init_full_shallow_copy_of
SUMMARY: ThreadSanitizer: data race include/skx/blis.h:2033 in bli_obj_init_full_shallow_copy_of
SUMMARY: ThreadSanitizer: data race include/skx/blis.h:2034 in bli_obj_init_full_shallow_copy_of
SUMMARY: ThreadSanitizer: data race include/skx/blis.h:2035 in bli_obj_init_full_shallow_copy_of
SUMMARY: ThreadSanitizer: data race include/skx/blis.h:2036 in bli_obj_init_full_shallow_copy_of
SUMMARY: ThreadSanitizer: data race include/skx/blis.h:24743 in bli_pblk_buf
SUMMARY: ThreadSanitizer: data race include/skx/blis.h:24828 in bli_pool_top_index
SUMMARY: ThreadSanitizer: data race include/skx/blis.h:6134 in bli_obj_dt
SUMMARY: ThreadSanitizer: data race include/skx/blis.h:6779 in bli_obj_length
SUMMARY: ThreadSanitizer: data race include/skx/blis.h:6784 in bli_obj_width
SUMMARY: ThreadSanitizer: data race include/skx/blis.h:6827 in bli_obj_row_stride
SUMMARY: ThreadSanitizer: data race include/skx/blis.h:6832 in bli_obj_col_stride
SUMMARY: ThreadSanitizer: data race include/skx/blis.h:7041 in bli_obj_row_off
SUMMARY: ThreadSanitizer: data race include/skx/blis.h:7046 in bli_obj_col_off
SUMMARY: ThreadSanitizer: data race include/skx/blis.h:7117 in bli_obj_buffer
SUMMARY: ThreadSanitizer: data race include/skx/blis.h:7147 in bli_obj_elem_size
SUMMARY: ThreadSanitizer: data race (/lib/x86_64-linux-gnu/libtsan.so.0+0x2b46a) in __interceptor_free
SUMMARY: ThreadSanitizer: data race (/lib/x86_64-linux-gnu/libtsan.so.0+0x616de) in __tsan_atomic64_load
SUMMARY: ThreadSanitizer: data race (/lib/x86_64-linux-gnu/libtsan.so.0+0x63bbd) in __tsan_atomic64_fetch_add

**Comment by devinamatthews** [comment]
@loveshack since we're using our own synchronization primitives, I expect these are largely false positives. Is there an easy way to make TSan "aware" of the primitives we're using?

**Comment by devinamatthews** [comment]
It's been a while without a response so I'm going to close. If the SNR could be improved then maybe this could be a useful tool for finding possible bugs.
