### ISSUE TITLE
Migrate Travis CI testing from Trusty to Xenial or Bionic

### ISSUE THREAD

**Issue by fgvanzee** [flame/blis#453]
Update `.travis.yml` file to use Ubuntu 16.04 (Xenial) or 18.04 (Bionic). The config file currently specifies use of 14.04 (Trusty). See [1] for migration guide and [2] for a list of supported Ubuntu distributions.

[1] https://docs.travis-ci.com/user/trusty-to-xenial-migration-guide
[2] https://docs.travis-ci.com/user/reference/linux

**Comment by devinamatthews** [comment]
Addressed by #500.
