### ISSUE TITLE
Marginal errors while running dotxaxpyf for multiple cases.

### ISSUE THREAD

**Issue by nagsingh** [flame/blis#455]
Marginal errors observed while running form testsuite for dotxaxpyf.

Steps to reproduce.
1. In master branch, ./configure --enable-cblas -t openmp haswell; make -j; cd testsuite
2. Change input.operation to run for dotxaxpyf   (i.e. change in line 216   1       # dotxaxpyf   ---->  2        # dotxaxpyf)
3. After change, make clean; make (inside testsuite folder)
4. run ./test_libblis.x. observe the logs for "MARGINAL"

**Comment by fgvanzee** [comment]
@nagsingh Thanks for this report. However, these can be safely ignored. `dotxaxpyf` is actually working fine in this case. I probably need to adjust the thresholds.

**Comment by fgvanzee** [comment]
@nagsingh I've adjusted the thresholds upward. This shouldn't be an issue going forward. Thanks again.
