### ISSUE TITLE
BLIS testsuite application aborts for amaxv API for vector size 0

### ISSUE THREAD

**Issue by Meghana-vankadari** [flame/blis#459]
Output of testsuite:
% --- amaxv ---
%
% amaxv m                      -1
% amaxv operand params         (none)
%

% blis_<dt><op>_<stor>               m   gflops   resid      result

libblis: frame/base/bli_query.c (line 48):
libblis: Requested functionality not yet implemented.
libblis: Aborting.
Aborted (core dumped)

Issue arises when dimension is zero. Functionality of amaxv is fine for this case. The main problem is with test function used to test the functionality of amaxv. 
Test function tries to check whether the value pointed by the index returned by amaxv is actually maximum value or not.
bli_obj_equals is implemented only for 1x1 objects. Since vector dimension is zero, bli_obj_equals returns with an error 'Not yet implemented'.

**Comment by fgvanzee** [comment]
This should be fixed now in 78aee79. Thanks Meghana.
