### ISSUE TITLE
multithread mode not working

### ISSUE THREAD

**Issue by hongyx11** [flame/blis#462]
I try to benchmark dgemv of blis library. I want to use dgemv in multithread mode. 
I'm running on AMD EPYC 7702 64-Core Processor. However, blis only works in single thread mode.

- how I install library.
`git clone https://github.com/flame/blis.git`
`cd blis`
`./configure -t openmp -p $HOME/simplemulti/amdbuild auto`
`make install -j`

here I notice antoher problem that the output of configure shows an error 
`
configure: executing: git describe --tags.
configure: git returned an error: 'Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]'.
configure: using string from unmodified version file.
`
but anyway then I finished the compile.

- Then I use the code and makefile in  https://github.com/hongyx11/simpledgemv 
`make amdibex`
blisapi.c is sample code of gemv from https://github.com/flame/blis/blob/master/examples/oapi/08level2.c
The only change is I choose m = 35000 and n = 70000.

- When I launch the binary, I check the htop of my machine, it shows only 1 core is running.

- [htopoutput](https://github.com/hongyx11/simpledgemv/blob/master/threads.png)
- [running console output](https://github.com/hongyx11/simpledgemv/blob/master/running.png)
Thanks,

**Comment by devinamatthews** [comment]
For the `git` issue, a version of 1.8.5 or later is required. I'll see about updating the docs if that isn't already in there.

For the OpenMP issue, please attach the complete `configure` output. Also, what is the value of `$OMP_NUM_THREADS` and/or `$BLIS_NUM_THREADS`?

**Comment by devinamatthews** [comment]
Docs updated re git version.

**Comment by hongyx11** [comment]
Hi,

- git issues,
thanks, after change git > 1.8.5, it works without any complaints.
Then I rerun the build and get the same cases.
- configureoutput 
[configureoutput](https://github.com/hongyx11/simpledgemv/blob/master/exp2/configureoutput.txt)
- threads usage
[threadsusage](https://github.com/hongyx11/simpledgemv/blob/master/exp2/exp2threads.png)
-env of THEADS
I use 128, please see [threadsenv](https://github.com/hongyx11/simpledgemv/blob/master/exp2/envTHREADS.txt)

Thanks

**Comment by devinamatthews** [comment]
Right, I glossed over the most important part: `dgemv`... unfortunately only level 3 BLAS (`dgemm` etc.) is parallelized at the moment. Hopefully this will be rectified at some point.

**Comment by hongyx11** [comment]
Okay. Thanks!

**Comment by jeffhammond** [comment]
If one implements DGEMV as a DGEMM where on of the dimensions is 1, will
that not thread? Even if the compute is inefficient, DGEMV is often
bandwidth-limited and threading will allow it to utilize all the bandwidth
of this CPU.--
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by hongyx11** [comment]
that could be possible, will give it a try, yes, we are benchmarking the bandwidth of CPU.

**Comment by devinamatthews** [comment]
If you're benchmarking memory bandwidth then I recommend using something reliable like STREAM.

**Comment by hongyx11** [comment]
@devinamatthews Thanks for your suggestions! in our app, we use dgemv and we know it's bounded by bandwidth, so we get the performance of dgemv based on bandwidth.
