### ISSUE TITLE
Using Windows Subsystem Linux  for Windows build will fail due to -fPIC

### ISSUE THREAD

**Issue by iaincoulter** [flame/blis#463]
Following the steps to build a windows version with Windows Subsystem Linux installed causes -fPIC errors

clang: fatal error: unsupported option '-fPIC' for target 'x86_64-pc-windows-msvc'

Main issue is when you type 'bash' it starts up and instance of WSL.  When running configure this logic is applied

```
        os_name=$(uname -s)
	os_vers=$(uname -r)
	echo "${script_name}: detected ${os_name} kernel version ${os_vers}."

	# Define a single variable off of which we can branch to tell if we are
	# building for Windows.
	is_win=no
	if [[ $os_name == MSYS* ]] || \
	   [[ $os_name == MINGW* ]]  || \
	   [[ $os_name == CYGWIN* ]] ; then
		is_win=yes
	fi
```

Thus is_win is not set to true,   as when using WSL "uname -s"  it returns "Linux" !!!  (as it should as it is running linux)
Apart from manually modifying this not sure how this should be fixed.   
A user with WSL installed could be using it to build a proper Linux version or a Windows version, but using "os_name" will not indicate what the user intended!!

**Comment by devinamatthews** [comment]
@iaincoulter do you mean the instructions [here](https://github.com/flame/blis/blob/e14424f55b15d67e8d18384aea45a11b9b772e02/docs/FAQ.md#can-i-build-blis-on-windows)? And are you using striaght MSYS2, Mingw64, Cygwin, etc.? Lastly, are you specifically trying to build a .dll or just build BLIS at all (in the latter case you could just do everything in WSL)?

**Comment by iaincoulter** [comment]
I'm trying to build a .dll  but don't see why i need to install MSYS2. Mingw64 or Cygwin as WSL Linux already provides all the tools (sed/bash/etc) they provide.   For compiler I'm using windows LLVM as mentioned in that link.
modifying the configure script to set is_win=true.    Code is compiling in this manner but has no completed yet.  no Errors as of yet.

**Comment by devinamatthews** [comment]
That may work or it may not. MSYS2 is *like* WSL but it definitely knows and adapts to the fact that it is really on Windows. WSL on the other hand is literally Linux.

**Comment by iaincoulter** [comment]
I understand.  The only fix I can see would be to pass a flag which sets that is_win variable. Just wanted to highlight this issue should other Windows users encounter it.  I'll just stick to modifying the file for now

**Comment by devinamatthews** [comment]
If it does work let us know and we can note it in the docs.

**Comment by dnparikh** [comment]
The build system of BLIS was not designed to build a Windows .dll on a Linux system. If you are using the Windows Subsystem Linux, you should expect to build a library meant for Linux OS, not Windows.

**Comment by isuruf** [comment]
@iaincoulter was using Windows Subsystem Linux for bash only which is fine. It's good to have cross compiling support for BLIS. AFAIK, we can build a Windows .dll on a Linux system. See https://github.com/flame/blis/issues/90#issuecomment-478818051

**Comment by devinamatthews** [comment]
OK, I guess the real fix for this problem would be to also check the predefined compiler macros for a window cross-compilation toolchain. @isuruf can you suggest something simple but robust (i.e. covering WSL-on-Windows as well as cross-compilation from Linux)?

**Comment by isuruf** [comment]
`_WIN32` macro should be good for all windows compilers.

To avoid running executables, you can test whether the following compiles or not.
```
#ifdef _WIN32
int a;
#else
int a
#endif
```

**Comment by devinamatthews** [comment]
@iaincoulter please try [this branch](https://github.com/flame/blis/tree/windows-compiler-check).

**Comment by devinamatthews** [comment]
@isuruf since you've also noticed a similar problem cross-compiling on Linux can you check if the linker PR fixes it?

**Comment by isuruf** [comment]
Yes, it works. There are more errors with that cross compiling build though.
1. Needs `-fno-asynchronous-unwind-tables` (we should check `__MINGW64__` macro and add that flag)
2. Next error is,

```
x86_64-w64-mingw32-gcc -O2 -O3 -fomit-frame-pointer -mavx2 -mfma -mfpmath=sse -march=haswell -fno-asynchronous-unwind-tables -Wall -Wno-unused-function -Wfatal-errors -std=c99 -D_POSIX_C_SOURCE=200112L -Iinclude/x86_64 -I./frame/3/ -I./frame/ind/ukernels/ -I./frame/3/ -I./frame/1m/ -I./frame/1f/ -I./frame/1/ -I./frame/include -DBLIS_VERSION_STRING=\"0.8.1-17\" -DBLIS_IS_BUILDING_LIBRARY -Wl,--exclude-all-symbols -c kernels/haswell/3/sup/bli_gemmsup_rv_haswell_asm_d6x8m.c -o obj/x86_64/kernels/haswell/3/sup/bli_gemmsup_rv_haswell_asm_d6x8m.o
kernels/haswell/3/sup/bli_gemmsup_rv_haswell_asm_d6x8m.c: In function ‘bli_dgemmsup_rv_haswell_asm_6x6m’:
kernels/haswell/3/sup/bli_gemmsup_rv_haswell_asm_d6x8m.c:1763:1: error: bp cannot be used in asm here
 }
 ^
compilation terminated due to -Wfatal-errors.
Makefile:601: recipe for target 'obj/x86_64/kernels/haswell/3/sup/bli_gemmsup_rv_haswell_asm_d6x8m.o' failed
make: *** [obj/x86_64/kernels/haswell/3/sup/bli_gemmsup_rv_haswell_asm_d6x8m.o] Error 1
```

**Comment by devinamatthews** [comment]
@isuruf if it fixes basic Windows detection then I think that solves the original problem for this issue. I will move this new problem to a separate issue.

**Comment by isuruf** [comment]
Yes, it fixes the basic windows detection and I agree that we can close this issue after that PR is merged.
