### ISSUE TITLE
CC_VENDOR not being set

### ISSUE THREAD

**Issue by phesse001** [flame/blis#465]
Hello,

I recently reconfigured blis and the CC_VENDOR var seems to no longer be set.

I first ran ./configure auto (also tried ./configure zen since that is my architecture) and that finished successfully with a similar output as shown in the docs.

Then when I run make, I get:

config/zen/amd_config.mk:68: *** gcc or clang are required for this configuration..  Stop.

I do have both gcc and clang, as seen from the commands below:

(base) patrick@patrick-Virtual-Machine:~/blis$ gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(base) patrick@patrick-Virtual-Machine:~/blis$ clang --version
clang version 5.0.0 
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/patrick/miniconda3/bin

based on the amd_config.mk file it seems like this is due to CC_VENDOR not being set, however I'm not sure why that isn't being set now considering this worked before I and haven't pulled from github since my original pull when it worked.

Any help sorting this out is appreciated!

**Comment by devinamatthews** [comment]
Using `CC=clang` would be a quick workaround. BLIS looks for `GNU` in the gcc version string but I guess they changed the format. I'll look for a robust fix.

**Comment by phesse001** [comment]
Thank you, and setting the CC var explicitly did work as a quick fix

**Comment by devinamatthews** [comment]
Without CC, please send the full output of `configure`.

**Comment by phesse001** [comment]
(base) patrick@patrick-Virtual-Machine:~$ cd blis
(base) patrick@patrick-Virtual-Machine:~/blis$ ./configure auto
configure: detected Linux kernel version 5.4.0-56-generic.
configure: python interpeter search list is: python python3 python2.
configure: using 'python' python interpreter.
configure: found python version 3.7.7 (maj: 3, min: 7, rev: 7).
configure: python 3.7.7 appears to be supported.
configure: C compiler search list is: gcc clang cc.
configure: using '/home/patrick/miniconda3/bin/x86_64-conda_cos6-linux-gnu-cc' C compiler.
configure: C++ compiler search list is: g++ clang++ c++.
configure: using '/home/patrick/miniconda3/bin/x86_64-conda_cos6-linux-gnu-c++' C++ compiler (for sandbox only).
configure: found  version 1.23.0 (maj: 1, min: 23, rev: 0).
configure: checking for blacklisted configurations due to /home/patrick/miniconda3/bin/x86_64-conda_cos6-linux-gnu-cc 1.23.0.
configure: checking /home/patrick/miniconda3/bin/x86_64-conda_cos6-linux-gnu-cc 1.23.0 against known consequential version ranges.
configure: found assembler ('as') version 1.23.0 (maj: 1, min: 23, rev: 0).
configure: checking for blacklisted configurations due to as 1.23.0.
configure: reading configuration registry...done.
configure: determining default version string.
configure: found '.git' directory; assuming git clone.
configure: executing: git describe --tags.
configure: got back 0.8.0-2-g55933b6f.
configure: truncating to 0.8.0-2.
configure: starting configuration of BLIS 0.8.0-2.
configure: configuring with official version string.
configure: found shared library .so version '3.0.0'.
configure:   .so major version: 3
configure:   .so minor.build version: 0.0
configure: automatic configuration requested.
configure: hardware detection driver returned 'zen2'.
configure: checking configuration against contents of 'config_registry'.
configure: configuration 'zen2' is registered.
configure: 'zen2' is defined as having the following sub-configurations:
configure:    zen2
configure: which collectively require the following kernels:
configure:    zen2 zen haswell
configure: checking sub-configurations:
configure:   'zen2' is registered...and exists.
configure: checking sub-configurations' requisite kernels:
configure:   'zen2' kernels...exist.
configure:   'zen' kernels...exist.
configure:   'haswell' kernels...exist.
configure: no install prefix option given; defaulting to '/usr/local'.
configure: no install exec_prefix option given; defaulting to PREFIX.
configure: no install libdir option given; defaulting to EXECPREFIX/lib.
configure: no install includedir option given; defaulting to PREFIX/include.
configure: no install sharedir option given; defaulting to PREFIX/share.
configure: final installation directories:
configure:   prefix:      /usr/local
configure:   exec_prefix: ${prefix}
configure:   libdir:      ${exec_prefix}/lib
configure:   includedir:  ${prefix}/include
configure:   sharedir:    ${prefix}/share
configure: NOTE: the variables above can be overridden when running make.
configure: detected preset CFLAGS; prepending:
configure:   -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/patrick/miniconda3/include
configure: detected preset LDFLAGS; prepending:
configure:   -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/patrick/miniconda3/lib -Wl,-rpath-link,/home/patrick/miniconda3/lib -L/home/patrick/miniconda3/lib
configure: debug symbols disabled.
configure: disabling verbose make output. (enable with 'make V=1'.)
configure: disabling ARG_MAX hack.
configure: building BLIS as both static and shared libraries.
configure: exporting only public symbols within shared library.
configure: threading is disabled.
configure: requesting slab threading in jr and ir loops.
configure: internal memory pools for packing blocks are enabled.
configure: internal memory pools for small blocks are enabled.
configure: memory tracing output is disabled.
configure: libmemkind not found; disabling.
configure: compiler appears to support #pragma omp simd.
configure: the BLAS compatibility layer is enabled.
configure: the CBLAS compatibility layer is disabled.
configure: mixed datatype support is enabled.
configure: mixed datatype optimizations requiring extra memory are enabled.
configure: small matrix handling is enabled.
configure: the BLIS API integer size is automatically determined.
configure: the BLAS/CBLAS API integer size is 32-bit.
configure: configuring for conventional gemm implementation.
configure: configuring complex return type as "gnu".
configure: creating ./config.mk from ./build/config.mk.in
configure: creating ./bli_config.h from ./build/bli_config.h.in
configure: creating ./obj/zen2
configure: creating ./obj/zen2/config/zen2
configure: creating ./obj/zen2/kernels/zen2
configure: creating ./obj/zen2/kernels/zen
configure: creating ./obj/zen2/kernels/haswell
configure: creating ./obj/zen2/ref_kernels/zen2
configure: creating ./obj/zen2/frame
configure: creating ./obj/zen2/blastest
configure: creating ./obj/zen2/testsuite
configure: creating ./lib/zen2
configure: creating ./include/zen2
configure: mirroring ./config/zen2 to ./obj/zen2/config/zen2
configure: mirroring ./kernels/zen2 to ./obj/zen2/kernels/zen2
configure: mirroring ./kernels/zen to ./obj/zen2/kernels/zen
configure: mirroring ./kernels/haswell to ./obj/zen2/kernels/haswell
configure: mirroring ./ref_kernels to ./obj/zen2/ref_kernels
configure: mirroring ./ref_kernels to ./obj/zen2/ref_kernels/zen2
configure: mirroring ./frame to ./obj/zen2/frame
configure: creating makefile fragments in ./obj/zen2/config/zen2
configure: creating makefile fragments in ./obj/zen2/kernels/zen2
configure: creating makefile fragments in ./obj/zen2/kernels/zen
configure: creating makefile fragments in ./obj/zen2/kernels/haswell
configure: creating makefile fragments in ./obj/zen2/ref_kernels
configure: creating makefile fragments in ./obj/zen2/frame
configure: configured to build within top-level directory of source distribution.
(base) patrick@patrick-Virtual-Machine:~/blis$ make
config/zen/amd_config.mk:68: *** gcc or clang are required for this configuration..  Stop.
(base) patrick@patrick-Virtual-Machine:~/blis$

**Comment by devinamatthews** [comment]
It's finding gcc as `/home/patrick/miniconda3/bin/x86_64-conda_cos6-linux-gnu-cc`. Is this what you get from just `gcc` on the command line?

**Comment by devinamatthews** [comment]
Also, is Conda setting `CC` by any chance?

**Comment by phesse001** [comment]
When I run `printenv` it shows `GCC=/home/patrick/miniconda3/bin/x86_64-conda_cos6-linux-gnu-cc`. I'm not sure if Conda is setting CC but I would assume not since I'm not working within any conda env when building blis. I have a different installation of gcc in /usr/bin so when I do `export CC=/usr/bin/gcc` before configuring and calling make it works. I don't mind setting CC as I don't plan on building blis on a very routine basis so if it's something weird on my end I could just settle with this temporary solution.

**Comment by devinamatthews** [comment]
I think you're somehow getting some strange compiler, perhaps because of Conda (I hate it with a passion) or otherwise. I'll close this since setting CC manually seems to work.

**Comment by isuruf** [comment]
> I think you're somehow getting some strange compiler, perhaps because of Conda (I hate it with a passion) 

:cry: I'm one of the maintainers of the compilers for conda package manager. they are built with crosstool-ng. (https://crosstool-ng.github.io/)

**Comment by devinamatthews** [comment]
@isuruf don't take it personallt, I'm crotchetty :smile:.
