### ISSUE TITLE
Problems about specifying compiler with configure

### ISSUE THREAD

**Issue by EnigmaHuang** [flame/blis#47]
Hi, I'm trying to compile BLIS on my server, it has a Xeon E5-2620v2 core and I want to use my ICC 2016. I used the following command to configure:
`./configure CC=icc sandybridge`
But when I tried to make it, it shows that:
_config/sandybridge/make_defs.mk:84: *** gcc is required for this configuration..  Stop._
It seems that the file in configure/sandybridge did not change.
Is there anything wrong in my command?  Please help, much thanks!

**Comment by SudoNohup** [comment]
You can edit the file:
*config/sandybridge/make_defs.mk <http://make_defs.mk>*
and replace "CC             := gcc" with "CC             := icc".

More details are here:
https://github.com/flame/blis/wiki/ConfigurationHowTo

**Comment by devinamatthews** [comment]
I am currently working on extending the CC=... option to alternate 
compilers, but for now it can only be used to select a particular 
version or path of the expected compiler (in this case gcc). However, as 
Jianyu mentions, you can manually edit the compiler and flags in the 
make_defs.mk file.

Devin Matthews

**Comment by devinamatthews** [comment]
@fgvanzee why don't you leave the issue open until I actually get around to implementing this feature.

**Comment by bluss** [comment]
You can work around it for the time being using `CC_VENDOR`.

For example `make CC="ccache gcc" CC_VENDOR=gcc`. The error check is against the vendor variable.
