### ISSUE TITLE
"Illegal Instruction" on intel64

### ISSUE THREAD

**Issue by yunfeim** [flame/blis#470]
I compiled BLIS using the `intel64` option, but when I run tests with
`make check`, I get the following output:
```
Linking test_libblis.x against 'lib/intel64/libblis.a  -lm -lpthread -lrt'
Running test_libblis.x (fast) with output redirected to 'output.testsuite'
bash: line 2: 50113 Illegal instruction     (core dumped) ./test_libblis.x -g ./testsuite/input.general.fast -o ./testsuite/input.operations.fast > output.testsuite
make: *** [Makefile:834: testsuite-run-fast] Error 132
```

My machine is running
- Bash 5.0
- Make 4.2
- Python 3.8
- Ubuntu 20.04

with a 7th gen Intel i7 processor.

**Comment by yunfeim** [comment]
Actually, everything succeeds when `auto` detects the `haswell` option. Using `intel64` was the wrong choice for me. Closing because issue is resolved.

**Comment by devinamatthews** [comment]
@yunfeim Actually, if you wouldn't mind, could you send the full output of the testsuite and the contents of your /proc/cpuinfo file? Configuring with intel64 shouldn't cause an illegal instruction.

**Comment by devinamatthews** [comment]
Nvm, I can reproduce on my MBP.

**Comment by devinamatthews** [comment]
@fgvanzee the problem is that the zen kernels that get used in the haswell config seem to use non-Intel instructions. I'll try to narrow down the specific offending instruction set.

Solutions:
1. Have zen kernels compiled with Intel-compatible architecture flags when configured with intel64. I assume that when configure for haswell specifically this already happens?
2. Disable specific instruction set(s) for zen kernels.

**Comment by devinamatthews** [comment]
On further review, it may actually be something slightly different. The offending instruction is EVEX encoded which should only be enabled for AVX-512 which is definitely not zen.

**Comment by fgvanzee** [comment]
I may know what the issue is. Running `configure -c intel64` gives:
```
configure: kernel-to-config map for 'intel64':
configure:   generic: generic
configure:   haswell: skx knl haswell
configure:   knl: knl
configure:   penryn: penryn
configure:   sandybridge: sandybridge
configure:   skx: skx
configure:   zen: skx knl haswell
configure: kernel-to-config map for 'intel64' (chosen pairs):
configure:   generic:generic
configure:   haswell:haswell
configure:   knl:knl
configure:   penryn:penryn
configure:   sandybridge:sandybridge
configure:   skx:skx
configure:   zen:skx
```
Recall that the kernel-to-config map is used to determine which subconfig's compilation flags to use when compiling the kernel sets. Notice that it chooses `skx` for the 'zen' kernel set. I imagine that's not what is supposed to happen. I can try look into this later today.

Can you confirm that you see the same thing from the kernel-to-config map?

**Comment by devinamatthews** [comment]
Ah, that would do it (and yes I see the same thing). I assume this is because the kernel-to-config map for zen doesn't include zen itself, so it just chooses the first which happens to be haswell. I guess the lists should just be ordered differently so haswell is chosen?

**Comment by fgvanzee** [comment]
> Ah, that would do it (and yes I see the same thing). I assume this is because the kernel-to-config map for zen doesn't include zen itself, so it just chooses the first which happens to be haswell.

Yes, exactly.

> I guess the lists should just be ordered differently so haswell is chosen?

Actually, I think the "problem" is that the `zen` subconfig does not currently belong to the `intel64` configuration family (per the `config_registry`), but the subconfigs within the `intel64` family are trying to use `zen` kernels.

If my hunch is correct, the obvious solution is to consolidate those level-1v and -1f kernels that the other `intel64` subconfigs are trying to use into the `haswell` kernel set.

**Comment by devinamatthews** [comment]
@fgvanzee That would just create a new possible problem when trying to configure with amd64. I put a least-effort workaround in #471.

**Comment by fgvanzee** [comment]
@devinamatthews You're right; my previously mentioned solution would not work. I'm fine with your workaround for now.
