### ISSUE TITLE
build: write a pkg-config file

### ISSUE THREAD

**Issue by ajaypanyala** [flame/blis#472]
This is a request to enable writing out a `pkg-config` file when `blis` is built. This would make it easy for `CMake` projects that use `blis` to [find](https://cmake.org/cmake/help/latest/module/FindPkgConfig.html) and incorporate the `blis` configuration (`Cflags`, `libs`) appropriately. Thanks!

**Comment by devinamatthews** [comment]
@ajaypanyala I don't think anyone here uses cmake or is familiar with pkg-config. Would you be able to submit a PR?
