### ISSUE TITLE
Row/Column-Major Assumptions on Registering gemmsup Kernels

### ISSUE THREAD

**Issue by xrq-phys** [flame/blis#474]
Hello again.

I'm wondering what assumption could be made when I register a `gemmsup` kernel for, e.g., `CCR` and `CCC` with row-major preference set to `FALSE`?

In `bli_dgemmsup_rv_haswell_asm_?x8n`, **B** is assumed to have `cs_b=1`. So in its column-major counterpart should I have `rs_a=1`? Or is it that we always assumes storage only for **B** and support of column-major **A** is done by transposing row-major **B**?

Best,
Ruqing

**Comment by fgvanzee** [comment]
@xrq-phys Sorry I did not see this sooner. It sounds like you are trying to figure out how to implement and register kernels for gemmsup if the kernels are column-preferential instead of row-preferential. Is that correct?

**Comment by xrq-phys** [comment]
Sorry I forgot having opened this issue after I contacted you about `ps_a` in gemmsup kernels.
Now that `cs_b=1` assumption is clear and I can call a `rs_a=1` kernel with (B', A', C') so that it can be used as an `rv` kernel.

Column-preferential kernel seems not needed for the moment...

**Comment by fgvanzee** [comment]
> Column-preferential kernel seems not needed for the moment...

Yeah, I've not really found much evidence that one is needed over the other given that BLIS can induce a high-level transpose of the operation and convert any column-oriented problem into a row-oriented one, and vice versa. There may be subtle bandwidth-from-L2 vs bandwidth-from-L1 issues that I have yet to study closely--issues which derive from the relative imbalance between MR and NR--but to the extent that those are real things, they haven't seemed to matter yet on modern Intel or AMD systems.
