### ISSUE TITLE
Linking to blis library from appveyor on windows with gcc

### ISSUE THREAD

**Issue by phesse001** [flame/blis#475]
Hello all,

Sorry if this question has been answered, I looked through some of the docs and issues but couldn't find a clear answer.

I am trying to link to [this](https://ci.appveyor.com/project/isuruf/blis/build/job/5v6rotwcet184921/artifacts) library  from appveyor using mingw on windows. I am trying to link the lib with the test file [here](https://github.com/flame/blis/blob/master/test/test_gemm.c). Is there a build for windows using gcc that doesn't require pthreads?

I called `gcc -c -I"C:\Users\patri\CK-TOOLS\lib-blis-prebuilt-master-gcc-8.1.0-windows-64\blis\include\blis" ..\test_gemm.c -o test_gemm.o`

and got 

`fatal error: pthread.h: No such file or directory
 #include <pthread.h> // skipped
                                ^
compilation terminated.`

Really just looking if there is a way to compile with gcc on windows with this dependence on pthreads, any help appreciated!

**Comment by isuruf** [comment]
You need to install pthreads from where you got gcc. If it's MSYS2, there is a package to install from pacman. Not sure what the exact name is.

**Comment by phesse001** [comment]
Thanks! I wasn't sure the windows version of pthreads was compatible but I got it to work. I ended up just reinstalling the newest version from source forge that comes with pthreads included as an extra lib.
