### ISSUE TITLE
Compiling test file with MSVC gives a bunch of errors

### ISSUE THREAD

**Issue by phesse001** [flame/blis#480]
I read on the faq that for blis to be compatible with msvc dlls, that it must be built with clang. I downloaded the prebuilt library from appveyor [here](https://ci.appveyor.com/project/shpc/blis/build/job/ol83svu3263hgqd5/artifacts). I am on windows 10 with a zen2 arc.

I am trying to compile and run one of the test files (specifically [this](https://github.com/flame/blis/blob/master/test/test_gemm.c) one) using MSVC 2019. After I navigate to a directory above the c file, running `"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall" amd64` 
and then executing my compile line with
 `cl /c /DWINDOWS /GS- /MD /DBLAS=mkl /DBLIS_VERSION_STRING=0.8.0-9 DPOSIX_C_SOURCE=200112L /DWIN32 /I"C:\Users\patri\CK-TOOLS\lib-blis-prebuilt-clang-master-mcl-19.28.29336-windows-64\blis\include\blis"  ..\test_gemm.c  /Fetest_gemm.obj`
 I get a bunch of errors with the header file 

`Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29336 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

test_gemm.c
C:\Users\patri\CK-TOOLS\lib-blis-prebuilt-clang-master-mcl-19.28.29336-windows-64\blis\include\blis\blis.h(1837): error C2061: syntax error: identifier 'bool'
C:\Users\patri\CK-TOOLS\lib-blis-prebuilt-clang-master-mcl-19.28.29336-windows-64\blis\include\blis\blis.h(1839): error C2059: syntax error: '}'
C:\Users\patri\CK-TOOLS\lib-blis-prebuilt-clang-master-mcl-19.28.29336-windows-64\blis\include\blis\blis.h(2100): error C2061: syntax error: identifier 'mbool_t'
C:\Users\patri\CK-TOOLS\lib-blis-prebuilt-clang-master-mcl-19.28.29336-windows-64\blis\include\blis\blis.h(2106): error C2061: syntax error: identifier 'l3_sup_kers_prefs'
C:\Users\patri\CK-TOOLS\lib-blis-prebuilt-clang-master-mcl-19.28.29336-windows-64\blis\include\blis\blis.h(2106): error C2059: syntax error: ';'
C:\Users\patri\CK-TOOLS\lib-blis-prebuilt-clang-master-mcl-19.28.29336-windows-64\blis\include\blis\blis.h(2106): error C2059: syntax error: '['
C:\Users\patri\CK-TOOLS\lib-blis-prebuilt-clang-master-mcl-19.28.29336-windows-64\blis\include\blis\blis.h(2119): error C2059: syntax error: '}'
C:\Users\patri\CK-TOOLS\lib-blis-prebuilt-clang-master-mcl-19.28.29336-windows-64\blis\include\blis\blis.h(2130): error C2061: syntax error: identifier 'bool'
C:\Users\patri\CK-TOOLS\lib-blis-prebuilt-clang-master-mcl-19.28.29336-windows-64\blis\include\blis\blis.h(2134): error C2061: syntax error: identifier 'pack_a'
C:\Users\patri\CK-TOOLS\lib-blis-prebuilt-clang-master-mcl-19.28.29336-windows-64\blis\include\blis\blis.h(2134): error C2059: syntax error: ';'
C:\Users\patri\CK-TOOLS\lib-blis-prebuilt-clang-master-mcl-19.28.29336-windows-64\blis\include\blis\blis.h(2135): error C2061: syntax error: identifier 'pack_b'
C:\Users\patri\CK-TOOLS\lib-blis-prebuilt-clang-master-mcl-19.28.29336-windows-64\blis\include\blis\blis.h(2135): error C2059: syntax error: ';'
C:\Users\patri\CK-TOOLS\lib-blis-prebuilt-clang-master-mcl-19.28.29336-windows-64\blis\include\blis\blis.h(2136): error C2061: syntax error: identifier 'l3_sup'
C:\Users\patri\CK-TOOLS\lib-blis-prebuilt-clang-master-mcl-19.28.29336-windows-64\blis\include\blis\blis.h(2136): error C2059: syntax error: ';'
C:\Users\patri\CK-TOOLS\lib-blis-prebuilt-clang-master-mcl-19.28.29336-windows-64\blis\include\blis\blis.h(2146): error C2059: syntax error: '}'
C:\Users\patri\CK-TOOLS\lib-blis-prebuilt-clang-master-mcl-19.28.29336-windows-64\blis\include\blis\blis.h(4653): error C2061: syntax error: identifier 'bli_is_odd'
C:\Users\patri\CK-TOOLS\lib-blis-prebuilt-clang-master-mcl-19.28.29336-windows-64\blis\include\blis\blis.h(4653): error C2059: syntax error: ';'
C:\Users\patri\CK-TOOLS\lib-blis-prebuilt-clang-master-mcl-19.28.29336-windows-64\blis\include\blis\blis.h(4653): error C2059: syntax error: '<parameter-list>'
C:\Users\patri\CK-TOOLS\lib-blis-prebuilt-clang-master-mcl-19.28.29336-windows-64\blis\include\blis\blis.h(4658): error C2061: syntax error: identifier 'bli_is_even'
C:\Users\patri\CK-TOOLS\lib-blis-prebuilt-clang-master-mcl-19.28.29336-windows-64\blis\include\blis\blis.h(4658): error C2059: syntax error: ';'
C:\Users\patri\CK-TOOLS\lib-blis-prebuilt-clang-master-mcl-19.28.29336-windows-64\blis\include\blis\blis.h(4658): error C2059: syntax error: '<parameter-list>'
C:\Users\patri\CK-TOOLS\lib-blis-prebuilt-clang-master-mcl-19.28.29336-windows-64\blis\include\blis\blis.h(4683): error C2143: syntax error: missing ')' before '*'
C:\Users\patri\CK-TOOLS\lib-blis-prebuilt-clang-master-mcl-19.28.29336-windows-64\blis\include\blis\blis.h(4683): error C2143: syntax error: missing '{' before '*'
C:\Users\patri\CK-TOOLS\lib-blis-prebuilt-clang-master-mcl-19.28.29336-windows-64\blis\include\blis\blis.h(4683): error C2059: syntax error: ')'
C:\Users\patri\CK-TOOLS\lib-blis-prebuilt-clang-master-mcl-19.28.29336-windows-64\blis\include\blis\blis.h(4684): error C2054: expected '(' to follow 'b'
C:\Users\patri\CK-TOOLS\lib-blis-prebuilt-clang-master-mcl-19.28.29336-windows-64\blis\include\blis\blis.h(4737): error C2061: syntax error: identifier 'bli_is_aligned_to'
C:\Users\patri\CK-TOOLS\lib-blis-prebuilt-clang-master-mcl-19.28.29336-windows-64\blis\include\blis\blis.h(4737): error C2059: syntax error: ';'`

and the list continues until it stops after error count exceeds 100.

Is this a problem with the std version? I tried specifying a few different `/std`'s but without luck. Any suggestions appreciated!

**Comment by fgvanzee** [comment]
@isuruf Any ideas here? The `bool` error makes me think that maybe there a non-default C99 mode that has to be activated?

**Comment by devinamatthews** [comment]
@phesse001 yes you do need to use clang. I'm not windows expect but I think clang-cl.exe is a drop-in replacement for cl.exe that should work.

**Comment by phesse001** [comment]
Thank you, using clang-cl solved the problem
