### ISSUE TITLE
Cannot import blis into python3 code

### ISSUE THREAD

**Issue by raspi-three** [flame/blis#481]
OS: Ubuntu 18.04.5 LTS 64-bit (clean minimal install)
Memory: 31.3 GB
Processor: Intel Core i7-2600 CPU @ 3.40GHz x 8
Graphics: llvmpipe (LLVM 10.0.0, 256 bits
GNOME 3.28.2
Disk 235.2 GB
Python 3.6.9

./configure -c intel64
make
make install
Result:
Installing libblis.a into /usr/local/lib/
Installing libblis.so.3.0.0 into /usr/local/lib/
Installing blis.h into /usr/local/include/blis/
Installing config.mk common.mk into /usr/local/share/blis/
Installing config/intel64/make_defs.mk into /usr/local/share/blis/config/intel64
mkdir -p /usr/local/share/pkgconfig
Installing blis.pc into /usr/local/share/pkgconfig/
install -c -m 0644 blis.pc /usr/local/share/pkgconfig

Proplem:
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
<code>
>>> import blis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'blis'
>>> 
</code>

**Comment by devinamatthews** [comment]
@raspi-three BLIS does not have a native Python package. However, you might be able to use it as a BLAS backend for NumPy.
