### ISSUE TITLE
mismatch lsame signature between blis and flame

### ISSUE THREAD

**Issue by stefanozampini** [flame/blis#496]
I need cblas and lapacke for a project, and I have configured BLIS as (probably pools and threading are not influential)

`./configure --enable-blas --enable-cblas --enable-pba-pools --enable-sba-pools  --enable-threading=openmp zen2`

and libflame as

`./configure CFLAGS="-march=znver2 -Wno-maybe-uninitialized" --enable-internal-error-checking=none --enable-lapack2flame --enable-max-arg-list-hack --enable-external-lapack-interfaces --enable-cblas-interfaces`

There is a conflct of declaration when including

```
#include <blis.h>
#include <lapacke.h>
```

I have encountered this issue using the amd forks, but the same happen using this repository,

```
/home/zampins/amd/src/local/include/lapack.h:101:36: error: conflicting declaration of C function ‘int lsame_(char*, char*, int, int)’
  101 | #define LAPACK_lsame LAPACK_GLOBAL(lsame,LSAME)
      |                                    ^~~~~
/home/zampins/amd/src/local/include/lapacke_mangling.h:12:39: note: in definition of macro ‘LAPACK_GLOBAL’
   12 | #define LAPACK_GLOBAL(lcname,UCNAME)  lcname##_
      |                                       ^~~~~~
/home/zampins/amd/src/local/include/lapack.h:102:16: note: in expansion of macro ‘LAPACK_lsame’
  102 | lapack_logical LAPACK_lsame( char* ca,  char* cb,
      |                ^~~~~~~~~~~~
In file included from /home/zampins/amd/h2opus/include/h2opus/util/blas_wrappers.h:242,
                 from /home/zampins/amd/h2opus/include/h2opus/util/batch_wrappers.h:13,
                 from src/core/hara_weak_util.cxx:6:
/home/zampins/amd/src/local/include/blis/blis.h:39716:32: note: previous declaration ‘int lsame_(const char*, const char*, int, int)’
39716 | BLIS_EXPORT_BLAS int PASTEF770(lsame)(const char *ca, const char *cb, int ca_len, int cb_len);
```

**Comment by devinamatthews** [comment]
@stefanozampini a similar (if not the same) issue came up recently, but for the life of me I can't find it. @fgvanzee do you remember?

**Comment by fgvanzee** [comment]
@devinamatthews Are you thinking of [this from issue 145](https://github.com/flame/blis/issues/145#issuecomment-822664392)?

**Comment by devinamatthews** [comment]
That's the one. @stefanozampini does the solution there work for you? Also, if you're only using the CBLAS/LAPACKe interface then you can skip the blis.h include.

**Comment by stefanozampini** [comment]
Thanks. That worked
