### ISSUE TITLE
Sandybridge OpenMP Failure

### ISSUE THREAD

**Issue by EnigmaHuang** [flame/blis#52]
Hi,

I compiled BLIS on my server(CentOS 7.1, gcc 4.8.5, 2*Xeon E5-2620v2), but it seems that BLIS can just use single thread. I used the command 

```
./configure sandybridge
make -j
make install
```

to compile and install. I didn't change any file in config/sandybridge. I checked that 

```
#define BLIS_ENABLE_OPENMP
```

is uncommented in bli_config.h, so it should be able to use OpenMP. Then I used the makefile in wiki/BuildSystem#linking-against-blis section and added -fopenmp flag to compile the test program. However the program is single-threaded. I also tried to use the script below to test the program but it still failed to use OpenMP

```
export OMP_NUM_THREADS=12
make -f BLIS-Makefile
./testBLIS.x 
```

I tried to use
···
 #define BLIS_ENABLE_PTHREAD
···
instead of OpenMP setting, but it still fail. 

What should I do to use OpenMP?

**Comment by Maratyszcza** [comment]
You should set `BLIS_JC_NT`, `BLIS_IC_NT`, `BLIS_JR_NT`, `BLIS_IR_NT` environment variables to specify multi-threading along each internal blocking dimension. See [BLIS wiki:multithreading](https://github.com/flame/blis/wiki/Multithreading)

**Comment by EnigmaHuang** [comment]
I thought it has a default setting so I did not set it, now it works. Thanks!
