### ISSUE TITLE
Haswell kernels lost vzeroupper at some point

### ISSUE THREAD

**Issue by devinamatthews** [flame/blis#523]
"Old" haswell kernels has vzeroupper to avoid penalty when mixed with legacy SSE code. For some reason, the current kernels don't have this anymore. AFAICT the compiler does **not** insert this automatically so we should put it back in.

**Comment by fgvanzee** [comment]
I see `vzeroall` used instead. Does that not avoid the penalty as well?

**Comment by devinamatthews** [comment]
That's at the beginning. vzeroupper has to be the last (VEX) instruction.

**Comment by fgvanzee** [comment]
Gotcha. I was confused and had forgotten about the trailing `vzeroupper` instructions. Yes, those should go back in.
