### ISSUE TITLE
Crash when re-initialized after finalized

### ISSUE THREAD

**Issue by lschork2** [flame/blis#525]
When `bli_finalize()` is called, then it is not possible to re-initialize the library with `bli_init()`. Doing so causes a crash in the next call to `bli_dgemm()`. The code snippet below is a working example to reproduce this.

It would be useful to allow re-initializing the library after it has been finalized.  In our application we would like to deallocate the memory after part of the computation is finished, and reallocate later if needed for another part.

```
#include "blis.h"

static void do_work()
{
  enum {DIM_M = 4, DIM_N = 5, DIM_K = 3};
  double a[DIM_M*DIM_K], b[DIM_K*DIM_N], c[DIM_M*DIM_N];
  double zero = 0.0, one = 1.0, alpha = 2.0, beta = 3.0;
  const int m = DIM_M;
  const int n = DIM_N;
  const int k = DIM_K;
  const int csa = m;
  const int csb = k;
  const int csc = m;
  const int rsa = 1;
  const int rsb = 1;
  const int rsc = 1;

  bli_drandm(0, BLIS_DENSE, m, k, a, rsa, csa);
  bli_dsetm(BLIS_NO_CONJUGATE, 0, BLIS_NONUNIT_DIAG, BLIS_DENSE,
            k, n, &one, b, rsb, csb);
  bli_dsetm(BLIS_NO_CONJUGATE, 0, BLIS_NONUNIT_DIAG, BLIS_DENSE,
            m, n, &zero, c, rsc, csc);

  bli_dgemm(BLIS_NO_TRANSPOSE, BLIS_NO_TRANSPOSE,
            m, n, k, &alpha, a, rsa, csa, b, rsb, csb,
            &beta, c, rsc, csc);
  bli_dprintm("c: after gemm", m, n, c, rsc, csc, "%4.1f", "");
}

int main()
{

  bli_init();
  do_work();
  bli_finalize();

  bli_init();
  do_work();
  bli_finalize();

  return 0;
}
```

**Comment by fgvanzee** [comment]
Thanks for this report, @lschork2. It was definitely my intention for BLIS to be able to be finalized and then re-initialized. I'll look into this.

**Comment by fgvanzee** [comment]
Oh dear lord, `pthread_once()` isn't yet done mocking us.

Of *course* it fails. The current init/finalization model means `bli_init()` and `bli_finalize()` will be called exactly once. Not just by one thread, but *once*.

The reason @lschork2's code example results in a segfault is because the second time around, BLIS is refusing to initialize itself. Lol.

@devinamatthews How did we not see this coming?

FWIW, this would be fixed in my error checking refactor since that code totally rewrites the initialization/finalization steps. I'll start thinking about workarounds for the current code base. (I'm open to suggestions.)

**Comment by devinamatthews** [comment]
If you can be sure it is happening in a single-threaded or otherwise thread-safe region then you could set the control variable back to `PTHREAD_ONCE_INIT`.

**Comment by fgvanzee** [comment]
I suppose we could make that an API call. Something like `bli_reinit()`, which resets the control variables *and* calls `bli_init()`. That would allow us to document the single-threaded assumption in the documentation for `bli_reinit()`.

I also like this because it semantically communicates that re-initialization is distinctly different than first-time initialization.

**Comment by fgvanzee** [comment]
@lschork2 Would your applicable be able to work with the following:
```
  bli_init();
  do_work();
  bli_finalize();

  bli_reinit();    // Instead of bli_init().
  do_work();
  bli_finalize();
```
And would this part of your application be single-threaded?

**Comment by devinamatthews** [comment]
Why wouldn't that be part of `bli_finalize()`?

**Comment by devinamatthews** [comment]
Single-threaded (or thread-safe, i.e. locked) is necessary because you wouldn't want to change the control variable while another thread is calling pthread_once etc.

**Comment by hominhquan** [comment]
Oh, this a a tricky and interesting one. I like the idea of @devinamatthews, how about adding this:
```c
void bli_init_apis( void )
{
	...
	once_finalize = BLIS_PTHREAD_ONCE_INIT;
}

void bli_finalize_apis( void )
{
	...
	once_init     = BLIS_PTHREAD_ONCE_INIT;
}
```

`bli_finalize()` to rearm `bli_init()`, and `bli_init()` to rearm `bli_finalize()`

**Comment by devinamatthews** [comment]
I like @hominhquan's idea. It has symmetry.

**Comment by fgvanzee** [comment]
> I like @hominhquan's idea. It has symmetry.

I agree. I had actually thought of this, but dismissed it before realizing that we pretty much have to be guaranteed that the caller is single-threaded.

**Comment by fgvanzee** [comment]
Please give the latest commit a try, @lschork2.

Thanks @hominhquan and @devinamatthews for your help fixing this.

**Comment by fgvanzee** [comment]
@devinamatthews Can you take a look at this [clang-on-OSX Travis CI failure](https://travis-ci.com/github/flame/blis/builds/234536010)? The first signs of trouble are in `configure`:
```
$ $DIST_PATH/configure -p `pwd`/../install -t $THR CC=$CC $CONF
configure: detected Darwin kernel version 17.7.0.
configure: python interpeter search list is: python python3 python2.
configure: using 'python' python interpreter.
configure: found python version 2.7.17 (maj: 2, min: 7, rev: 17).
configure: python 2.7.17 appears to be supported.
configure: C compiler search list is: gcc clang cc.
configure: using 'clang' C compiler.
configure: C++ compiler search list is: g++ clang++ c++.
configure: using 'g++' C++ compiler (for sandbox only).
./configure: line 1446: [: too many arguments
configure: found clang version  (maj: , min: , rev: ).
configure: checking for blacklisted configurations due to clang .
./configure: line 1577: [: -lt: unary operator expected
./configure: line 1580: [: -eq: unary operator expected
./configure: line 1593: [: -lt: unary operator expected
configure: checking clang  against known consequential version ranges.
```

**Comment by devinamatthews** [comment]
line 1425 change `clang version` to `(clang|LLVM) version`.

**Comment by lschork2** [comment]
Thanks for the fix. It works with our application.

**Comment by fgvanzee** [comment]
> line 1425 change `clang version` to `(clang|LLVM) version`.

It's actually [still failing](https://travis-ci.com/github/flame/blis/jobs/529440697), but for a reason that seemingly had nothing to do with the `configure` issue:
```
Compiling obj/sandybridge/frame/base/bli_init.o ('sandybridge' CFLAGS for framework code)
frame/base/bli_init.c:95:18: fatal error: expected expression

        once_finalize = BLIS_PTHREAD_ONCE_INIT;
                        ^
include/sandybridge/blis.h:1554:40: note: expanded from macro 'BLIS_PTHREAD_ONCE_INIT'
#define BLIS_PTHREAD_ONCE_INIT         PTHREAD_ONCE_INIT
                                       ^
/usr/include/pthread.h:210:27: note: expanded from macro 'PTHREAD_ONCE_INIT'
#define PTHREAD_ONCE_INIT {_PTHREAD_ONCE_SIG_init, {0}}
                          ^
1 error generated.
make: *** [obj/sandybridge/frame/base/bli_init.o] Error 1
make: *** Waiting for unfinished jobs....
```
Does the `= { ... };` `struct` assignment notation only work when initializing at declaration time?

**Comment by devinamatthews** [comment]
In C yes, unless maybe you cast? You can always just create a local variable with the initializer then memcpy it. No it's not "POSIX standard" but I am hard-pressed to imagine a universe in which it wouldn't work.

**Comment by fgvanzee** [comment]
Do we have to use `memcpy()` though? Is there any issue with using the following approach based on `=`?
```c
void bli_init_apis( void )
{
    ...
    // Reset the control variable that will allow finalization.
    bli_pthread_once_t once_new = BLIS_PTHREAD_ONCE_INIT;
    once_finalize = once_new;
}

```

**Comment by devinamatthews** [comment]
I think this is fine.

**Comment by fgvanzee** [comment]
Yay it works.

**Comment by fgvanzee** [comment]
> Thanks for the fix. It works with our application.

I'm glad we were able to help. Please stay in touch.
