### ISSUE TITLE
Blis on windows with AVX512 hangs indefinitely in scipy test suite

### ISSUE THREAD

**Issue by h-vetinari** [flame/blis#526]
Before fixing #154, the scipy test-suite used to fail with ~440 errors (see e.g. [here](https://github.com/conda-forge/scipy-feedstock/pull/172#issuecomment-870917701)).

Running the same thing with a new build that includes #522, the test suite now hangs indefinitely (and reproducibly so): There are some failures right before which might provide a clue, but so far all I see is:
```
[...]
fftpack/tests/test_real_transforms.py::Test_DCTN_IDCTN::test_shape_is_none_with_axes[axes5-dctn-idctn] PASSED [ 12%]
fftpack/tests/test_real_transforms.py::Test_DCTN_IDCTN::test_shape_is_none_with_axes[axes5-dstn-idstn] PASSED [ 12%]
integrate/_ivp/tests/test_ivp.py::test_integration FAILED                [ 12%]
integrate/_ivp/tests/test_ivp.py::test_integration_complex FAILED        [ 12%]
integrate/_ivp/tests/test_ivp.py::test_integration_sparse_difference FAILED [ 12%]
integrate/_ivp/tests/test_ivp.py::test_integration_const_jac FAILED      [ 12%]
integrate/_ivp/tests/test_ivp.py::test_integration_stiff[Radau] PASSED   [ 12%]
[hangs here indefinitely]
```

**Comment by devinamatthews** [comment]
Can you get a backtrace on the hang?

**Comment by h-vetinari** [comment]
Hey, thanks for the very quick response!

Getting a backtrace is not so easy from the CI, and I don't have AVX512 hardware to run this on myself.

However, maybe looking at the 4 failed tests might already start to give some clues? Haven't dug into that yet.

**Comment by h-vetinari** [comment]
Just recording for myself the instructions I just stumbled over for how to run python in Intel SDE:

> ### run tests
> 
> To test on a machine that does not support AVX-512, one may use [Intel® SDE](https://software.intel.com/content/www/us/en/develop/articles/pre-release-license-agreement-for-intel-software-development-emulator-accept-end-user-license-agreement-and-download.html).
> 
> ```batchfile
> sde.exe -- python tests\utils\stl-lit\stl-lit.py -v ..\..\tests\std\tests\GH_000814_avx512_vector_algorithms
> ```

**Comment by devinamatthews** [comment]
> Just recording for myself the instructions I just stumbled over for how to run python in Intel SDE:

I can only imagine how slow it must be :smile:.

**Comment by h-vetinari** [comment]
As of the most recent run, this hang does not appear anymore. Not sure what caused this, but in the meantime this can be closed.

There is one "relatively" bad tolerance violation on linux + x64 + non-avx512 - would you like to have an issue for that @devinamatthews?

**Comment by devinamatthews** [comment]
@h-vetinari if it can be reduced to a small, reproducible test case (BLAS only) then yes. Otherwise is will be impossible to isolate the cause.

**Comment by h-vetinari** [comment]
Well, we've covered above that it would be possible in principle to run python in Intel SDE. And since this is only one test, it might be doable.

In any case, I think I'll open the issue, and then we can see if the python-version can be distilled down further to the underlying blas calls.

**Comment by jeffhammond** [comment]
> > Just recording for myself the instructions I just stumbled over for how to run python in Intel SDE:
> 
> 
> 
> I can only imagine how slow it must be :smile:.

SDE only emulates instructions that fault so it should not be too bad. But it's probably better to run in GDB and backtrack the fault first.
