### ISSUE TITLE
ARMSVE blacklist for Clang 10 and lower

### ISSUE THREAD

**Issue by devinamatthews** [flame/blis#535]
The `armsve` config should be added to the blacklist for clang 10 and lower, as ARM SVE intrinsics support (used in the packm kernels) is only in clang11+. I am checking on gcc...

**Comment by devinamatthews** [comment]
@fgvanzee you can probably handle this quite easily.

**Comment by fgvanzee** [comment]
I'll wait until you finish checking for gcc.

**Comment by devinamatthews** [comment]
gcc 10+ required

**Comment by fgvanzee** [comment]
Okay, so disallow `armsve` for clang10 and older, and gcc 9 and older?

**Comment by devinamatthews** [comment]
Yes. I don't know if this affects A64fx because it is only the intrinsics. @xrq-phys ?

**Comment by fgvanzee** [comment]
@devinamatthews Do I need to also add the `armsve` blacklisting to the `"Apple"` branch of the `clang` conditional handling?

**Comment by devinamatthews** [comment]
No.

**Comment by devinamatthews** [comment]
I believe this is fixed nowl
