### ISSUE TITLE
All dcomplex 1m operations fail for mixed row/col dgemm ukrs

### ISSUE THREAD

**Issue by devinamatthews** [flame/blis#557]
When the sgemm microkernel is row-major and the dgemm microkernel is column-major or vice versa, all dcomplex 1m operations fail. I guess the row/column preference is being read from the wrong precision?

The problem is reproduced in [this branch](https://github.com/flame/blis/tree/1m_row_col_problem) for `haswell`.

**Comment by fgvanzee** [comment]
Le sigh. I'll investigate.
