### ISSUE TITLE
support LLVM OpenMP

### ISSUE THREAD

**Issue by jeffhammond** [flame/blis#56]
`OpenMP is not supported with Clang` in the build system has been false [http://blog.llvm.org/2015/05/openmp-support_22.html](for almost a year now).  While Mac does not appear to support it in the default toolchain, I've been using Homebrew's `clang-omp` just fine.

I think that the BLIS build system should test for OpenMP support "the old fashioned way" (i.e. like `configure` does) and use OpenMP if it is available.

**Comment by devinamatthews** [comment]
Yeah, it totally should, but I'm going in baby steps.

**Comment by jeffhammond** [comment]
I only added this issue because having children broke my photographic memory skills and I use Github for out-of-core storage - don't feel any pressure to address it soon.

**Comment by jeffhammond** [comment]
I don't know why the github hook did not close this issue automatically, but it should have happened.

**Comment by devinamatthews** [comment]
The PR has to be accepted first.
