### ISSUE TITLE
error: ‘asm’ operand has impossible constraints

### ISSUE THREAD

**Issue by chengguosun** [flame/blis#595]
hi,
i compiled the latest blis with gcc7.2, but there was an error as shown below:

> kernels/haswell/3/bli_gemm_haswell_asm_d6x8.c: In function ‘bli_sgemm_haswell_asm_6x16’:
>  ./frame/include/bli_x86_asm_macros.h:102:21: error: ‘asm’ operand has impossible 
>  #define BEGIN_ASM() __asm__ volatile (

i found this error caused by "__attribute__((aligned(BLIS_STACK_BUF_ALIGN_SIZE)))" in bli_edge_case_macro_defs.h, if i delete this line, compilation passed.

if i compile blis with gcc8.5, it passes with no errors. so, I think this may be related to compiler optimization.

**Comment by chengguosun** [comment]
another problem:
there is "GEMM_UKR_SETUP_CT( s, 16, 6, true );" in bli_gemm_haswell_asm_d8x6.c, Shouldn't it be "GEMM_UKR_SETUP_CT( s, 16, 6, false );"?

**Comment by devinamatthews** [comment]
> another problem:
> there is "GEMM_UKR_SETUP_CT( s, 16, 6, true );" in bli_gemm_haswell_asm_d8x6.c, Shouldn't it be "GEMM_UKR_SETUP_CT( s, 16, 6, false );"?

Yes, good catch. This kernel isn't actually used ATM so that slipped through.

**Comment by devinamatthews** [comment]
Hmmm... the alignment restriction isn't technically necessary for Haswell. I could add another macro for an unaligned buffer although it's a bit hackish.

**Comment by devinamatthews** [comment]
@chengguosun please test if the linked PR fixes the problem.

**Comment by chengguosun** [comment]
@devinamatthews yes, the test passed without any problems, thanks.

**Comment by ivan23kor** [comment]
@devinamatthews this issue still exists on some `skx` CPUs.

Unfortunately, I could not reproduce the issue on my `skx` machine and all I have is [this log](https://github.com/ivan23kor/yaconv/issues/1#issuecomment-1833345854).

Looks like the macros are using alignment for *gemm edge cases in [the BLIS version I am using](https://github.com/ivan23kor/blis/tree/yaconv).

Any idea what is wrong?

**Comment by devinamatthews** [comment]
Does that fork incorporate 7a8e580? If not then you could try just editing `GEMM_UKR_SETUP_CT_PRE` to remove the alignment attribute.

**Comment by ivan23kor** [comment]
Yes, the fork incorporates https://github.com/flame/blis/commit/7a8e580bfa17fce3ea00c575b1a0334900d95a33
