### ISSUE TITLE
Error when compiling BLIS with A64FX

### ISSUE THREAD

**Issue by SAbdulah** [flame/blis#598]
I am using Fujitsu C/C++ Compiler 4.6.1  simulating gcc version 6.1 to compile `BLIS` on an A64FX chip. Through cross-compile, this is the command I am using:

`cc=fccpx CC=FCCpx ./configure  --prefix=$PWD/blis_install a64fx`

I am getting some warning and some errors as follow,  

"kernels/armsve/1m/bli_dpackm_armsve512_asm_16xk.c", line 69: error: a value of type "unsigned long" cannot be assigned to an entity of type "double *"
              p = ( (uint64_t)0x1 << 56 ) | (uint64_t)p;
                ^
"kernels/armsve/1m/bli_dpackm_armsve512_asm_16xk.c", line 71: error: a value of type "unsigned long" cannot be assigned to an entity of type "double *"
              p = ( (uint64_t)0x2 << 56 ) | (uint64_t)p;

**Comment by devinamatthews** [comment]
Please use `CC=fccpx CXX=FCCpx`.
