### ISSUE TITLE
arm64 config error

### ISSUE THREAD

**Issue by ajaypanyala** [flame/blis#606]
Am trying to build BLIS with `config=arm64` and see the following error

`config/arm64/make_defs.mk:71: *** gcc or clang is required for this configuration..  Stop.`

```
armclang --version
Arm C/C++/Fortran Compiler version 20.3 (build number 543) (based on LLVM 9.0.1)
Target: aarch64-unknown-linux-gnu
```

**Comment by devinamatthews** [comment]
@fgvanzee I guess we need to update the parsing to treat this as clang X.Y.Z as indicated in the "based on"?

**Comment by fgvanzee** [comment]
Thanks for taking care of this.
