### ISSUE TITLE
Integrate armsve in arm64 family : runtime detection and kernel selection

### ISSUE THREAD

**Issue by egaudry** [flame/blis#612]
I believe the current arm64 config option will not include the armsve kernels.
```
configure: configuration 'arm64' is registered.
configure: 'arm64' is defined as having the following sub-configurations:
configure:    firestorm thunderx2 cortexa57 cortexa53 generic
configure: which collectively require the following kernels:
configure:    armv8a generic
configure: checking sub-configurations:
configure:   'firestorm' is registered...and exists.
configure:   'thunderx2' is registered...and exists.
configure:   'cortexa57' is registered...and exists.
configure:   'cortexa53' is registered...and exists.
configure:   'generic' is registered...and exists.
```

With new processors getting on the market, with SVE, it might be interesting to include the armsve optimization in the arm64 family, and to support the detection of sve at runtime.

@devinamatthews @jeffhammond

**Comment by devinamatthews** [comment]
@xrq-phys @fgvanzee IIRC the previous problem with including `armsve` in `arm64` was the need to use newer compilers? I think this is fixed now with clang/gcc version detection, right?

**Comment by xrq-phys** [comment]
Confirmed working. Raising PR.
