### ISSUE TITLE
bli_gemm_8x8.h?

### ISSUE THREAD

**Issue by chiensh** [flame/blis#63]
1) I attempted to build BLIS version 0.2.0 on bgq, but I found this error
"./config/bgq/bli_kernel.h", line 174.10: 1506-296 (S) #include file "bli_gemm_8x8.h" not found.

and I check the file "bli_kernel.h" for bgq, line 174 contains 
#include "bli_gemm_8x8.h"

but I cannot locate this header file anywhere in the package.

2) For my previous ticket "BLIS Test Failure in BlueGene/Q #34", is there any follow up? seems that BLIS still not working correctly for all complex test cases. 

3) Is there any instruction to build LAPACK to work with BLIS? 

Thanks!

**Comment by fgvanzee** [comment]
Thanks for this bug report. I'll try to address this later today. (It should be a straightforward fix.)

**Comment by fgvanzee** [comment]
This should be fixed now in f756dbf. Let me know if anything else appears broken.
