### ISSUE TITLE
More compilation error on  BG/Q

### ISSUE THREAD

**Issue by chiensh** [flame/blis#64]
I got another error when I attempt to compile the latest version (0.2) for BG/Q 

(1) Undeclared identifier bli_daxpyf_fusefac
_Compiling ../config/bgq/kernels/1f/bli_axpyf_opt_var1.c (NOTE: using flags for kernels)
"../config/bgq/kernels/1f/bli_axpyf_opt_var1.c", line 57.20: 1506-045 (S) Undeclared identifier bli_daxpyf_fusefac.
"../config/bgq/kernels/1f/bli_axpyf_opt_var1.c", line 64.39: 1506-098 (E) Missing argument(s).
make: *** [obj/bgq/config/kernels/1f/bli_axpyf_opt_var1.o] Error 1_

in file ./config/bgq/kernels/1f/bli_axpyf_opt_var1.c, line 57

_if ( b_n < PASTEMAC(d,axpyf_fusefac) || inca != 1 || incx != 1 || incy != 1 || bli_is_unaligned_to( a, 32 ) || bli_is_unaligned_to( y, 32 ) )
                use_ref = TRUE;_

I cannot find where "axpyf_fusefac" is, so I simply comment out this line to call the reference DAXPYF function

(2) More error in bli_gemm_int_8x8.c 
But when I commented out the line 57, I got a bunch of  error messages in bli_gemm_int_8x8.c:

_Compiling ../config/bgq/kernels/3/bli_gemm_int_8x8.c (NOTE: using flags for kernels)_
_"../config/bgq/kernels/3/bli_gemm_int_8x8.c", line 133.28: 1506-754 (S) The parameter type is not valid for a function of this linkage type.
"../config/bgq/kernels/3/bli_gemm_int_8x8.c", line 134.28: 1506-754 (S) The parameter type is not valid for a function of this linkage type.
...
"../config/bgq/kernels/3/bli_gemm_int_8x8.c", line 231.28: 1506-045 (S) Undeclared identifier c_z.
"../config/bgq/kernels/3/bli_gemm_int_8x8.c", line 262.14: 1506-754 (S) The parameter type is not valid for a function of this linkage type.
"../config/bgq/kernels/3/bli_gemm_int_8x8.c", line 263.14: 1506-754 (S) The parameter type is not valid for a function of this linkage type.
"../config/bgq/kernels/3/bli_gemm_int_8x8.c", line 264.14: 1506-754 (S) The parameter type is not valid for a function of this linkage type.
"../config/bgq/kernels/3/bli_gemm_int_8x8.c", line 265.14: 1506-754 (S) The parameter type is not valid for a function of this linkage type.
"../config/bgq/kernels/3/bli_gemm_int_8x8.c", line 267.14: 1506-754 (S) The parameter type is not valid for a function of this linkage type.
"../config/bgq/kernels/3/bli_gemm_int_8x8.c", line 268.14: 1506-754 (S) The parameter type is not valid for a function of this linkage type.
"../config/bgq/kernels/3/bli_gemm_int_8x8.c", line 302.19: 1506-196 (S) Initialization between types "double" and "struct {...}" is not allowed.
"../config/bgq/kernels/3/bli_gemm_int_8x8.c", line 303.19: 1506-196 (S) Initialization between types "double" and "struct {...}" is not allowed.
"../config/bgq/kernels/3/bli_gemm_int_8x8.c", line 304.18: 1506-196 (S) Initialization between types "double" and "struct {...}" is not allowed.
"../config/bgq/kernels/3/bli_gemm_int_8x8.c", line 305.18: 1506-196 (S) Initialization between types "double" and "struct {...}" is not allowed.
"../config/bgq/kernels/3/bli_gemm_int_8x8.c", line 362.5: 1506-068 (S) Operation between types "double" and "struct {...}" is not allowed.
"../config/bgq/kernels/3/bli_gemm_int_8x8.c", line 362.5: 1506-068 (S) Operation between types "double" and "struct {...}" is not allowed.
"../config/bgq/kernels/3/bli_gemm_int_8x8.c", line 362.5: 1506-068 (S) Operation between types "double" and "struct {...}" is not allowed.
"../config/bgq/kernels/3/bli_gemm_int_8x8.c", line 362.5: 1506-068 (S) Operation between types "double" and "struct {...}" is not allowed.
..._

**Comment by fgvanzee** [comment]
@chiensh I've fixed the axpyf issue. However, I don't know what is causing the other issue inside the gemm ukernel file. This *may* have something to do with some changes that @devinamatthews made to the build system recently. We'll have to look into it further.

**Comment by chiensh** [comment]
**Thank you, I got another error in "../config/bgq/kernels/1f/bli_axpyf_opt_var1.c", which is caused by missing an "(" in the statement in line 59**

_[chiensh@cumulus tmp]$ make
...
"../config/bgq/kernels/1f/bli_axpyf_opt_var1.c", line 59.29: 1506-275 (S) Unexpected text '||' encountered.
..._

**After I fixed this problem, I still hit the problem in "../config/bgq/kernels/3/bli_gemm_int_8x8.c"  that I mentioned before:**

_Compiling ../config/bgq/kernels/3/bli_gemm_int_8x8.c (NOTE: using flags for kernels)
"../config/bgq/kernels/3/bli_gemm_int_8x8.c", line 133.28: 1506-754 (S) The parameter type is not valid for a function of this linkage type.
"../config/bgq/kernels/3/bli_gemm_int_8x8.c", line 134.28: 1506-754 (S) The parameter type is not valid for a function of this linkage type.
"../config/bgq/kernels/3/bli_gemm_int_8x8.c", line 215.6: 1506-343 (S) Redeclaration of bli_zgemm_int_8x8 differs from previous declaration on line 54 of "../frame/3/bli_l3_ukr.h".
"../config/bgq/kernels/3/bli_gemm_int_8x8.c", line 227.12: 1506-334 (S) Identifier alpha has already been defined on line 218 of "../config/bgq/kernels/3/bli_gemm_int_8x8.c".
"../config/bgq/kernels/3/bli_gemm_int_8x8.c", line 227.32: 1506-045 (S) Undeclared identifier alpha_z.
"../config/bgq/kernels/3/bli_gemm_int_8x8.c", line 228.12: 1506-334 (S) Identifier beta has already been defined on line 221 of "../config/bgq/kernels/3/bli_gemm_int_8x8.c".
"../config/bgq/kernels/3/bli_gemm_int_8x8.c", line 228.32: 1506-045 (S) Undeclared identifier beta_z.
"../config/bgq/kernels/3/bli_gemm_int_8x8.c", line 229.12: 1506-334 (S) Identifier a has already been defined on line 219 of "../config/bgq/kernels/3/bli_gemm_int_8x8.c".
"../config/bgq/kernels/3/bli_gemm_int_8x8.c", line 229.28: 1506-045 (S) Undeclared identifier a_z.
"../config/bgq/kernels/3/bli_gemm_int_8x8.c", line 230.12: 1506-334 (S) Identifier b has already been defined on line 220 of "../config/bgq/kernels/3/bli_gemm_int_8x8.c".
"../config/bgq/kernels/3/bli_gemm_int_8x8.c", line 230.28: 1506-045 (S) Undeclared identifier b_z.
"../config/bgq/kernels/3/bli_gemm_int_8x8.c", line 231.12: 1506-334 (S) Identifier c has already been defined on line 222 of "../config/bgq/kernels/3/bli_gemm_int_8x8.c".
"../config/bgq/kernels/3/bli_gemm_int_8x8.c", line 231.28: 1506-045 (S) Undeclared identifier c_z.
..._

**Comment by fgvanzee** [comment]
@chiensh Okay, I fixed a big chunk of the errors, I think. Please let me know what is left.

**Comment by chiensh** [comment]
**I think there are still some problem left to be fixed:**

_configure: creating makefile fragment in ../frame/ind/ukernels/trsm
configure: creating makefile fragment in ../frame/util
configure: creating symbolic link to Makefile.
configure: creating symbolic link to common.mk.
configure: configured to build outside of source distribution.
[chiensh@cumulus tmp]$ make
Compiling ../config/bgq/kernels/1/bli_axpyv_opt_var1.c (NOTE: using flags for kernels)
Compiling ../config/bgq/kernels/1/bli_dotv_opt_var1.c (NOTE: using flags for kernels)
Compiling ../config/bgq/kernels/1f/bli_axpyf_opt_var1.c (NOTE: using flags for kernels)
Compiling ../config/bgq/kernels/3/bli_gemm_int_8x8.c (NOTE: using flags for kernels)
"../config/bgq/kernels/3/bli_gemm_int_8x8.c", line 133.28: 1506-754 (S) The parameter type is not valid for a function of this linkage type.
"../config/bgq/kernels/3/bli_gemm_int_8x8.c", line 134.28: 1506-754 (S) The parameter type is not valid for a function of this linkage type.
"../config/bgq/kernels/3/bli_gemm_int_8x8.c", line 300.21: 1506-021 (S) Expecting struct or union.
"../config/bgq/kernels/3/bli_gemm_int_8x8.c", line 301.21: 1506-021 (S) Expecting struct or union.
"../config/bgq/kernels/3/bli_gemm_int_8x8.c", line 302.21: 1506-021 (S) Expecting struct or union.
"../config/bgq/kernels/3/bli_gemm_int_8x8.c", line 303.21: 1506-021 (S) Expecting struct or union.
make: *** [obj/bgq/config/kernels/3/bli_gemm_int_8x8.o] Error 1_

**Comment by fgvanzee** [comment]
@chiensh Thanks for your feedback. I've integrated your fixes into eb2f18e. Please give it a try and confirm that it works for you.

**Comment by chiensh** [comment]
@fgvanzee, Thank You!

I think we can consider this issue closed; now it falls back to the problem reported in #34:
excepted many complex test cases, e.g cgemm4,  zgemm4, are fail, other tests are passed. 

However, I build the BLAS to BLIS interface, but it is failure in most of the cases in the netlib BLAS test suite that comes with LAPACK. I will further investigate and report this as another issue.
