### ISSUE TITLE
"configure auto" results in an error for users with a Mac M1 Pro processor

### ISSUE THREAD

**Issue by cgebhart-lbl** [flame/blis#672]
The specific error is: 
```
./frame/base/bli_cpuid.c:1182:6: error: use of undeclared identifier 'has_sve'
```
configure appears to work correctly if "arm32" or "arm64" are specified manually.

Update: it seems that `configure arm64` led to a failure when the user tried to do `make install`:

`Generated include/arm64/blis.h
Compiling obj/arm64/config/armsve/bli_cntx_init_armsve.o ('armsve' CFLAGS for config code)
config/armsve/bli_cntx_init_armsve.c:36:10: fatal error: 'sys/auxv.h' file not found
#include <sys/auxv.h>
         ^~~~~~~~~~~~
1 error generated.
make: *** [obj/arm64/config/armsve/bli_cntx_init_armsve.o] Error 1`

doing `configure firestorm` also "worked" , but calling `make install` yielded: 

 `../../../blis/version:1:1: error: expected unqualified-id
0.9.0
^`

Update: Apparently installing through homebrew "worked" but I'm still trying to figure out to what extent

**Comment by fgvanzee** [comment]
@jdiamondGitHub @figual @dnparikh @xrq-phys Any ideas here?

**Comment by xrq-phys** [comment]
I see. The problem seems to be that `arm64` metaconfig includes `armsve`, enabling [this block](https://github.com/flame/blis/blob/9453e0f163503f64a290256b4be53d8882224863/frame/base/bli_cpuid.c#L1181-L1184), while `has_sve` is only defined under `#ifdef __linux__` [here](https://github.com/flame/blis/blob/9453e0f163503f64a290256b4be53d8882224863/frame/base/bli_cpuid.c#L1051).

**Comment by devinamatthews** [comment]
I can take a look next week (I have an M1 machine now yay).

**Comment by devinamatthews** [comment]
@cgebhart-lbl PR #679 fixes the autodetection issue and the `sys/auxv.h` issue. I couldn't reproduce the problem with the `expected unqualified-id` error though. Installing on M1 using `auto`, `firestorm`, and `arm64` all work.
