### ISSUE TITLE
Incorrect result in axpys (theoretically)

### ISSUE THREAD

**Issue by devinamatthews** [flame/blis#69]
The `???axpys` family of macros could give the incorrect result for `alpha` and `x` complex and `y` real. For example, `zzdaxpys` calls `daxpyris` which computes `yr += ar * xr` instead of the correct result `yr += ar * xr - ai * xi`.

One way to fix this is to drop all of the scalar macros and just use C99 complex operators like normal people.

**Comment by fgvanzee** [comment]
@devinamatthews Thanks for bringing this to my attention. 

As for why I don't use the built-in C99 complex operators, I investigated this a while back and ran into a snag. There was a reason I didn't switch whole hog to `complex` and `double complex`, but I can't remember now. It may take a while for me to rediscover the reason (or maybe I wrote a comment somewhere).

**Comment by jeffhammond** [comment]
@fgvanzee Just a guess, but perhaps Fortran ABI compatibility is not guaranteed by C99 complex?  My understanding is that C++ interoperability is fine though.

**Comment by devinamatthews** [comment]
@jeffhammond: I talked to @fgvanzee, and apparently the primary issue is/was doing updates to just the real or imaginary part which is not simple in pure C99. But, the standard apparently specifies the binary layout such that something like this would work:

```C
#define bli_zreal(z) (((double*)&(z))[0])
#define bli_zimag(z) (((double*)&(z))[1])
bli_zimag(whatever) = 3;
```

except where `z` is an expression, but the current `bli_?real/imag` macros don't support that anyways. Funny story: apparently both gcc and icc emit highly sub-optimal code for the following:

```C
void set_real(double complex* a, double r)
{
    a = r + cimag(a)*I;
}
```

**Comment by jeffhammond** [comment]
@devinamatthews I would probably just write that in intrinsics if I wanted it to perform...

**Comment by devinamatthews** [comment]
I assume this is all fixed given MP/MD support.
