### ISSUE TITLE
One question when compiling source code in linux arm arch

### ISSUE THREAD

**Issue by Hins** [flame/blis#694]
since my dev machine is arm arch, i installed blis by source code other than pip command.
I changed [return "x86_64"] with return "generic" in setup.py file, meanwhile remove gcc compiler options in x86 arch, such as "-mfpmath"、"-mavx" and others.
I can't find "blis/cy.c" file during compiling, the commd is `gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -fPIC -I/home/sjt/xtpan/python3_exp/bin/blis-0.7.0/include -I/home/sjt/xtpan/python3_exp/bin/blis-0.7.0/blis/_src/include/linux-generic -I/home/sjt/xtpan/python3_exp/include/python3.7m -c blis/cy.c -o build/temp.linux-aarch64-cpython-37/blis/cy.o -std=c99`.
Thanks in advance.

**Comment by devinamatthews** [comment]
To install BLIS from source, you should probably avoid using the PIP distribution files. Here are some simple steps:

1. `git clone https://github.com/flame/blis && cd blis`
2. `./configure -tomp auto` This uses OpenMP for threading which is probably what you want
3. `make && make install`
4. You can also run `make check` to make sure everything is working properly.

**Comment by xrq-phys** [comment]
Perhaps @Hins is referring to [this PyPI installer project](https://pypi.org/project/blis/) whose code should lie elsewhere.
Guessing from the explanations there, what you should do is:
```bash
BLIS_ARCH="cortexa57" pip install spacy --no-binary blis
```
If that doesn't compile, [this repo](https://github.com/explosion/cython-blis) shall be the place to raise an issue.
