### ISSUE TITLE
Constants in bli_const.c "undefined" on OSX

### ISSUE THREAD

**Issue by devinamatthews** [flame/blis#73]
It seems that the linker on OSX is not able to find any of the constants defined in `bli_const.c`, such as BLIS_ONE etc. The problem, according to [this page](http://stackoverflow.com/questions/19398742/os-x-linker-unable-to-find-symbols-from-a-c-file-which-only-contains-variables) is that undefined constants end up as "common" symbols which are ignored by the OSX linker. The two available solutions seem to be:

1. Initialize the variables. Since these are `obj_t`'s, default-initialization with `...={}` should be OK (and they are initialized for real later).
2. Compile with `-fno-common`. This would have to be added to each configuration or in `common.mk`.

I am not sure when this problem first appeared, since I thought I had successfully compiled after the "big commit", but I am seeing it in my branch based off of cbcd0b739dc54bd14fbb46aeda267c26725cd70f. Using gcc-5.3.0 from Homebrew instead of the system "gcc" may also be a contributing factor.

**Comment by devinamatthews** [comment]
Two updates:

1. Both methods mentioned above seem to fix the problem.
2. The `gemm_cntl*` and `trsm_[lr]_cntl*` constants and possibly others are also affected.

**Comment by fgvanzee** [comment]
1. This is super annoying. I wonder if it runs afoul of any standards.
2. I suppose the most maintainable way of addressing this is solution 1. But you are right, it would affect the control tree as well. Can we `#define` an  initializer expression in the spirit of `PTHREAD_MUTEX_INITIALIZER`?

**Comment by devinamatthews** [comment]
1. Not a standards issue, just a Mach limitation.
2. I am actually leaning towards 1. since it is a global change. If you do want to initialize, though, default-initialization with `{}` will just fill it with zeros instead of random data which should be fine.

**Comment by fgvanzee** [comment]
Sure, `{}` is fine for now. I may go back and replace them with `_INITIALIZER` macros in the future.

**Comment by devinamatthews** [comment]
I'll set up a PR.
