### ISSUE TITLE
libblis.so.4.loc Problem!

### ISSUE THREAD

**Issue by CCMKCCMK** [flame/blis#756]
I am using windows wsl2
 then when i run `make -j`

error occurs:
Creating symlink lib/skx/libblis.so.4
ln: failed to create symbolic link 'libblis.so.4.loc': Operation not permitted
make: *** [Makefile:807: lib/skx/libblis.so.4] Error 1

i tried using sudo but fail as well

**Comment by CCMKCCMK** [comment]
the solution is very simple: 
instead of using the /mnt/c/......... ,which is actually the Windows file system,
I tried move everything to /home, which is the Linux system, 
then everything back to normal!

**Comment by fgvanzee** [comment]
Glad you were able to find a fix to your problem. Thanks for using BLIS!
