### ISSUE TITLE
hpx runtime support breaks in testsuite

### ISSUE THREAD

**Issue by ct-clmsn** [flame/blis#758]
the hpx runtime support is currently broken in the blis testsuite. the testsuite segmentation faults due to posix thread calls conflicting with the hpx runtime system. the solution requires removing posix threads in testsuite for the hpx backend.

**Comment by fgvanzee** [comment]
Thanks @ct-clmsn. I took a look at #759 and it looks fine. I made minor changes and plan to merge shortly.
