### ISSUE TITLE
Multithreading.md does not introduce include file needed for function calls

### ISSUE THREAD

**Issue by BarrySmith** [flame/blis#763]
Multithreading.md should, above the first mention of using C function calls to set the number of threads, indicate what include file needs to be included.

**Comment by fgvanzee** [comment]
How does this look, @BarrySmith?
---
## Globally at runtime

*NOTE: If you want to gain access to BLIS API function prototypes, be sure to `#include blis.h` from the relevant source files in your application.*

If you still wish to set the parallelization scheme globally, but you want to do so at runtime, BLIS provides a thread-safe API for specifying multithreading. Think of these functions as a way to modify the same internal data structure into which the environment variables are read. (Recall that the environment variables are only read once, when BLIS is initialized).
