### ISSUE TITLE
Header path for default source build and Debian should match

### ISSUE THREAD

**Issue by jedbrown** [flame/blis#786]
A default source build installs `$incdir/blis/blis.h`, suggesting that a user should `#include <blis/blis.h>`.

Debian installs `/usr/include/x86_64-linux-gnu/blis.h`, which works with `#include <blis.h>`. (This path is actually a symlink through the `/etc/alternatives` system, but that aspect does not concern us here.)

Upstream should decide (and convey to users) which schema is intended. @devinamatthews and @fgvanzee [have indicated in Discord](https://discord.com/channels/879093420801527858/879093420801527861/1170117964767445034) that `#include <blis.h>` is preferred, meaning that the default `make install` should be changed. Although symlinks `blis.h -> blis/blis.h` are problematic on Windows, the outer header could be a simple stub with `#include "blis/blis.h"`.

**Comment by jedbrown** [comment]
With 1.0 coming up, this should be resolved and documented prior to release.

**Comment by fgvanzee** [comment]
Thanks @jedbrown. Devin and I discussed this and we both agree that our preferred solution is to install a supplemental one-line `blis.h` header to the `INCDIR` install prefix (which is `PREFIX/include` by default, where `PREFIX` is the install prefix) that contains:
```c
#include <blis/blis.h>
```
FYI: @cdluminate

**Comment by fgvanzee** [comment]
FYI, I'm working on a PR for this issue.

**Comment by cdluminate** [comment]
I will change the alternatives symlink installation path to synchronize with you.

**Comment by fgvanzee** [comment]
@jedbrown I think this issue is resolved now. Let me know if there's anything left/else to discuss. Thanks for your feedback!

**Comment by fgvanzee** [comment]
@jedbrown Closing this issue for now. Please let us know if you have any further concerns.
