### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jakirkham** [flame/blis#792]
Happy New Year! 🎆

Looks like there has been [a lot of activity since the last release]( https://github.com/flame/blis/compare/0.9.0...master ), which is great to see 😄

Was wondering what folks were thinking about in terms of when the next release might come out?

**Comment by fgvanzee** [comment]
Hi @jakirkham. Thanks for your inquiry.

We've done most of our QA on our next release (1.0), but one of our collaborators in industry stumbled upon a performance regression for complex operations. I'd prefer to get to the bottom of that before finalizing our next version. It could be something simple, or specific to certain ARM hardware, but we just don't know yet.

I'm just as eager to get 1.0 out as anyone else, but, we want to at least try to get it right the first time. We appreciate your patience in the meantime.

**Comment by jakirkham** [comment]
Thanks Field! 🙏

Appreciate the prompt and detailed update

No worries. Understand how that goes. Was mostly trying to get a sense of roughly when a release might be planned, but understand that can be a bit nebulous

Happy to wait patiently and listen for any exciting updates 🙂

Best of luck on the perf regression 🍀

**Comment by fgvanzee** [comment]
Thanks for your understanding, @jakirkham.

**Comment by fgvanzee** [comment]
> Thanks Field! 🙏
> 
> Appreciate the prompt and detailed update
> 
> No worries. Understand how that goes. Was mostly trying to get a sense of roughly when a release might be planned, but understand that can be a bit nebulous
> 
> Happy to wait patiently and listen for any exciting updates 🙂
> 
> Best of luck on the perf regression 🍀

@jakirkham I think we've nailed down the blocker issue that was preventing us from moving forward with a release. (It was a false alarm in some ways; the problem appears to have been with the test driver code, not the framework itself.)

This means that we will be able to resume our push towards 1.0 soon. Thanks for your patience.

**Comment by jakirkham** [comment]
Great news! Glad to hear things are clearing up, Field 😄

**Comment by fgvanzee** [comment]
I'm going to close this issue now that the new release is imminent. Thanks again for hanging in there with us, @jakirkham.
