### ISSUE TITLE
getting error as illegal instruction 

### ISSUE THREAD

**Issue by garadeaniket** [flame/blis#800]
Hi ,
After running  the ./a.out  after compiling the example codes on a64fx using  gcc 04level3.c -I /path/to/include/  -L /path/to/lib/  -lblis -lm    , i am getting "Illegal instruction(core dumped) error.

Kindly help to resolve the error

**Comment by devinamatthews** [comment]
Ah, I see you did submit an issue. Reposting from Discord:

Please include the specific version of BLIS used (release number or git commit ID). It would also be helpful if you could:
  1) Configure and build blis using ./configure -dopt a64fx
  2) Build your example program using gcc -g
  3) Run with gdb, gdb ./a.out and enter the following commands:
        1) r to start the program it should run until the illegal instruction error occurs
        2) bt to get a backtrace. Please send this information.
        3) disas this will output a disassembly. You will need the press enter until you get to a page with => to mark the current instruction. Please send this page of output. 

Technically 3.iii) can be done on an optimized binary or from the core dump.

**Comment by garadeaniket** [comment]
Blis version used : blis-0.9.0 , I have also attached the backtrace and dissassemble output after running gdb for blis example 04level3.c.
[backtrace.txt](https://github.com/flame/blis/files/14339891/backtrace.txt)
[disassemble.txt](https://github.com/flame/blis/files/14339892/disassemble.txt)

**Comment by devinamatthews** [comment]
It looks like you need to add `CFLAGS="-DCACHE_SECTOR_SIZE_READONLY"` to the flags passed to `configure`. E.g. `./configure -tomp CFLAGS="-DCACHE_SECTOR_SIZE_READONLY" a64fx`.

**Comment by garadeaniket** [comment]
Its working .. Thankyou
