### ISSUE TITLE
Facing issue when running following command: pip install --upgrade --no-cache-dir thinc

### ISSUE THREAD

**Issue by rishav12** [flame/blis#810]
[blis issue.txt](https://github.com/user-attachments/files/15710952/blis.issue.txt)

I am trying to run spacy source code, but ran into "'**thinc\backends\cblas.pxd' not found**". On debugging more using chatgpt and chrome I got to know that there is issue with thic module. So I performed this command "pip install --upgrade --no-cache-dir thinc", which is again failing :
_**" Building wheel for blis (pyproject.toml): started
        Building wheel for blis (pyproject.toml): finished with status 'error'"**_

I have attached the full call stack with this. Please help me on this.

**Comment by devinamatthews** [comment]
The BLIS PIP package is not maintained in this repo. You'll have to open an issue [here](https://github.com/explosion/cython-blis/issues).
