### ISSUE TITLE
errors with scalapack due to [cz]symv and [cz]syr interfaces

### ISSUE THREAD

**Issue by ajaypanyala** [flame/blis#812]
Using `BLIS` to configure Reference [LAPACK](https://github.com/Reference-LAPACK/lapack) and [ScaLAPACK](https://github.com/Reference-ScaLAPACK/scalapack), results in link errors (duplicate definitions) due to the `[cz]symv` and `[cz]syr` interfaces introduced in Commit 37ca4fd.   `ScaLAPACK` defines them [here](https://github.com/Reference-ScaLAPACK/scalapack/tree/master/PBLAS/SRC/PTZBLAS)

**Comment by devinamatthews** [comment]
I guess we need a configure flag to turn these off.

**Comment by fgvanzee** [comment]
Regardless of what we do, maybe LAPACK/ScaLAPACK need a `configure` flag to turn them off on their side.

**Comment by ajaypanyala** [comment]
`ScaLAPACK` works fine with BLIS before Commit 37ca4fd.  There doesn't seem like a way to turn those interfaces off in `ScaLAPACK`.

**Comment by devinamatthews** [comment]
@ajaypanyala is [cz]syr2 affected?

**Comment by devinamatthews** [comment]
Looks like it is.

**Comment by ajaypanyala** [comment]
Atleast on my end, I do not see any issues with `[cz]syr2`

**Comment by devinamatthews** [comment]
It's because I didn't enable them in BLIS when I did `[cz]syr` and `[cz]symv` which was an oversight on my part. I've included all 3 in the fix.

**Comment by devinamatthews** [comment]
@ajaypanyala please try the branch `scalapack-compat` and configure with the option `--enable-scalapack-compat`.

**Comment by ajaypanyala** [comment]
Using `scalapack-compat` branch with `--enable-scalapack-compat` worked. thanks!
