### ISSUE TITLE
sandybridge segfault with 32-bit dim_t

### ISSUE THREAD

**Issue by devinamatthews** [flame/blis#83]
The culprit seems to be the load of `k` in the micro-kernel which is explicitly a `movq`. Changing type of `k_iter` and `k_next` to [u?]int64_t should fix it.

**Comment by fgvanzee** [comment]
@devinamatthews I assume that you are trying to configure with `-i 32`? May I ask why you are forcing the use of internal 32-bit integers on Sandy Bridge?

**Comment by devinamatthews** [comment]
This came about in a very roundabout way which is not really relevant. 
In any case it is probably best to either prohibit this configuration or 
copy to a 64-bit variable to not segfault.

**Comment by fgvanzee** [comment]
I favor the copy-to-`uint64_t` option. I'll leave this issue open until someone (maybe me) applies a comprehensive fix to all x86_64 microkernels.
