### ISSUE TITLE
Problem in cross-compile for RISC-V develop board

### ISSUE THREAD

**Issue by ztjjj9** [flame/blis#836]
Hello,
I am performing cross-compilation on an X86 Linux host to build the BLIS library for a RISC-V development board. I tried to install a single-threaded version of the BLIS library using the following configuration command:
`./configure --prefix=Path/to/blis_lib/2 CC=Xuantie-900-gcc-linux-6.6.0-glibc-x86_64-V3.0.1/bin/riscv64-unknown-linux-gnu-gcc CXX=Xuantie-900-gcc-linux-6.6.0-glibc-x86_64-V3.0.1/bin/riscv64-unknown-linux-gnu-g++ --disable-threading --disable-shared rv64iv`  
`make`  
`make install`  
However, when I try to compile `blis/test/test_gemm.c` on the host machine using the cross-compilation toolchain, I encounter the following errors:
```
lib//libblis.a(bli_pthread.o): in function `bli_pthread_create':
bli_pthread.c:(.text+0x0): undefined reference to `pthread_create'

lib//libblis.a(bli_pthread.o): in function `bli_pthread_join':
bli_pthread.c:(.text+0x8): undefined reference to `pthread_join'

/libblis.a(bli_pthread.o): in function `bli_pthread_mutex_destroy':
bli_pthread.c:(.text+0x1c): undefined reference to `pthread_mutex_trylock'

lib//libblis.a(bli_pthread.o): in function `bli_pthread_cond_init':
bli_pthread.c:(.text+0x38): undefined reference to `pthread_once'

lib//libblis.a(bli_pthread.o): in function `bli_pthread_cond_destroy':
bli_pthread.c:(.text+0x40): undefined reference to `pthread_barrier_init'

lib//libblis.a(bli_pthread.o): in function `bli_pthread_cond_wait':
bli_pthread.c:(.text+0x48): undefined reference to `pthread_barrier_destroy'

lib//libblis.a(bli_pthread.o): in function `bli_pthread_cond_broadcast':
bli_pthread.c:(.text+0x50): undefined reference to `pthread_barrier_wait'
```
I am compiling test_gemm.c using the following command:
`Xuantie-900-gcc-linux-6.6.0-glibc-x86_64-V3.0.1/bin/riscv64-unknown-linux-gnu-gcc test_gemm.c -I blis_lib/2/include/ -L blis_lib/2/lib/ -o r1 -lblis -lm`
I have explicitly disabled threading in the BLIS configuration, but it seems that some threading functions are still being referenced. Could you please provide guidance on how to cross-compile blis for RISC-V develop board?

Thank you for your assistance!

**Comment by devinamatthews** [comment]
You can use the `--disable-system` option of `configure` to remove the dependency on pthreads. Alternatively, if pthreads should be available then we can try and determine why the proper link option is not detected.

**Comment by ztjjj9** [comment]
> You can use the `--disable-system` option of `configure` to remove the dependency on pthreads. Alternatively, if pthreads should be available then we can try and determine why the proper link option is not detected.
Thank you for your suggestions. After adding the --disable-system option to the configure command, the previous pthread-related errors disappeared, and I can now use the single-threaded version of BLIS normally. However, I am still thinking about why those errors occurred even when I disabled threading by using --disable-threading.

**Comment by devinamatthews** [comment]
This is because pthreads is used in some areas of the code for all threading models, and "disable threading" really just means "don't turn on any additional threading modes (beyond single-threaded)". Thus, some pthreads functions keep being used unless the compatibility layer is turned on via `--disable-system`. Either way, glad it worked for you!
