### ISSUE TITLE
reg-BLAS.R test fails

### ISSUE THREAD

**Issue by lejeczek** [flame/blis#84]
being not a programmer I'd like to ask - what might the problem?

Type 'q()' to quit R.

> ## PR#4582 %*% with NAs
> 
> stopifnot(is.na(NA %_% 0), is.na(0 %_% NA))
> ## depended on the BLAS in use.
> ## found from fallback test in slam 0.1-15
> ## most likely indicates an inaedquate BLAS.
> 
> x <- matrix(c(1, 0, NA, 1), 2, 2)
> y <- matrix(c(1, 0, 0, 2, 1, 0), 3, 2)
> (z <- tcrossprod(x, y))
>      [,1] [,2] [,3]
> [1,]   NA   NA    0
> [2,]    2    1    0
> stopifnot(identical(z, x %_% t(y)))
> Error: identical(z, x %_% t(y)) is not TRUE

**Comment by devinamatthews** [comment]
Is BLIS being used for the `tcrossprod(x, y)` calculation or for `x %*% t(y)`?

**Comment by lejeczek** [comment]
I'd guess only BLIS is being used there, I build BLIS:
'./configure --prefix=/local.CPUnative --enable-shared --enable-threading=omp --enable-cblas piledriver'
then I try to substitute R's blas with BLIS and during R build it fails above test.

**Comment by devinamatthews** [comment]
Since it's been so long, I'm going to close. Please reopen if you can reproduce the issue on the latest BLIS.
