### ISSUE TITLE
License/copyright headers in need of update

### ISSUE THREAD

**Issue by fgvanzee** [flame/blis#87]
The license/copyright headers at the top of each source file need to be updated. The copyright year needs to be changed to "2016". (I never got around to updating it in 2015 and so it still reads "2014".)

Unfortunately, this change is going to touch virtually every file in the repository. If you have any objections, or this will disrupt your work, please speak up.

**Comment by devinamatthews** [comment]
What is the benefit of per-file copyright licenses vs. a single 
top-level LICENSE file? Do any of the files actually say anything different?

**Comment by fgvanzee** [comment]
For most files, no, there is no difference. However, we are about to integrate some changes submitted by an industry partner, and they asked us to include them as a separate copyright line in the BSD license header.

At one time, I think OTC preferred having the full license on each file, though I'm not sure if that is strictly required. (In libflame's source headers, we simply state the license and where to find the full text.)

**Comment by jeffhammond** [comment]
Why do you need to change year? Copyright expiration is a long time. Seems
like you only need to change filed touched by the vendor contribution.

-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by fgvanzee** [comment]
Well I guess I don't **need** to update the year, like I need to stay hydrated, but as an agent of the UT I continue to make new changes to BLIS all the time, and those changes are done today, not in 2014. And rather than update the header of each file I change, it's easier to just update all files annually.

Also, I would be lying if I claimed there wasn't an obsessive-compulsive element in here somewhere.

**Comment by jeffhammond** [comment]
@fgvanzee It's 2020 so if you are going to do this, now is as good a time as ever 😄

**Comment by fgvanzee** [comment]
@jeffhammond I learned recently that I misunderstood the semantics behind copyright years. It doesn't really matter much for 3-clause BSD, anyway, but to the extent that it *does* matter, by always changing the year to be the most current we are actually throwing away information. Ideally you would want to go from "2019" to "2019-2020" and then just widen the range. Or use a series (list) of years.

But like I said, it doesn't really matter. So I'm going to close.
