### ISSUE TITLE
Issue with pthreads and memory broker abstraction

### ISSUE THREAD

**Issue by tlrmchlsmth** [flame/blis#89]
When compiling with pthreads now, I  get a bunch of warnings and errors like the below. If I back up to the commit ce59f81, these go away.

> In file included from ./frame/thread/bli_mutex.h:43:0,
                 from ./frame/thread/bli_thread.h:56,
                 from ./frame/include/blis.h:74,
                 from frame/base/bli_membrk.c:36:
frame/base/bli_membrk.c: In function ‘bli_membrk_init’:
./frame/base/bli_membrk.h:56:2: warning: passing argument 1 of ‘pthread_mutex_init’ from incompatible pointer type
  ( &( (membrk_p)->mutex ) )
  ^
./frame/thread/bli_mutex_pthreads.h:53:22: note: in definition of macro ‘bli_mutex_init’
  pthread_mutex_init( mtx_p ); \
                      ^
frame/base/bli_membrk.c:44:18: note: in expansion of macro ‘bli_membrk_mutex’
  bli_mutex_init( bli_membrk_mutex( membrk ) );
                  ^
In file included from ./frame/thread/bli_mutex_pthreads.h:42:0,
                 from ./frame/thread/bli_mutex.h:43,
                 from ./frame/thread/bli_thread.h:56,
                 from ./frame/include/blis.h:74,
                 from frame/base/bli_membrk.c:36:
/usr/include/pthread.h:723:12: note: expected ‘union pthread_mutex_t *’ but argument is of type ‘struct mtx_s *’
 extern int pthread_mutex_init (pthread_mutex_t *__mutex,
            ^
In file included from ./frame/thread/bli_mutex.h:43:0,
                 from ./frame/thread/bli_thread.h:56,
                 from ./frame/include/blis.h:74,
                 from frame/base/bli_membrk.c:36:
./frame/thread/bli_mutex_pthreads.h:53:2: error: too few arguments to function ‘pthread_mutex_init’
  pthread_mutex_init( mtx_p ); \
  ^
frame/base/bli_membrk.c:44:2: note: in expansion of macro ‘bli_mutex_init’
  bli_mutex_init( bli_membrk_mutex( membrk ) );
  ^
In file included from ./frame/thread/bli_mutex_pthreads.h:42:0,
                 from ./frame/thread/bli_mutex.h:43,
                 from ./frame/thread/bli_thread.h:56,
                 from ./frame/include/blis.h:74,
                 from frame/base/bli_membrk.c:36:
/usr/include/pthread.h:723:12: note: declared here
 extern int pthread_mutex_init (pthread_mutex_t *__mutex,
            ^

**Comment by fgvanzee** [comment]
Thanks for reporting this, Tyler. I'm looking into it now.

**Comment by tlrmchlsmth** [comment]
Is Travis CI configured to test BLIS with pthreads and openmp turned on?

**Comment by fgvanzee** [comment]
Clearly not. I'll have a fix in soon.

**Comment by jeffhammond** [comment]
Should this issue be closed?  Field's last commit indicates that it is resolved.

**Comment by fgvanzee** [comment]
Yes, thanks for reminding me Jeff. I kept in open in case by chance my fix was not successful.
