### ISSUE TITLE
How to cross compile for use on windows?

### ISSUE THREAD

**Issue by musm** [flame/blis#90]
Hi, I would like to try blis. Is there a guide on how to cross compile on linux so that I can use blis on windows?

**Comment by fgvanzee** [comment]
@musm, Unfortunately, we don't have a working Windows build system for BLIS (as is the case with libflame), nor do we have any documentation on cross-compiling for Windows. (Most of our users build and execute on GNU/Linux, and virtually all of those that don't use OS X.)

**Comment by musm** [comment]
Alright. Well there's a simple answer as to why you don't have any windows users. If there is no windows support you will not have any windows users.  

I was looking into exploring replacing blas and lapack with your libraries, however if there is no windows support it's impossible. Think about the millions of windows users that use matlab.

**Comment by musm** [comment]
I just saw: https://github.com/flame/blis/issues/57  so clearly there is  interest in Windows support if a Continuum Analytics dev was interested in using these libraries. Looks like he too could not since it's simply unacceptable to not support windows for Python.

**Comment by fgvanzee** [comment]
It's not that we would not like to have Windows support. It's that we don't have the resources to make it happen, especially given that we have many other competing priorities.

If you would like to take this on as a pet project, we would happily accept your contributions.

**Comment by RoyiAvital** [comment]
I wish for Windows support as well.
Having this with integration to [Eigen](https://github.com/eigenteam/eigen-git-mirror) could be a real treat in Windows.

**Comment by fgvanzee** [comment]
@RoyiAvital Thanks for your interest in BLIS.

Perhaps you could ask @isuruf if his recent work on providing Windows ABI support via clang/appveyor (via pull request #227) would benefit you?

**Comment by insertinterestingnamehere** [comment]
Using the binaries from conda-forge via the conda package manager may make things easier as well. See https://anaconda.org/conda-forge/blis. I think those binaries are already MSVC compatible, but you can get clang via conda-forge too if that's necessary.

**Comment by RoyiAvital** [comment]
@fgvanzee ,
I think Windows should be first class citizen for the BLIS world.
There are many users which would appreciate BLIS as a replacement for OpenBLAS on Windows.

**Comment by fgvanzee** [comment]
> I think Windows should be first class citizen for the BLIS world.
> There are many users which would appreciate BLIS as a replacement for OpenBLAS on Windows.

@RoyiAvital I don't disagree with you, and I sympathize with your willingness/desire to migrate away from OpenBLAS for Windows. In an ideal world, we would support all operating systems. Unfortunately, we have limited dollars, time, and expertise, and we must deploy our resources so they have the maximum impact for the HPC community. For now, that means targeting GNU/Linux, BSD, and OS X, which are the most-frequently used platforms for high-performance applications. For other operating system support, we must rely on the community at-large to step up and make contributions and provide support where they can.

**Comment by musm** [comment]
Can we at least open this issue? Maybe someone will see the issue and chose to tackle the problem.

**Comment by isuruf** [comment]
@musm, you can compile BLIS using either Clang, MinGW-w64 or Cygwin. There's no need to open the issue.

**Comment by musm** [comment]
cross compilation is now supported?

**Comment by isuruf** [comment]
I don't think blis support cross-compilation at all. You might have to hack configure to set `os_name`

**Comment by musm** [comment]
To be clear, I want a shared library that can be used on windows. I.e. to be able to cross compile from Cygwin or Mysys2 to windows.  Is this possible?

**Comment by isuruf** [comment]
You can compile BLIS using Cygwin or Msys2 on windows, but you cannot cross compile from Linux.

**Comment by musm** [comment]
Thanks!

**Comment by isuruf** [comment]
```diff
diff --git a/configure b/configure
index 7c76427d..47bd7296 100755
--- a/configure
+++ b/configure
@@ -1033,7 +1033,7 @@ auto_detect()
        # Set the linker flags. We need pthreads because it is needed for
        # parts of bli_arch.c unrelated to bli_arch_string(), which is called
        # by the main() function in ${main_c}.
-       if [ $is_win = no ]; then
+       if [[ $is_win == no || "$cc_vendor" != "clang" ]]; then
                ldflags="${LIBPTHREAD--lpthread}"
        fi
 
@@ -2062,7 +2062,7 @@ main()
 
        # -- Check the operating system --------------------------------------------
 
-       os_name=$(uname -s)
+       os_name=MINGW
        os_vers=$(uname -r)
        echo "${script_name}: detected ${os_name} kernel version ${os_vers}."
 
@@ -2834,7 +2834,7 @@ main()
        # For Windows builds, clear the libpthread_esc variable so that
        # no pthreads library is substituted into config.mk. (Windows builds
        # employ an implementation of pthreads that is internal to BLIS.)
-       if [ $is_win = yes ]; then
+       if [[ $is_win == yes && "$cc_vendor" == "clang" ]]; then
                libpthread_esc=
        fi
 ```

You can cross-compile from Linux by using the diff above and running,
```bash
CFLAGS=-fno-asynchronous-unwind-tables CC=x86_64-w64-mingw32-gcc ./configure --enable-shared --disable-static x86_64
```

**Comment by fgvanzee** [comment]
@isuruf Forgive me if this is a dumb question, but can @musm use the Windows library artifacts from AppVeyor? (There's probably some nuance to cross-compilation that I'm not following here.)

**Comment by isuruf** [comment]
@fgvanzee, depends on the compiler @musm is using. If it's Cygwin, then the dlls from appveyor artifacts might not be compatible.
