### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by ShadenSmith** [flame/blis#91]
The "new BLAS-like API" link in the README is empty and leads to a 404.

Should it instead point to [https://github.com/flame/blis/wiki/BLISAPIQuickReference](https://github.com/flame/blis/wiki/BLISAPIQuickReference)?

**Comment by jeffhammond** [comment]
I support you converting this issue to a pull request ;-)

-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/
