### ISSUE TITLE
Document level-0 operations in BLASAPIQuickReference wiki

### ISSUE THREAD

**Issue by fgvanzee** [flame/blis#95]
To clarify, I'm referring to the level-0 object-based APIs in `frame/0`, not the level-0 scalar macros in `frame/include/level0`.

**Comment by fgvanzee** [comment]
On second thought, very few people care about the level-0 operations. Closing.

**Comment by tonyskjellum** [comment]
What are they ?

Anthony Skjellum, PhD
205-807-4968

**Comment by fgvanzee** [comment]
The level-0 operations are defined in `frame/0` and have the `sc` suffix--for example, `mulsc`. These are operations on scalars.
