### ISSUE TITLE
Duplicate mem_manager_mutex 

### ISSUE THREAD

**Issue by tlrmchlsmth** [flame/blis#98]
When I try to link with BLIS with pthreads turned on, I get the following:

>   = note: duplicate symbol _mem_manager_mutex in:
>     /Users/tyler/blis/lib/libblis.a(bli_mem.o)
>     /Users/tyler/blis/lib/libblis.a(bli_memsys.o)
> ld: 1 duplicate symbol for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

Changing
`pthread_mutex_t mem_manager_mutex = PTHREAD_MUTEX_INITIALIZER;`
to
`extern pthread_mutex_t mem_manager_mutex;`
in either bli_mem.c or bli_memsys.c allows me to link, but I don't know if this is the right thing to do

**Comment by fgvanzee** [comment]
Tyler, this should be fixed now in 9cda605. Thanks for this report.
