### ISSUE TITLE
double typedef membrk_t

### ISSUE THREAD

**Issue by tlrmchlsmth** [flame/blis#99]
membrk_s is typedeffed to membrk_t both in frame/base/bli_membrk.h and in frame/include/typedefs.h

This is apparently not legal in C99

**Comment by ShadenSmith** [comment]
It is however valid C11, and in practice most C99 compilers will compile it. For example, GCC allows it unless `-std=c99 -pedantic` is used.

Unrelated, but the `_t` naming convention for types is [reserved](https://www.gnu.org/software/libc/manual/html_node/Reserved-Names.html) for POSIX.

**Comment by fgvanzee** [comment]
@tlrmchlsmth Thanks for the report, Tyler. This has been fixed in 970745a.
@ShadenSmith Thanks for your comments. I was unaware that _t was claimed as "reserved" by POSIX. Perhaps I'll fix this in future libraries, and/or if there is an actual type collision. :)

**Comment by jeffhammond** [comment]
Indeed, @ShadenSmith, I'm pretty sure that every C project of more than 1KLOC violates the `_t` rule 😱

**Comment by ShadenSmith** [comment]
Heh, including [my own](https://github.com/ShadenSmith/splatt/blob/master/src/base.h#L25) :-).
